### ISSUE TITLE
Can't have more than one TagClassField by form

### ISSUE THREAD

**Issue by julirio** [applegrew/django-select2#100]
When filtering a queryset by some "value", and is not found, raise a ValueError, and the object with "value" info is created. 
But in the case have a form with two TagClassField, the model is unique=True, and want to add the same tagField to both fields, when save the form raise an IntegrityError: column name is not unique.

My code:
```
class Genre(models.Model):
    name = models.CharField(max_length=100, unique=True)


class GenreField(AutoModelSelect2TagField):
     queryset = Genre.objects
     search_fields = ['name__icontains', ]

     def get_model_field_values(self, value):
           return {'name': value}

class ProfileForm(forms.ModelForm):  
    genres = GenreField(widget=AllowSpacesSelect2TagWidget(), required=True)
    critiquing_genres = GenreField(widget=AllowSpacesSelect2TagWidget(), required=False)
```
The problem is that create_new_value method try to create a new object, but in the example mentioned above, if insert the same value to both fields (and is not created in db) when try to create a Genre instance with critiquing_genres value, raise the IntegrityError.

I fixed the problem by overwriting create_new_value method to use django method get_or_create_object, so can use GenreField to many fields in form.

**Comment by codingjoe** [comment]
@julirio tho you're example is rather odd, the bug would also appear if multiple users add the field at the same time.

**Comment by daddz** [comment]
I ran into a similar error:

User types in an existing Name but does not wait for the JS request to finish.

Steps to reproduce:
1. Tag field is a "AutoModelSelect2TagField"
2. Add a tag called "foo" to some model
3. Add tag "foo" to some other model by writing it really fast and hitting tab (e.g. don't wait for the input suggestions to finish and show up)
4. Try to save
5. See IntegrityError

Maybe that helps a bit.
