### ISSUE TITLE
Heavy Widgets are misaligned and not displaying the field's label

### ISSUE THREAD

**Issue by rizumu** [applegrew/django-select2#121]
When using `AutoHeavySelect2Widget` or any of the heavy widgets my City field is rendered incorrectly. It is misaligned and missing its label. This is a screenshot of the error:

![heavy-widget](https://cloud.githubusercontent.com/assets/27119/3904566/26d0f782-22db-11e4-8b81-c9e8e23c55fe.png)

```
class CityChoices(AutoModelSelect2Field):
    search_fields = ["name__icontains", ]
    queryset = City.objects


class LocationForm(forms.ModelForm):
    city = CityChoices(
        label = _("city"),
        widget=AutoHeavySelect2Widget(
            select2_options={
                "width": "32em",
                "placeholder": "Search cities",
            }
        ),
    )
```

If I only change `AutoHeavySelect2Widget`  to `Select2Widget` (or any light widget) all is good, see this screenshot.

![light-widget](https://cloud.githubusercontent.com/assets/27119/3904572/3c89ef2a-22db-11e4-8e99-e8a364017747.png)

I am only using the heavy widgets on my project so it took some time consider checking if light widgets had the same issue as the heavy one. This should help narrow down the fix, but at the moment I'm not sure where the fix for this resides. It seems it might be a javascript problem. Any suggestions of where to look?

**Comment by deepthivalisetti** [comment]
@rizumu I have the same issue with AutoModelSelect2MultipleField. The autoselect box is at the botton. Unaligned and no label for it though label is mentioned in the form field.
Can you please let me know where am I wrong? Below are the details
Django_select2: 4.2.2
Django: 1.8

choices.py:
class CustomersChoices(AutoModelSelect2MultipleField):
    queryset = Customer.objects
    search_fields = ('customer_name__istartswith',
                     'description__istartswith',
                     'user__first_name__istartswith',
                     'user__last_name__istartswith',
                     )

forms.py:
class CSDashboardFilterForm(forms.Form):
    customers = CustomersChoices(label='Customer(s)', required=False)
    is_expedite = forms.BooleanField(required=False, label='Is Expedite?')
    status = Select2ChoiceField(choices=CHOICES, required=False)
    facility_plant = ModelSelect2Field(queryset=Plant.objects, initial='----', required=False)

![image](https://cloud.githubusercontent.com/assets/17268585/25133789/5fc285c6-246b-11e7-80ad-d2c1e2f9ccdb.png)
