### ISSUE TITLE
AutoModelSelect2Field cant save a new model instance.

### ISSUE THREAD

**Issue by sztankatt** [applegrew/django-select2#128]
Hi! I have a foreign key in my database, for which I am using the `AutoModelSelect2Field`. Currently I could not work out, how to achieve the same functionality as in `AutoHeavySelect2TagField` where you define a function `get_model_field_values`.

Basically, I want the user to be able to type in a new value for that `ForeignKey` field, if there is nothing found currently in the database.

Is there a functionality already for this, and did I just miss it, or do I have to overwrite a lot of the code?

**Comment by codingjoe** [comment]
Hi @sztankatt that's what the `AutoHeavySelect2TagField` is for. I don't get your problem.
