### ISSUE TITLE
testapp - tags aren't displayed/added properly on questions

### ISSUE THREAD

**Issue by bcail** [applegrew/django-select2#132]
When I look in test.db from git, I see tags for both questions - but when I look at those forms on the webpage, no tags are displayed.

If I try to add my own tags, the first one seems to be properly saved to the tags table, but not subsequent tags. And only the first tag is associated with the question. And, the old tags that used to be associated with the question aren't anymore.

Am I missing something?

**Comment by bcail** [comment]
Here's some more detail on this issue - this time from an actual project I'm working on:

I am using a modified HeavyModelSelect2TagField for some keywords, and the widget is a HeavySelect2TagWidget with '\t' as the tokenSeparator and createSearchChoicePosition = 'bottom'. The code works great on Firefox and Chrome.

However, on Safari I'm seeing some issues. If I've entered two values in the field, when the page loads, it doesn't see the two values. I've traced the issue to the onInit: function in heavy_data.js - the 'val' variable is supposed to have two values (eg. 33,34), but on Safari, it only has the first one (eg. 33). It's pulling the this value from the event: val = e.select2('val');

My jquery version is 1.11.3.

Has anyone else seen this issue? Any thoughts on how to fix it?

**Comment by vikasgulati** [comment]
+1 Facing the same issue on Safari 8.0.5

**Comment by vikasgulati** [comment]
@codingjoe Was this resolved or something?

**Comment by codingjoe** [comment]
@vikasgulati I closed the bug with the release of version 5. Since we updated jQuery to version 2 as well as Select2 to version 4. This bug should also be covered by tests now.
Let me know if you're still having the same issue.

**Comment by vikasgulati** [comment]
@codingjoe Thanks for the details. Would check and let you know.

**Comment by codingjoe** [comment]
@vikasgulati sorry about the confusion. I closed all issues with the version 5 release, since its a complete rewrite. I should have left a comment when I closed the issue.
