### ISSUE TITLE
Hello sir,how can I use ModelSelect2MultipleField and maintain the "PLUS" feature?

### ISSUE THREAD

**Issue by hebijiandai** [applegrew/django-select2#135]
When I use "ModelSelect2MultipleField" I found that I lost the "plus" feature for manytomayfield,this is my code:

```python
bibliography = ModelSelect2MultipleField(
        label="书目",
        queryset=Bibliography.objects,
        widget=Select2MultipleWidget(
            select2_options={
                'width': '200px',
            }
        )
    )
```
If I want to maintain the 'plus' feature as the picture show,How can I do it?Thanks very much!

![1](https://cloud.githubusercontent.com/assets/5127081/5293377/846cc8e8-7bab-11e4-9421-023a75df5f7e.png)
![2](https://cloud.githubusercontent.com/assets/5127081/5293378/846d9fca-7bab-11e4-9ec5-c4d229241b68.png)

**Comment by codingjoe** [comment]
@hebijiandai you can always add the button yourself, by creating a subclass and adding a button the admin create view. Feel free create a pull request should you implement such a behaviour.
