### ISSUE TITLE
Readonly Attribute Ignored

### ISSUE THREAD

**Issue by JP-Ellis** [applegrew/django-select2#136]
Hi,

Regarding the widgets, `attrs['readonly'] = True` has no effect.  This should have a similar akin to `attrs['disabled'] = 'disabled'`, except that upon submitting the form, the data should still be passed on correctly.

Another user seems to have a fix (which I am about to try and implement) over at:  https://gist.github.com/czpython/7683425.

PS:  This is at least true with the Python3 branch.

**Comment by codingjoe** [comment]
duplicate to #146
