### ISSUE TITLE
can you update PyPi for new version of 4.2.2

### ISSUE THREAD

**Issue by li5tun** [applegrew/django-select2#138]
bootstrap css is not set correctly if I install from pip. I compared the code, it's different( but same version number 4.2.2).

**Comment by JonPeel** [comment]
Noticed the same with heavy_data.js and heavy_data.min.js when using pip.  Would love to see the update done soon =)

**Comment by codingjoe** [comment]
We are working on a new release. Until than please note, that you can always use a github repo for pip including a commit hash to freeze a "version".
