### ISSUE TITLE
AutoModelSelect2Field not clearable

### ISSUE THREAD

**Issue by codingjoe** [applegrew/django-select2#140]
You can not empty a `AutoModelSelect2Field` even if `required` is set  `True`.

**Comment by patgmiller** [comment]
I've noticed this same problem, once an item is selected, you can only ever select another item. But I believe the problem is when `required=False`, in that scenario one should be able to un-select.

**Comment by codingjoe** [comment]
@patgmiller so you think that the `AutoModelSelect2Field` doesn't take `blank=True` into account?

**Comment by patgmiller** [comment]
@codingjoe Last time I used it specifically was about 5 months ago. So I came back to see if any updates specific to that had been issued but couldn't find any except this one.

**Comment by codingjoe** [comment]
I'll look into it, but it might take a while. We need a good test suit first.

**Comment by patgmiller** [comment]
I'll try to duplicate it again as well with latest.

**Comment by patgmiller** [comment]
Here is my use case, it is with a django model admin form which is creating updating a profile model. 

```python

#models.py
class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile')

#forms.py
class UserNonMemberSelect2Choices(AutoModelSelect2Field):
    """
    Used with custom admin profile add form.

    NOTE: Not currently being used because it doesn't allow for easily clearing
    the field.
    """
    queryset = User.objects.filter(profile__isnull=True)
    search_fields = (
        'email__icontains',
        'username__icontains',
        'first_name__icontains',
        'last_name__icontains',
    )


class ProfileAdminForm(forms.ModelForm):
    # note that field is one to one required, but add form is used to link an un-linked user
    # or to create a new one based on another email field. so in this context user is not 
    # required. 

    user = UserNonMemberSelect2Choices(required=False)
    # ....
    class Meta:
        model = Profile
```

![screenshot - django-select2-required-false](https://cloud.githubusercontent.com/assets/3914379/6333076/3efb001e-bb47-11e4-95dc-b65282fbbf50.png)

Let me know if I can assist in any way. Thanks,
