### ISSUE TITLE
Select2 4.0

### ISSUE THREAD

**Issue by kevin-brown** [applegrew/django-select2#141]
We're in the process of finalizing the 4.0 release and are aiming to have it done by the end of this month at the latest.

https://select2.github.io/

Since I'm not extremely familiar with the plugin, I can't judge how easy it will be to support 4.0, but I might be able to help depending on how the tests are built.

**Comment by codingjoe** [comment]
@kevin-brown thanks for the info. Please let us know once you released. We will start integration once we solved all django/python related issues.

**Comment by mattamizer** [comment]
Is there work currently being done on this upgrade? I'm working on a project that requires the templating support provided in select2 4.0. It looks like select2 4.0.0 rc1 was released about 10 days ago. Thanks!

**Comment by codingjoe** [comment]
Yes, I'm on it, but I currently don't have too much time. We could definitely need a hand, feel free to join.

**Comment by mattamizer** [comment]
We're feeling a time crunch as well. If I get the time to work on it I certainly will. :)
