### ISSUE TITLE
error with bootstrap3

### ISSUE THREAD

**Issue by bcail** [applegrew/django-select2#145]
I have a form that uses a HeavyModelSelect2TagField with a HeavySelect2TagWidget. If I don't use a bootstrap3 template to display the form, it works. However, if I enable the bootstrap3 template, the tag widgets don't display at all, and I get the following js error:
Uncaught TypeError: Cannot read property 'empty' of undefined
https://github.com/applegrew/django-select2/blob/master/django_select2/static/js/heavy_data.js#L165

I've tried this with django-select 4.2.2. I also tried updating to commit d00ba18db14673b58a07970a191395e253881f48, which adds some bootstrap-related code, and I added the SELECT2_BOOTSTRAP setting, but I still got the same failure. I even tried copying select2-3.5.2 in, but that still failed.

Help?

**Comment by codingjoe** [comment]
Hi @bcail,

this would mean, that the data-valContainer has not been rendered in your template. Could you please check if this is the case?

If it would be interesting to find out why it's not rendered in the bootstrap mode.

Cheers,
joe

**Comment by bcail** [comment]
Right, I don't see data-valContainer. I see the hidden input element, and I see the hidden div that's supposed to contain the values that are added, but I don't see anything about valContainer. Not sure why, unfortunately.

**Comment by codingjoe** [comment]
Ok, now we know the error cause. I'd much appreciate if you could debug further, to find out why the input attribute isn't rendered properly. If not it would be cool if you could provide example code that recreates the bug.

Thanks for your support!

**Comment by bcail** [comment]
I compared the page loading between the version that works, and the version that doesn't. So far, the only difference I'm seeing is this:
<   <div class="select2-drop select2-drop-multi select2-display-none"> #doesn't work
---
>   <div class="select2-drop select2-drop-multi select2-display-none select2-drop-active"> #works

I'll look around more.

**Comment by bcail** [comment]
OK, closing this issue. Turns the problem was that I had jQuery being loaded twice - once in the head, and then again at the end of the document. Once we just loaded jQuery at the top, it worked. Thanks, Joe, for looking at this and for your work on django-select2.
