### ISSUE TITLE
Support for Generic Relations

### ISSUE THREAD

**Issue by xxinfinityxx** [applegrew/django-select2#147]
Hey there,

It would be nice to have a way to support Generic Foreign Keys (https://docs.djangoproject.com/en/1.6/ref/contrib/contenttypes/#generic-relations)

So far I've been able to hack my way into this but it seems to be a LOT of work... Any ideas about where I should start? If I manage to get this to work properly I could submit a PR...

Thanks

**Comment by codingjoe** [comment]
Hi @xxinfinityxx, let me stop you right there. There is a very simple rule of thumb regarding generic foreign keys: DON'T

There not really keys and a django construct using content types. That is nice, but creating an acutally search on top of that is almost impossible. You'd need to create a full text index like django watson does `django-waton`.

I'd recommend you to not waist your time here, but to rethink your db schema und remember that a generic foreign key isn't an actual foreign key.
Even if you'd pull it of to write something, it would be questionable if we would merge such a feature and therefore increase complexity.

**Comment by xxinfinityxx** [comment]
Well, my application requires them and believe me, there is no possible fix on the database schema. (I spent the last year making sure of that)

My goal is to provide a specific set of fields and widgets that will allow the use of constrained Generic FKs. (I.e.: only allow relations with specific content types.) 

The general opinion on whether or not to use Generic relations is very much 50/50. People say use them if you absolutely need to, but try as much as possible to stay away from them because of the complexity they add. They are not BAD, just more trouble.

I am, for sure, thinking that supporting generic fks would benefit the project so I'll submit a PR with basic tests when done :)

**Comment by codingjoe** [comment]
Sure, I don't mind a new feature, but we currently can't develop it. Maintaining what we have is already pretty hard.
Just create a PR when you're done. Until then I'll just close the ticket.
Thanks again for your support, it's very much appreciated.
