### ISSUE TITLE
django 1.7 is_hidden change break display with django-bootstrap3

### ISSUE THREAD

**Issue by onysos** [applegrew/django-select2#155]
I found a bug in the widgets since a change in the way django 1.7 treat is_hidden in their widgets

since django 1.7, the `is_hidden` attribute is now a `@property` that compare `input_type == "hidden"`.
so the MultipleSelect2HiddenInput and  HeavySelect2Widget has since django 1.7 `is_hidden = True` instead of `is_hidden = False` befor django 1.7.

all lib that rely upon `is_hidden` will so work differently with the upgrade django 1.6 -> 1.7. 

in my experience, django-bootstrap3 won't display any label for the field that use these widgets since the upgrade. 

my fix is to replace the `@property` of django by us own that return False. 

I will fork and make a push request to fix this bug.

**Comment by codingjoe** [comment]
@onysos thanks, I've seen this bug in combination with django-crispy-forms before. I would be very cool if you could write a patch.

**Comment by onysos** [comment]
it seem that the bug is fixed in the git master branch. 
so i give you the patch for the 4.2.2 version currently on pypi

**Comment by codingjoe** [comment]
Interesting, could you maybe add a test? I don't know if this package has been fixed in master.

**Comment by onysos** [comment]
if thuth, this bug is already fixed in the master branch, since you don't override `input_test` anymore. 
this commit prevent and the tests prevent the bug to come back if you need to re-add `input_test = "hidden"` in the next release
