### ISSUE TITLE
data_view and data_url should be smarter

### ISSUE THREAD

**Issue by bubenkoff** [applegrew/django-select2#157]
ATM, there's no way to pass additional arguments to the `reverse(self.data_view)` function call in the widget's `get_options`.
Same for data_url, it can be only static one.
I propose to check if url and view are callable, if yes, call them with self live this:

```
if callable(self.view):
    self.view = self.view(self)
...
if callable(self.url):
    self.url = self.url(self)
```

this way you can declare your field/widget avoiding to override form's **init** just to set widget's url

**Comment by bubenkoff** [comment]
django_select2/widgets.py:443

**Comment by bubenkoff** [comment]
and the reason is?

**Comment by codingjoe** [comment]
@bubenkoff sorry. I closed all issues. Because we're on a completely new code base.
You're issues is valid tho.

**Comment by bubenkoff** [comment]
@codingjoe thanks

**Comment by codingjoe** [comment]
Closed: **This issue has been inactive for an extended period of time. Please reopen the issue if it is still relevant.**
