### ISSUE TITLE
404 issues with latest django select2

### ISSUE THREAD

**Issue by hrishiballal** [applegrew/django-select2#162]
When using the test app and testing the Auto tags in  /test/question/ there is a 404 error while searching
![screen shot 2015-04-08 at 10 57 16](https://cloud.githubusercontent.com/assets/1588744/7043018/188570f4-ddde-11e4-90ac-726fec19a94f.png)
![screen shot 2015-04-08 at 10 57 00](https://cloud.githubusercontent.com/assets/1588744/7043024/1d3108e8-ddde-11e4-8873-2b090eeacd00.png)

**Comment by codingjoe** [comment]
Are we talking lastest master? I've seen this bug before and wrote a fix, but it broke something different. I'll figure out a better solution.

**Comment by hrishiballal** [comment]
That is correct, this is in the latest master.

**Comment by codingjoe** [comment]
I'll find a solution.

**Comment by codingjoe** [comment]
duplicate #162

**Comment by JayTurnr** [comment]
@codingjoe Did you close this as a duplicate of itself?

**Comment by codingjoe** [comment]
Hahaha, true. Thanks for the not

**Comment by codingjoe** [comment]
@hrishiballal what is the response message you get on the 404?

**Comment by codingjoe** [comment]
Closed: **This issue has been inactive for an extended period of time. Please reopen the issue if it is still relevant.**
