### ISSUE TITLE
travis failures on python 2.6

### ISSUE THREAD

**Issue by bcail** [applegrew/django-select2#163]
I'm seeing travis failures on python 2.6. Looking in .travis.yml, I see the following:
  - pip install --upgrade pip
  - pip install -e .
  - pip install -r requirements_dev.txt
  - pip install Django$DJANGO
  - pip install coveralls

Would it be good to install the django we want first, before running "pip install -e ."? Right now it looks like it's pulling in django 1.8, which doesn't run on python 2.6. Not sure if this will fix the travis failures, but it might be a good idea anyway?

**Comment by codingjoe** [comment]
I've seen that. I'm still at work, and cant fix that right now, but if you do a PR i'll merge.

**Comment by codingjoe** [comment]
fixed
