### ISSUE TITLE
No support for placeholder translation

### ISSUE THREAD

**Issue by emorozov** [applegrew/django-select2#164]
Hello,
django_select2 breaks when the widget placeholder is initialized using Django `ugettext_lazy` function, like this:

    select2_options={'placeholder': _(u'Add category...')}

This results in `TypeError`:

    <django.utils.functional.__proxy__ object at 0x7fc2280c9b10> is not JSON serializable

**Comment by codingjoe** [comment]
Hi @emorozov, have you tried `ugettext` instead of it's lazy version?

**Comment by emorozov** [comment]
@codingjoe I know that this will work. But usually widget options are set in form definition which is executed when module is loaded, so using `ugettext` is pointless here.

**Comment by codingjoe** [comment]
And your point is? It should work, but it doesn't, yet there is a perfectly fine solution to it?
I don't mind having this fixed but you'd need to provide a pull request.

**Comment by emorozov** [comment]
@codingjoe It's not a perfectly fine solution because if you use `ugettext`, placeholder will be translated only once: when you start the application and all modules are loaded by Django.

`ugettext_lazy` is used because translation should happen on every page render, to display placeholder in user's locale. Application can be accessed by users preferring different languages: Russian, Spanish, French, etc. Every user needs to see placeholder translated to their own language.

When `ugettext` is used on module level, placeholder will be translated only once. When `ugettext_lazy` is used, translation will be different for every user.

It's the same with Django models: help text and other properties are translated using `ugettext_lazy` exactly for this reason.

Sorry, if my explanation is difficult to understand. I don't have much time now, but maybe in a week or two I can try to fix this issue and submit the pull request.

**Comment by VerosK** [comment]
There is simple workaround how to handle placeholder translation. In `MyForm.__init__`, you can do

```python
self.fields['add_people'].widget.options['placeholder'] = ugettext("Select user here")
```

which is not-so-elegant-but-working-solution.

**Comment by codingjoe** [comment]
@emorozov I don't think this is a select2 problem, but rather a django one. Thus I'll close the thicket. But feel free to submit a pull-request.
For the record @VerosK your's is a very valid and good solution.

**Comment by emorozov** [comment]
@codingjoe Yes, I've used the same workaround myself for all this months, but it's pretty ugly in my opinion.

I've finally decided to fix the bug properly and created a pull request.
