### ISSUE TITLE
Add limit choices to support using QSerializer

### ISSUE THREAD

**Issue by codingjoe** [applegrew/django-select2#165]
It would be cool if you could limit the choices for each field in the widget definition. This could be accived using https://djangosnippets.org/snippets/3003/

**Comment by xxinfinityxx** [comment]
Could you provide more details of the actual use cases? I could find a use for this in my project and implement it.

**Comment by codingjoe** [comment]
@xxinfinityxx currently It's only possible to define a field with a certain queryset on class level. Mostly due to multiprocessing as instances are not shared across multiple machines. That makes you end up with a lot of code, tho you might only wan t to change the queryset for instance.
That why it might be a better idea to fully serialise a field instance for it to be shared across machines using django's cache backend or a DB.

**Comment by codingjoe** [comment]
A use case would be, to dynamically filter a queryset based on user parameters. As far as I'm concerned, that is currently not possible.

**Comment by xxinfinityxx** [comment]
I usually do this like that:

In forms.py:
```python
class FiberStrandChoices(AutoModelSelect2Field):
    """
    Special version of AutoModelSelect2Field to allow dynamic queryset.
    """
    search_fields = [
        'bufferedfiberstrand__fiber_cable_section__cable__identifier__icontains',
        'bufferedfiberstrand__number',
        'ribbonfiberstrand__fiber_cable_section__cable__identifier__icontains',
        'ribbonfiberstrand__number',
        'cablefiberstrand__fiber_cable_section__cable__identifier__icontains',
        'cablefiberstrand__number',
        'notes__icontains'
    ]
    max_results = 10

    def __init__(self, *args, **kwargs):
        self.queryset = kwargs.get('queryset', None)
        super(FiberStrandChoices, self).__init__(*args, **kwargs)
```

In the view:
```python
form.fields['a'] = FiberStrandChoices(queryset=fiber_strands_qs)
```

The class UnhideableQuerysetType has some "pretty nasty hacky stuff" (quote from the class documentation) that makes the magic happen...

**Comment by codingjoe** [comment]
@xxinfinityxx does this work across multiple machines? I doubt it, how would the other machine know about the queryset you passed?

**Comment by xxinfinityxx** [comment]
Then I must have misunderstood your use case @codingjoe .

The way I use this code is to instantiate the form dynamically depending on the query the user made to access that form. I.e.: to filter down some available choices. Other machines are not supposed to be affected in my use case.

**Comment by codingjoe** [comment]
AutoModelSelect2Field is heavy and does ajax requests to the select2 json view.
The AJAX request could be handles by any other machine. I just ran into the very same problem with an app of mine. That's why I'm thinking about a way to share the field instant state across machines.
