### ISSUE TITLE
Django 1.8 TypeError: Error when calling the metaclass bases

### ISSUE THREAD

**Issue by garcianavalon** [applegrew/django-select2#166]
When I try to start my django server I get a crash:
>...
>django_select2/fields.py", line 301, in __new__
>    return type.__new__(cls, name, bases, dct)
>TypeError: Error when calling the metaclass bases
>    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

I think its related to #153 and #160. The fixed uploaded in #160 is not in the actual version from pip.
```
$pip freeze
Django==1.8
Django-Select2==4.2.2
```
Let me know if I can help fix it somehow or if I'm missing something out ;)
Thanks, cheers.

**Comment by codingjoe** [comment]
Nope, that's right. It's not yet on pypi. I don't feel like releasing this just now, there is still much that needs fixing and more important test coverage.
Just install from github, but may I remind you that it might not be stable.

**Comment by garcianavalon** [comment]
Cool thanks. I will follow the GitHub route as I'm only prototyping and its fine.
Thanks again for the quick answer.
