### ISSUE TITLE
Release a 4.2.3 with Django 1.7 support

### ISSUE THREAD

**Issue by bdauvergne** [applegrew/django-select2#169]
Hi, do you think could release master as a 4.2.3 release ? We are using Django 1.7 and we have the problem that multiple choide field does not have a label anymore (problem fixed in master).

Thank you for django-select2 it's a great library.

**Comment by codingjoe** [comment]
@bdauvergne as you are the 3rd person to ask:
I don't feel all to comfortable about releasing the current master, as a lot of behavior is sill untested.
BUT, the master is more stable than the current release.
Taking this into consideration: @applegrew feel free to release, I'd go for 4.3.0 considering the new support for python3 and django 1.8

**Comment by bdauvergne** [comment]
The best way to have people debug the current master is to release it with the bugs ! :)

**Comment by codingjoe** [comment]
@bdauvergne say what? One should always aim for a stable release, no matter what. That why we have automated testing. How do you upgrade 3rd party code than? I need to rely on packages being tested.
BTW, the community is rather large for a django package.

**Comment by applegrew** [comment]
Version 4.3.0 pushed to pypi. Let me know if you see any issues with latest version.

**Comment by bdauvergne** [comment]
Great, big thank you, I can remove the ugly dependency_links from my package ! :)
