### ISSUE TITLE
Memcached and unicode

### ISSUE THREAD

**Issue by TheDeadOne** [applegrew/django-select2#178]
With SELECT2_MEMCACHE_HOST enabled I get error "memcache.MemcachedStringEncodingError: Keys must be str()'s, not unicode.  Convert your unicode strings using mystring.encode(charset)!"

**Comment by codingjoe** [comment]
@TheDeadOne I think that bug was introduced with python3 support. Do you feel comfortable enough to write a fix?

**Comment by codingjoe** [comment]
@TheDeadOne you can check out the cache branch. Which is the version 5 draft. I resolved the caching issue there. But I must remind you this is still experimental.
