### ISSUE TITLE
JSFunctionInContext doesn't exist anymore

### ISSUE THREAD

**Issue by joaolsilva** [applegrew/django-select2#183]
Previously in a ModelForm we could interface with javacript via django_select2.util.JSFunctionInContext

    foo = FooChoices(widget=AutoHeavySelect2Widget(select2_options={"ajax":
        {
            'width': '220px',
            'dataType': 'json',
            'quietMillis': 100,
            'data': JSFunctionInContext('my_url_param_generator'),
            'results': JSFunctionInContext('django_select2.process_results')
        }}))

In this case the my_url_param_generator is a javascript function that is used to filter the possible results. What is the current way of achieving this?

**Comment by joaolsilva** [comment]
Or, more succinctly, since JSFunctionInContext doesn't exist anymore how to solve the same problem as https://github.com/applegrew/django-select2/issues/22?

**Comment by applegrew** [comment]
This was deleted by SHA-36bac0570f6e1c16d27980f8b06ea8e91b9cefd2. I don't remember why it was done. Not sure if this was a good commit. Will need recheck that. Sorry can't provide a workaround now.

**Comment by magicjohnson** [comment]
here is a workaround
```python
{
   ...
   'data': '*START*django_select2.runInContextHelper(django_select2.get_url_params, selector)*END*',
   'results': '*START*django_select2.runInContextHelper(django_select2.process_results, selector)*END*',
}
```

**Comment by LyleScott** [comment]
Here is how I accomplished it:

Custom field:
```python
class Endpoints(AutoModelSelect2TagField):
    queryset = ProjectEndpoint.objects
    search_fields = ['title__icontains']

    def get_model_field_values(self, value):
        return {'title': value}

    def prepare_qs_params(self, request, search_term, search_fields):
        res = super(Endpoints, self).prepare_qs_params(request, search_term, search_fields)
        res['and'] = {'id': request.GET.get('id')}
        return res
```

(Model)Form field:
```python
    endpoints = Endpoints(widget=AutoHeavySelect2TagWidget(select2_options={
        'minimumInputLength': 1,
        'ajax': {
            'dataType': 'json',
            'quietMillis': 100,
            'data': '*START*django_select2.runInContextHelper(s2_endpoints_param_gen, selector)*END*',
            'results': '*START*django_select2.runInContextHelper(django_select2.process_results, selector)*END*',
        }
    }))
```

Javascript on page:
```javascript
            var s2_endpoints_param_gen = function(term, page) {
                    var proxFunc = $.proxy(django_select2.get_url_params, this);
                    // no need for a custom func here.
                    var results = proxFunc(term, page, 'django_select2.process_results');
                    results.id = $('#project_id').val()
                    return results;
            };
```
