### ISSUE TITLE
CSS files not available intermittently

### ISSUE THREAD

**Issue by chriswedgwood** [applegrew/django-select2#189]
I have raised this issue: 

https://github.com/divio/djangocms-link/issues/55

The consensus seems to be that the issue lies with django-select2. Ive tried to debug and see where the issue is but am struggling to do so 

Perhaps someone else with more pythin knowledge could re-create and see where the issue lies?

**Comment by codingjoe** [comment]
@chriswedgwood I know that we jus trecently changed the way the widget media attribute works b576bcdd9e76441cc27282c2ecd3978f4854b5a1
I don't see an issue with that tho. Let me know if you find any cause for this unexpected behavior

**Comment by chriswedgwood** [comment]
@codingjoe Thanks yes ive tried the latest code and it all works. No issue

**Comment by codingjoe** [comment]
Great!
