### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by gavinwahl** [applegrew/django-select2#190]
I am trying to debug some issues and it is very difficult because none of the releases are marked with a git tag. It would be helpful to tag every release.

**Comment by codingjoe** [comment]
true. we could even deploy releases on pypi with Travis.

**Comment by codingjoe** [comment]
For now I can only promise you that we're working on a more stable and tested version. Once it's released there should be no need for too much debugging.

**Comment by codingjoe** [comment]
I added tags for the new releases. If you need older once let me know.
