### ISSUE TITLE
Capitalisation differences results in new Tags

### ISSUE THREAD

**Issue by diegomatar** [applegrew/django-select2#192]
When a user type Tags in a "AutoModelSelect2TagField", the autocomplete is case insensitive (uses ['tag__icontains', ] ). But if the user ignores autocomplete's suggestions and submit a value with different capitalisation, a new object (Tag) is created.

How can I manipulate the "value" inputed by the user, to make it a title (something like .title() in Python), before it is processed, so capitalisation differences won't result in new Tags?

I guess it should be done in 'heavy_data.js', but due to my limited skills, I could not made it...

**Comment by codingjoe** [comment]
You could also do that during object saving on model level. That's how I do it. I save everything in lower and do the formatting to title where ever I need it in the front end.

**Comment by diegomatar** [comment]
Thanks!

**Comment by diegomatar** [comment]
Sorry, I realise I did not understand what you mean:

Even when I overwrite the Model save method, *django-select2* creates a new Tag object, if a different capitalisation is inputed:

    class Tag(models.Model):
        name = models.CharField(max_length=70, unique=True)
        slug = models.SlugField(unique=True)

        def save(self, *args, **kwargs):
           self.name = self.name.lower()
           super(Tag, self).save(*args, **kwargs)

If I input ***Test Tag 1*** and ***test tag 1***, it raises the error: *UNIQUE constraint failed: tag.slug*  , as the first inputed Tag will already grab that slug.

I guess that the solution would be if the "AutoModelSelect2TagField" did not accept the *Test Tag 1* if *test tag 1* was already inputed, or vice versa. Does it make sense?

**Comment by codingjoe** [comment]
You should make the name unique as well. Then you'll need to capture the integrity error in the save method and load the right class from db to replace the currents instance PK.

**Comment by diegomatar** [comment]
Worked! Thank you very much:

    def save(self, *args, **kwargs):
            self.nome = self.nome.lower()
        
            try: #create a new Tag object
                super(Tag, self).save(*args, **kwargs)
        
            except IntegrityError: # in case of errors, replace instance by the existing one
                existing_tag = Tag.objects.get(slug=self.slug)
                self.pk = existing_tag.pk
                # Now pk != 0 , so object is updated:
                self.save()

**Comment by codingjoe** [comment]
:+1:
