### ISSUE TITLE
Using space to add separate "tags" causes IntegrityError

### ISSUE THREAD

**Issue by daddz** [applegrew/django-select2#193]
Steps to reproduce:
1. Have a AutoModelSelect2TagField on your form
2. Add tag "foo" to some model
3. Try adding "foo" to another model but use the "space" key (instead of enter/tab) to add the tag
4. See IntegrityError

Seems like the JS does something else when hitting space instead of enter/tab!?

**Comment by daddz** [comment]
Django==1.8.3
Django-Select2==4.3.1

**Comment by codingjoe** [comment]
seems related to #192

**Comment by codingjoe** [comment]
No longer in scope of package.
