### ISSUE TITLE
How can I use extra data in js for custom rendering?

### ISSUE THREAD

**Issue by ramganez** [applegrew/django-select2#194]
I'm going to try  search functionality using django_select2.
I'm using AutoModelSelect2Field.

Its doing search and list out the choices, Make a link for that choice, user ones click the choice its redirect to particular url. 
I'm Overriding the extra_data_from_instance method its return the url.
 Is it correct? What am I doing wrong here??

**Comment by codingjoe** [comment]
Hi Ramganez, django-select2 isn't really made for search with autocomplete. You can use select2 of course, but you should really write your own JSON response view.
BTW, I mostly use django-watson and twitter's typeahead.js to build a search.
