### ISSUE TITLE
Can't display in the admin site

### ISSUE THREAD

**Issue by albus12138** [applegrew/django-select2#198]
As the title, when i try to use this in my admin site, it just display as a Charfield.Even in the testapp of the package.How can I use this module in admin site?

**Comment by codingjoe** [comment]
That is correct. That bug was introduced when the media was changed.

**Comment by albus12138** [comment]
Can you tell me what I should add to admin templates, such as .js, .css or anything else.

**Comment by albus12138** [comment]
I have added all staticfiles in "form.html" to "admin/change_form.html"(no 404), but it is no use.What's wrong?

**Comment by albus12138** [comment]
https://github.com/applegrew/django-select2/pull/179
Or like this?
