### ISSUE TITLE
Possibly outdated select2-bootstrap-css?

### ISSUE THREAD

**Issue by stringsonfire** [applegrew/django-select2#199]
In the documentation for [`SELECT2_BOOTSTRAP [Default False]`](http://django-select2.readthedocs.org/en/latest/get_started.html#select2-bootstrap-default-false), there is a link to [fk/select2-bootstrap-css](https://github.com/fk/select2-bootstrap-css), but the author has stated this has been merged back into the original repository, under the [bootstrap 3 branch here](https://github.com/t0m/select2-bootstrap-css/tree/bootstrap3). What's currently being used in `django-selects2`?

**Comment by codingjoe** [comment]
Removed in v5.
