### ISSUE TITLE
AutoModelSelect2TagField - New entries have same misleading CSS as existing entries

### ISSUE THREAD

**Issue by theashishranjan** [applegrew/django-select2#200]
Just a wild suggestion, you might choose to ignore

I will try to explain with an example:

Let's say I have 'cat', 'dog', 'mouse' and if I start typing 'cat', it shows 'ca' in blue border giving an impression that 'ca' also exists in my DB, ideally it should not show 'ca' in dropdown or if it does then it should be like 'Add ca' with other suggestions following it below in the dropdown. I mean to say that if the user is typing something, what he types should not be part of auto suggest dropdown.

**Comment by codingjoe** [comment]
@theashishranjan I guess this is no longer within the package scope.
