### ISSUE TITLE
widgets not staying in cache

### ISSUE THREAD

**Issue by alandmoore** [applegrew/django-select2#204]
I'm trying to use the latest django_select2 (v.5.0.3) with django 1.8.4 and python 3.4 on Debian Jessie.

For some reason, my widgets are being deleted from the cache almost immediately after being created, so when I go to do a search I get "field_id not found" from auto.json.

My field subclasses `ModelSelect2Widget`.  I have tried with both memcached and the locmem caching backends.

Running with `pdb`, I put a breakpoint at django_select2/forms.py:202 and found that (according to memcached logs) the widget instance is not being stored.  Memcached output looks like this:

    Sep 30 14:58:42 magdev systemd-memcached-wrapper[30517]: <31 delete :1:select2_140400431077080
    Sep 30 14:58:42 magdev systemd-memcached-wrapper[30517]: >31 NOT_FOUND

The problem seems to be with storing `self`, i can store other python objects using the same key, just not `self`.

**Comment by codingjoe** [comment]
Hi @alandmoore,
I've seen some pickling issues in the latest version but never that objects have been removed from the cache.

Lets assume you're code doesn't swallow any exceptions. Therefore the objects is being set to the cache. The dj-select2 code doesn't delete it in the current version. Therefore I must presume that your code most do it.
Maybe you have a `cache.clear()` in your code, that's been called?

Also you should make sure that you're actually using memcached or redis, NOT locmemcached. The later clears on each server restart.

**Comment by alandmoore** [comment]
So to clarify:

- I am using memcached, I can see it logging the transactions realtime.
- I wasn't using any kind of cache before setting it up for dj-select2, so my own code isn't calling `cache.clear()` (or any other cache methods) anywhere.  It's possible a 3rd-party library is doing this, I'll have to scan the codebase for cache calls.

It appears that storing the `ModelSelect2Widget` instance is just failing, if I step through with `pdb` and try to cache to object, it's immediately deleted from the cache (in fact, in never logs being stored, see the output in the original post) without any other code being run.

My only thought was maybe the instance was too big to store, but `sys.getsizeof()` says it's only 56 bytes.  I am able to store much larger objects.

**Comment by codingjoe** [comment]
Ok interesting. I changed the way we pickle the widget in v5.1.0. Do you still have this issue?

**Comment by codingjoe** [comment]
Hi @alandmoore I experienced this issue myself using the local cache backend. I just migrated my first big production system (using Redis). I'll keep my eye open for this issue. So far I haven't seen any logs proving a greater issue.

**Comment by alandmoore** [comment]
When I get a chance to try it, I'll see if 5.1.0 works.  I refactored my code to use a `HeavySelect2Widget` and wrote a view to get around the use of the cache.  My app will only be used by a handful of people so I don't normally use a cache.

**Comment by codingjoe** [comment]
As I didn't hear back, I presume the issue is resolved. I use it in production and didn't stumble upon it using different cache backends.
