### ISSUE TITLE
How to use placeholder or other attributes ?

### ISSUE THREAD

**Issue by sebastien247** [applegrew/django-select2#212]
How to use placehoder and other attributes on my field ?
This exemple doesn't work for me : 
```
class FiltersForm(forms.Form):
    category = forms.ChoiceField(
        widget=Select2Widget(attrs={'placeholder': 'Catégorie'}),
        choices=modelData(Category),
        required=False,
        label=False
    )
```

**Comment by codingjoe** [comment]
@sebastien247 you're almost there. Check out the new data-attributes for select2 version 4.
In your case it's `attrs={'data-placeholder': 'Catégorie'})`. If you have CamelCase options you have to split them with a dash. Like `mySelect2Option` becomes `data-my-select2-option`.
