### ISSUE TITLE
"Add another" buttons

### ISSUE THREAD

**Issue by jonashaag** [applegrew/django-select2#215]
This is not a bug report; I'm here to inform anyone interested about a new small Django application I have created: https://github.com/jonashaag/django-addanother

It has some very light integration with django-select2. If the maintainers of django-select2 like it we could add a reference to the django-select2 documentation.

**Comment by codingjoe** [comment]
:+1:

**Comment by codingjoe** [comment]
@jonashaag we now provide a jQuery plugin. That makes dynamic field adding a breeze.

**Comment by jonashaag** [comment]
Not exactly sure what you are referring to here? Does this help with the "add another" buttons somehow?

**Comment by codingjoe** [comment]
Yes. http://django-select2.readthedocs.org/en/latest/django_select2.html#javascript

**Comment by jonashaag** [comment]
Either I don't get it or you haven't really looked at my implementation. Popups are used to show the "inline" add another form; there's no dynamic loading of any kind.

**Comment by codingjoe** [comment]
Nope, there is not, it's just a helper to implement it.
