### ISSUE TITLE
AutoModelSelect2MultipleField is not defined

### ISSUE THREAD

**Issue by workino** [applegrew/django-select2#216]
Hello,
i'm migrating from 1.7 to 1.8.5 but i got this error and i can't figure out to solve.

name 'AutoModelSelect2MultipleField' is not defined

Thank you

**Comment by codingjoe** [comment]
Did you also upgrade to version 5 of this package? If so, the field is gone. They all are. 
https://github.com/applegrew/django-select2#upgrade-from-version-4
