### ISSUE TITLE
Does django-select2 support dependent dropdowns?

### ISSUE THREAD

**Issue by tisOO** [applegrew/django-select2#217]
For example, I have a form with fields `Continent, Country, State, City, University`.
`Country` depends on `continent`, `state` depends on `city` and etc.
When I select country, for example, USA, and start typing in the input box city's name, request must be:
`q=New&country_id=1`

Does some widget support this behavior? If it doesn't support, will it be supported in next versions?

**Comment by codingjoe** [comment]
Hi @tisOO,
no none of the widgets supports this feature, but you could add it yourself. You'd need to do some javascript hackery. Too much to be included as a feature here. Check out how we pass data to the endpoint https://github.com/applegrew/django-select2/blob/master/django_select2/static/django_select2/django_select2.js#L7-L12

You can simply create your own endpoint that expects another argument to build a queryset.

**Comment by tisOO** [comment]
Thank you!
