### ISSUE TITLE
Add custom label support

### ISSUE THREAD

**Issue by codingjoe** [applegrew/django-select2#218]
Based on #208, waiting for supporters

**Comment by stelzzz** [comment]
Hello! When you plan to add this feature?

**Comment by codingjoe** [comment]
When someone needs it and writes a solid implementation. I for one don't need it.
Should a lot of people request it I might reconsider investing some time.

**Comment by palm86** [comment]
This would be very useful to me. It is somewhat silly to allow searching on multiple fields, without the user seeing why the search matches a particular value. Say I search on name_en and name_af, but only name_en is displayed to the user.

What is the status of mostafa-anm's efforts?

**Comment by codingjoe** [comment]
@mostafa-anm what's the status of #233? I left you a comment. We need this feature to If I'm not mistaken.

**Comment by codingjoe** [comment]
Released in 5.6.0

@palm86

**Comment by palm86** [comment]
Great! Thanks @codingjoe
