### ISSUE TITLE
jQuery version 2

### ISSUE THREAD

**Issue by jrief** [applegrew/django-select2#219]
In section **External dependencies**, you write that jQuery version 2 is required, but on https://github.com/select2/select2/releases its written that for Select2 4.0.0 the supported environments requires jQuery 1.7.2+.
Is this a documentation bug?

**Comment by codingjoe** [comment]
No it's not.
> You can also define nested configurations, which are typically needed for options such as AJAX. Each level of nesting should be separated by two dashes (--) instead of one. Due to a jQuery bug, nested options using data-* attributes do not work in jQuery 1.x.

We use nested options like `data-ajax-url`.

You can try it under 1.x, but officially we don't support it.
