### ISSUE TITLE
Add extra parameters to Select2View dinamically when calling it from ajax

### ISSUE THREAD

**Issue by nabucosound** [applegrew/django-select2#22]
I have a case where I would like a second select to get the results through ajax (HeavySelect2Widget). I want the view to also receive an ID and consequently construct the queryset according. It is the classic "select the country", and then the second select searches on cities from the selected country.

Is there an easy way to do this? I guess the way to accomplish this is adding another GET param (along with the 'term' or 'page') while calling auto.json (or a custom Select2View) but I didn't find an easy solution... Or maybe I am missing something?

Thanks!

H.

**Comment by magicjohnson** [comment]
it's working, but you need to set JS function in different way: https://github.com/applegrew/django-select2/issues/183#issuecomment-125903553
