### ISSUE TITLE
django_select2.js is not loaded correctly when using a CDN in production

### ISSUE THREAD

**Issue by mlorant** [applegrew/django-select2#221]
Hi,

I am using Amazon S3 to serve my static files in production. Since the upgrade to version 5, the file django_select2.js is not served correctly. Indeed, Django tries to fetch `mywebsite.com/static/django_select2/django_select2.js` instead of the Amazon S3 file.

I hotfixed this by editing Select2Mixin: 

```
# Add the import
from django.contrib.staticfiles.templatetags.staticfiles import static

# Note the static call on the second JS file
return forms.Media(
     js=('//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js',
          static('django_select2/django_select2.js')),
     css={'screen': ('//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css',)}
)
```

It works fine in local and with local static serving though. I did not try my patch on other environments, so I don't know if this have consequences on other uses.

**Comment by codingjoe** [comment]
hm.... that's because of the static thing. That is actually wrong. We should fix it.

**Comment by codingjoe** [comment]
Sorry. I misread you ticket.
The static widget media is defined as it should be. I must presume that the error is in your configuration. Please double check with https://docs.djangoproject.com/en/1.8/topics/forms/media/#paths-in-asset-definitions

**Comment by mlorant** [comment]
Mmmh, ok. Seems weird though, since it can needs more than "be prepended with the value of the appropriate prefix". 

In my case, the static URL is `https://<myAppID>.cloudfront.net/django_select2/django_select2.<hash>.js` (where myAppID and hash are placeholder for unique string here of course.), hence the need of the `static`function call.  Django media forms does not seem to support that but I guess my problem is *more framework-related* and does not concerned this lib in particular :)

**Comment by codingjoe** [comment]
Seems so. Curious tho, please approach Tim code.djangoproject.org. I'd really like to clarify this issue.
Please post the ticket number here to allow other to read up on this issue.

**Comment by mlorant** [comment]
I found a ticket specifying the same problem, created two years ago (but updated recently): https://code.djangoproject.com/ticket/21221 Last comment's author uses the same trick to bypass the problem...

**Comment by codingjoe** [comment]
@mlorant I commented on the issue. Let's see where it goes. Should there be an action form my side required, I will do so during django under the hood.

**Comment by codingjoe** [comment]
@mlorant I wrote a patch for django https://github.com/django/django/pull/5571#discussion_r44535304
You'll have to wait until version 1.10 tho. I'd advice you overwrite media in your own code, including a note to remove you hack when upgrading to 1.10.

Cheers, Joe

**Comment by mlorant** [comment]
@codingjoe I subscribed to the PR, so I followed activity about it. I also did a fork of the plugin, which includes the `static` call (see commit reference above). I will try to keep it up to date with your project, so everyone can use it if they have the same problem :)
