### ISSUE TITLE
debugging issue

### ISSUE THREAD

**Issue by dbinetti** [applegrew/django-select2#223]
sorry for the 'support-request-as-bug-report', but I have followed instructions to the letter and can't get the new select widget to work.  how best to debug?

**Comment by codingjoe** [comment]
Hi @dbinetti ,
do you have some code to share?

Cheers,
Joe

**Comment by dbinetti** [comment]
Joe, thanks for the response.  I'm digging in a bit more so that I can ask a reasonable question (with code.)  I'll close this until I have something worth sharing.  Thanks
