### ISSUE TITLE
Puting more select fields on same form

### ISSUE THREAD

**Issue by PredragPeranovic** [applegrew/django-select2#225]
I tried to put more than one ModelSelect2Widget on same form similar to the example: 

```python
class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('__all__')
        widgets = {
            'author': ModelSelect2Widget(model=Author, search_fields=['first_name__icontains']),
            'publisher': ModelSelect2Widget(model=Publisher, search_fields=['name__icontains'])
        }
```

But the second select2 was initialised with ajax configuration defined for the first select. In my case publisher select displayed data about authors. 

I rewrite function in  django_select.js to initialize both select2 fields correctly (not in most elegant way).
from
```javascript
   $(function () {
        $('.django-select2').djangoSelect2();
    });
```
to 

```javascript
  $(function () {
        var selects = $('.django-select2');
        if (selects.size() == 1) {
            selects.djangoSelect2();
        } else {
            for (i in selects) {
                $('#'+selects[i].id).djangoSelect2();
            }
        }
    });
```
Maybe this was my wrong doing but please check if this is a bug.

All best

**Comment by codingjoe** [comment]
This is a bug and was introduced by @anneFly in version 5.3.0 please freeze to a lower version for now.
It will be fixed in #224
