### ISSUE TITLE
Support tag widget in ArrayFields

### ISSUE THREAD

**Issue by yuvadm** [applegrew/django-select2#226]
It seems this library is well-positioned to support the [plain select2 tag widget](https://select2.github.io/examples.html#tags) for Postgres specific [`ArrayField`](https://docs.djangoproject.com/en/1.8/ref/contrib/postgres/fields/#arrayfield). Suppose the model looks like so:

```python
from django.contrib.postgres.fields import ArrayField

class Book(models.Model):
    name = models.CharField()
    tags = ArrayField(models.CharField(max_length=30), blank=True, null=True)
```

The default admin behavior renders the `ArrayField` as a plain text field which has to be filled with comma separated data, such as: `tag1,tag2,tag3`. Since this isn't a M2M field, no lookup is required and the widget is used just for style and better UX.

Is it possible to implement this in the library? Alternatively, I'd be happy to get some directions on how to build this widget myself from the various mixins.

**Comment by codingjoe** [comment]
Hi @yuvadm,
as I it there is no additionally work required to make the array field work.

All you got to do is use the `value_from_datadict` method of the tagfield.

```python
class MyModelSelect2TagWidget(HeavySelect2TagWidget):
    queryset = MyModel.objects.all()

    def value_from_datadict(self, data, files, name):
        values = super().value_from_datadict(self, data, files, name)
        return ", ".join(values)
```

Is there a point in our documentation, where we could be more specific on how to implement that?

Also there might be an issue, that there is not "light" tag field. As I understood you, you are not interested providing autocompletion.

**Comment by yuvadm** [comment]
In that case, why do I need to use a `queryset` if indeed I'm not concerned about autocomplete?

**Comment by codingjoe** [comment]
I guess it's a bit of both. There should be a light tag widget and it's documentation could be based on your use case.

**Comment by yuvadm** [comment]
Is there any way I can workaround the autocomplete/queryset limitation for now?

**Comment by codingjoe** [comment]
I'm gonna fix it now, if you have an hour ;)

**Comment by yuvadm** [comment]
Awesome! :smile: Let me know if there's anything I can help test.

**Comment by codingjoe** [comment]
Released in 5.4.0

**Comment by yuvadm** [comment]
@codingjoe thanks for the quick fix and release, kudos!

**Comment by yuvadm** [comment]
@codingjoe is using `formfield_overrides` not an acceptable usage? Do I have to create a proper `Form`? e.g.

```python
class MyWidget(Select2TagWidget):
    def value_from_datadict(self, data, files, name):
        values = super().value_from_datadict(data, files, name)
        return ','.join(values)

class MyAdmin(admin.ModelAdmin):
    formfield_overrides = {
        ArrayField: {
            'widget': MyWidget
        },
    }
```

**Comment by yuvadm** [comment]
Ignore, I think this is a missing jQuery problem.

**Comment by codingjoe** [comment]
ok ;)

**Comment by yuvadm** [comment]
This still isn't a drop-in replacement. I'm working on the details and will probably open a PR with some documentation updates.

In the meantime, any advice on what's the best/right way to preload the field with the existing data? I'm trying to render the data with `render_options` but no dice:

```python
def render_options(self, choices, selected_choices):
        OPTION_SELECTED = '<option selected="selected">{}</option>'
        options = ['abc', 'dev']  # later on i'll just take this from the existing field data
        return '\n'.join([OPTION_SELECTED.format(opt, opt) for opt in options])
```

Should I try some other method?

**Comment by codingjoe** [comment]
In the "light" versions all options a rendered as usual. That should work out the box. There has been some problem regarding option rendering with heavy fields tho but that shouldn't effect you right?
Just set the initial on the form, that should do the job.

**Comment by yuvadm** [comment]
Hmm, it's not working out of the box. I can type new stuff in, it gets saved properly, but if I refresh the model form I get a blank input field.

**Comment by codingjoe** [comment]
Ok, you need to be more specific, what do you mean by refresh. Are we talking about an update view? Is the initial data not being displayed? Or is that the browser that can't keep the form state?

**Comment by yuvadm** [comment]
Refresh as in save the object => you're back in list view => click on same record => field is now blank (but is saved properly on DB)

**Comment by codingjoe** [comment]
Hm... could you provide a quick example that I could test?

**Comment by yuvadm** [comment]
Here's the code I have right now:

https://github.com/daat-hamakom/maps/blob/select2/daat/maps/admin.py#L51-L79

https://github.com/daat-hamakom/maps/blob/select2/daat/maps/models.py#L108-L109

Later today I'll have some time and can prepare a minimal codebase for you to test if that helps.

**Comment by codingjoe** [comment]
That would be great, as the repository is private as it seems.

**Comment by yuvadm** [comment]
@codingjoe it's not private, just been renamed. updated the links

**Comment by codingjoe** [comment]
Ok, so all that seems to be related to #222
