### ISSUE TITLE
integration with django-taggit

### ISSUE THREAD

**Issue by witchnick** [applegrew/django-select2#228]
Hello, 
I'm trying to use AutoModelSelect2TagField for tags working with django-taggit. 
Filling the form and saving works fine, but I cannot edit the tags. 
I should have tags shown in input id_tags, but there is nothing.
There is only hidden field with IDs of selected tags show after rendering the JS code. 
 
My code:
```
class MatTagsChoices(AutoModelSelect2TagField):    
    widget = SetTagWidget    
    queryset = Tag.objects
    search_fields = ['name__icontains']

    def security_check(self, request, *args, **kwargs):        
        return True    

    def create_new_value(self, value):
       tag = Tag()
       tag.name = value[:100]
       tag.save()
       return tag.id

class MaterialForm(models.ModelForm):
    tags = MatTagsChoices(label=_(u'Tags'))
    class Meta:
        model = Material
        fields = ['tags']
```
Is this behaviour a bug? or I have missed something? 
I thought It will do the job out of the box. 

I'll appreciate any help.

**Comment by codingjoe** [comment]
Hi @witchnick yes, it's the same bug as described in #222
