### ISSUE TITLE
How to allow integers as tags when using a Select2TagWidget?

### ISSUE THREAD

**Issue by xelhark** [applegrew/django-select2#230]
When I get the array of elements in the widget, in the function `value_from_datadict` I get a list of elements and must return a list of primary keys from my model.

If the user wants to add a new element they can do it, and in my function I will have the name of the element the user is trying to add after the list of ids of elements that were there already:

```
['foo'] -> ['1'] 

['1', 'bar'] -> ['1', '2']
```

Is it possible to tell if the element is a primary key or a new key that the user is trying to add?

Example:

```
['foo', 'bar'] -> ['1', '2']
```

If the user saves again, you will get 

```
['1', '2'] 
```

Since they are the PK of the elements 'foo' and 'bar' respectively.

But what if the user wants to add a key '1' or deletes 'foo' and replaces it with '1'?

This might sound silly, but I can see use cases of users trying to add an year (1965, 2005) which may very well be an id itself. So how can you tell the difference?

**Comment by codingjoe** [comment]
Good point. I guess, you can only check if the integer is in the queryset.
```python
existing_pks = queryset.filter(pk__in=values).list_values('pk', flat=True)
new_pks = set(values) - set(existing_pks)
```

**Comment by xelhark** [comment]
Hey I just finished some testing and other stuff. I think you should upgrade the code in the docs (there are also a couple of syntax errors) with this one:

    def value_from_datadict(self, data, files, name):
        values = super(KeywordWidget, self).value_from_datadict(data, files, name)
        qs = self.queryset.filter(**{'pk__in': [l for l in values if is_int(l)]})
        names = [k.name for k in self.queryset.filter(**{'name__in': values})]
        pks = set(force_text(getattr(o, 'pk')) for o in qs)
        cleaned_values = []
        for val in values:
            if force_text(val) not in pks and force_text(val) not in names:
                val = self.queryset.create(name=val).pk
            cleaned_values.append(val)
        return cleaned_values

I added the `names` thing because sometimes when submitting data the method would be called twice with the same parameters, causing the method itself to create duplicate elements.

Obviously, in my code my model is the following (if needed)

    class Keyword(models.Model):
        name = models.CharField(max_length=50)

        def __str__(self):
            return self.name

**Comment by codingjoe** [comment]
Closed: **This issue has been inactive for an extended period of time. Please reopen the issue if it is still relevant.**
