### ISSUE TITLE
`if not queryset` causes fetching the entire queryset data

### ISSUE THREAD

**Issue by magicjohnson** [applegrew/django-select2#231]
Hi,
I have a choice field with `City.objects.all()` as a queryset.

When I'm trying to filter by calling `auto.json` server gets stuck and then crashes with segmentation fault. My virtual machine has not enough memory to store the entire set of cities as a list (~500k objects).

The root cause is https://github.com/applegrew/django-select2/blob/5.4.0/django_select2/forms.py#L352
https://github.com/django/django/blob/1.7.4/django/db/models/query.py#L145

I guess this issue could be easily fixed like this:

```python
if queryset is None:
    queryset = self.get_queryset()

```

**Comment by codingjoe** [comment]
@magicjohnson good catch! Do you want to write the patch, or should I? You can also just send me your author string.

**Comment by codingjoe** [comment]
Released in 5.4.1

Again BIG thanks!

**Comment by magicjohnson** [comment]
thank you for quick response ;)
