### ISSUE TITLE
Problems with upgrade...

### ISSUE THREAD

**Issue by diegomatar** [applegrew/django-select2#234]
In the upgrade from 4. to 5., I did not understand what is the new widget I should use to replace "AutoModelSelect2TagField"...

My forms.py was working fine since I upgraded:

        from django_select2 import AutoModelSelect2TagField

        class TagField(AutoModelSelect2TagField):
            queryset = Tag.objects
            search_fields = ['nome__icontains', ]

            def get_model_field_values(self, value):
        
                return {'nome': value, 'slug':slugify(value)}

        class PerguntaForm(forms.ModelForm):
                tags = TagField(label="")

**Comment by codingjoe** [comment]
Hi @diegomatar,
Take a look at the [docs](http://django-select2.readthedocs.org/en/latest/django_select2.html#django_select2.forms.ModelSelect2TagWidget) here.

Let me know if the description is not sufficient enough.

**Comment by diegomatar** [comment]
I did try to understand the docs before open this ticket, but I think their linguagem goes beyond my Django skills and I could not figure out if the corret widget.
I understand that I need a Heavy one, since there are thousands of values for tags.
But could not decide if the correct substitute wold be tag, select or mixins.

**Comment by codingjoe** [comment]
This should do the trick.
```python
class TagWidget(ModelSelect2TagWidget):
    queryset = Tag.objects.all()

    def value_from_datadict(self, data, files, name):
        values = super().value_from_datadict(self, data, files, name)
        qs = self.queryset.filter(**{'pk__in': list(values)})
        pks = set(force_text(getattr(o, pk)) for o in qs)
        cleaned_values = []
        for val in value:
            if force_text(val) not in pks:
                val = queryset.create(title=val).pk
            cleaned_values.append(val)
        return cleaned_values

class PerguntaForm(forms.ModelForm):
        class Meta:
            widgets = {'tags': TagWidget}
```
