### ISSUE TITLE
Add extra parameters to filter in queryset dynamically.

### ISSUE THREAD

**Issue by Gustavosdo** [applegrew/django-select2#237]
Hello,
Is there a way to work with results returned in the widget dynamically with values in the form?

Example:

    continent = request.GET.get('continent', '')
    queryset = Country.objects.filter(continent=continent)

I checked some methods, such as *filter_queryset*. But I have not found any that has access to the attributes on the form.

I found some issues, like this:
https://github.com/applegrew/django-select2/issues/22#issuecomment-41167962

But I noticed that the *get_results* method is no longer available to overwrite ..

**Comment by codingjoe** [comment]
@Gustavosdo You are not the first one to request such a feature #195.
I agree it would be nice, but it is also very hard to implement in a generic way. The only possibility I see is  to create your own JSON endpoint and to handle additional parameters.
You also need to make sure to collect these parameters. @anneFly did a great job making the js code more extendable.

I'm totally open for a pull request, but I don't have the time to implement a feature I don't need.
