### ISSUE TITLE
'u' character is treated as token separator

### ISSUE THREAD

**Issue by daddz** [applegrew/django-select2#238]
Hey,

I'm using the `ModelSelect2TagWidget` with default settings.
Whenever I tried adding a tag and started to type it worked until I hit the 'u' character which lead to separating it and starting a new one.

After countless hours of trying around several things to fix this I found the cause in the generated `<select ...>` field.

This is the code in the final html: `data-token-separators="[u',', u' ']"`
I'm not sure if it's caused by my Python/Django version combination or something else. Maybe this is a bug in select2 itself. I'm not sure and don't know enough about the internals.

Workaround for now is to set it manually and everything works as expected: 
`MyCustomTagsSelect2TagWidget(attrs={'data-token-separators': "[',', ' ']"})`

Environment:
Python 2.7.9
Django 1.8.7
Default Django development server

If you need more information just let me know

**Comment by codingjoe** [comment]
@daddz thanks, that is a bug in deed! Good catch. Do you know the proper markup to define the separators in a `data`-attribute? Maybe you can try to it since you have a setup locally. Just pass the following attrs to the widget:
```python
ModelSelect2TagWidget(attrs={'data-token-separators': ', '})
```
And see if that does the job, would be great to get some feedback so I can write a patch to fix the bug.

**Comment by hrishiballal** [comment]
Same issue here with the latest release, it is not recognizing character u. and even when using the token-seperators as above; 
```python
self.attrs.setdefault('data-token-separators', [", ", ",", " "])
```

**Comment by codingjoe** [comment]
@hrishiballal do you have a solution that works? I'm happy to patch it, but I don't know how.

**Comment by jonatascastro12** [comment]
I got the same issue. Should put `data-token-separators` attribute as string, so it'll be parsed correctly.

My patch works:

`self.attrs.setdefault('data-token-separators', '[",", " "]')`

**Comment by codingjoe** [comment]
@jonatascastro12 can you create a pull-request for that?

**Comment by jonatascastro12** [comment]
\o/
