### ISSUE TITLE
how to change language?

### ISSUE THREAD

**Issue by dchoruzy** [applegrew/django-select2#241]
hi,

how to change language for django-select2?
’no matches found’ appears in english, i need to change it to russian.

**Comment by codingjoe** [comment]
Hi @dchoruzy,
have a look at #212 this should do the trick for you. Just change the placeholder to whatever you like.

**Comment by Mastermind-U** [comment]
Hi @dchoruzy I've found that u can just change `data-language="ru"` attribute in your widget by js or u can add `attrs={'data-language': 'ru'}` to your widget arguments in form.
