### ISSUE TITLE
Allow to specify global options

### ISSUE THREAD

**Issue by toabi** [applegrew/django-select2#242]
To use e.g. <https://github.com/select2/select2-bootstrap-theme> one would have to add `{theme: 'bootstrap'}` to all places where djangoSelect2() is called. It would be cool to have `SELECT2_OPTIONS` as a dict in the section which is always added to the calls.

**Comment by codingjoe** [comment]
@toabi the cleanest way is actually to create a mixin as explained [here](https://github.com/applegrew/django-select2/pull/220#issuecomment-152980298).
