### ISSUE TITLE
ModelSelect2Widget not match value

### ISSUE THREAD

**Issue by sebastien247** [applegrew/django-select2#244]
# French
Bonjour,
J'utilise select2Widget pour des champs de formulaire de taille opposé, une dizaine de valeurs pour les catégories et quelques millier de valeurs pour les villes. Si j'applique la technique des catégories sur les villes cela me crash le navigateur car il y a trop de données. Donc j'utilise la technique décrite ci-dessous, cependant j’obtiens l'erreur suivant lorsque que je réinjecte la valeur dans le formulaire 
```filtersForm = FiltersTestForm(request.GET or None)```. Est-ce normal ou est-ce un bug ?

    Select a valid choice. 32994 is not one of the available choices.

# English
Hello,
I use select2Widget for size form fields opposite, a dozen values for categories and the few thousand values for cities. If I apply the technical categories on cities that crash my browser because there is too much data. So I use the technique described below, however, I get the following error when I re-injects the value in the form
`` `filtersForm = FiltersTestForm (request.GET or None)` ``. Is this normal or is it a bug?

    Select a valid choice. 32994 is not one of the available choices.

# Code
```python
def test(request):
    data = {}
    filtersForm = FiltersTestForm(request.GET or None)
    announcements = Announcement.objects.all()
    data['filtersForm'] = filtersForm
    data['announcements'] = announcements
    return render(request, 'frontend/announcementsTest.html', data)


class FiltersTestForm(forms.Form):
    category = forms.ModelChoiceField(
        widget=Select2Widget(attrs={'data-placeholder': _(u"Catégorie")}),
        queryset=Category.objects.all(),
        required=False,
    )
    city = forms.ChoiceField(
        widget=ModelSelect2Widget(
            attrs={'data-placeholder': _(u"Ville")},
            model=City,
            search_fields=['name__istartswith', 'zip_code__istartswith', ],
        ),
        required=False,
    )
```

**Comment by codingjoe** [comment]
Hi @sebastien247,
I need a little bit more info to help you out.
Ok, so what's inside your GET request? The error message is pretty clear to me. You are passing a value that is not inside the City queryset.
Cheers,
Joe

**Comment by sebastien247** [comment]
Hi, thank you for your answer,
My GET request return this : ```<QueryDict: {u'category': [u'1'], u'city': [u'33551']}>``` This value is given by the field ModelSelect2Widget. Why she would no longer be in the queryset?
Cheers,
Sebastien

**Comment by codingjoe** [comment]
@sebastien247 thanks for the update! I'm glad its working now.
