### ISSUE TITLE
ModelSelect2TagWidget doesn't work with new tags

### ISSUE THREAD

**Issue by sztankatt** [applegrew/django-select2#245]
Hi! I basically copy pasted this from the testapp:
```python
class TagWidget(ModelSelect2TagWidget):
    search_fields = [
        'name__startswith'
    ]
    model = Tag

    def create_value(self, value):
        self.get_queryset().create(name=value)
```
But, the problem is, when I instert a tag into the field which wasn't used before (the expectation is that django will save it first), I get the following error:
    ValueError at [...] invalid literal for int() with base 10:

I also tried the solution, that is:
```python
class MyModelSelect2TagWidget(ModelSelect2TagWidget):
    queryset = MyModel.objects.all()

    def value_from_datadict(self, data, files, name):
        values = super().value_from_datadict(self, data, files, name)
        qs = self.queryset.filter(**{'pk__in': list(values)})
        pks = set(force_text(getattr(o, pk)) for o in qs)
        cleaned_values = []
        for val in value:
            if force_text(val) not in pks:
                val = queryset.create(title=val).pk
            cleaned_values.append(val)
        return cleaned_values
```
But it wasnt working as well.

Could you help me figure this out?

**Comment by codingjoe** [comment]
Hi @sztankatt I just saw that there is a type in the documentation. It should be
`for val in values:`

**Comment by codingjoe** [comment]
I just created a PR for a little fix, can you try if it actually works for you? #248
