### ISSUE TITLE
AutoModelSelect2Field

### ISSUE THREAD

**Issue by dianahernandez** [applegrew/django-select2#247]
Hi, I want to know how to run the previous AutoModelSelect2Field role in the new django-select2==5.6
Thank you

**Comment by codingjoe** [comment]
Hi @dianahernandez 

check out our [documentation](http://django-select2.readthedocs.org/en/latest/django_select2.html#django_select2.forms.ModelSelect2Widget). Maybe also take a look at the update instructions in the readme file.
Let me know if you need further instructions of if we can improve our documentation.

Cheers,
Joe
