### ISSUE TITLE
Error loading data for HeavySelect2MultipleWidget

### ISSUE THREAD

**Issue by garyhesse** [applegrew/django-select2#249]
Attempting to use HeavySelect2MultipleWidget in a form with a data_url, but I get a "Uncaught TypeError: Cannot read property 'results' of undefined" error on line 19 of django_select2.js. 

The call in forms.py looks like this:
```python
categories = forms.MultipleChoiceField(
        widget=HeavySelect2MultipleWidget(data_url = 'static/js/vendor/factual176.json'),
		required=False
	)
```

The format of the JSON data looks like this:
```JSON
{ "results": [{ "id": 1,"label": "Factual Places","text": "Factual Places"}, {"id": 2,"label": "Automotive","text": "Automotive"}, {"id": 3,"label": "Car Appraisers","text": "Automotive/Car Appraisers"},...
```

I'm using this tag on the template to include select2:
`{{ form.media.js }}`

I get this in the console, so it looks to me like it's finding the JSON file, but I'm unclear what's failing, and why:
```
[31/Jan/2016 17:12:09]"GET /static/js/vendor/factual176.json?field_id=NDQwNzkzMzAwOA%3A1aPvXU%3AEnSmfECr2vFAB-hlQNMUS8SJD9E HTTP/1.1" 200 18453
```

**Comment by codingjoe** [comment]
Hi @garyhesse ,

is this a new problem, or are you just starting out to use `django-select2`.
I don't see an error, since you get a 200 from the JSON endpoint and the data seems correct.

Is your JSON dump the response body of the request from the browser?

Cheers,
Joe

**Comment by garyhesse** [comment]
Joe,

I'm just starting to implement django-select2 in a new project. I am seeing the JSON in the browser at that path.

**Comment by codingjoe** [comment]
Ok, so the problem seems to be javascript side. Do you use jQuery 1 or 2?

**Comment by garyhesse** [comment]
jQuery 2.2.0.

**Comment by garyhesse** [comment]
Update: I rolled back to jQuery 2.1.4 and the TypeError message disappeared. However, I'm still not getting the JSON elements to appear in the select. Using the data example above, typing 'Auto' in the widget leads to this in the console:
`[03/Feb/2016 17:48:36]"GET /static/js/vendor/factual3.json?term=Auto&field_id=NDQwMzgzMjMzNg%3A1aR1Rf%3ABL9BxsKdEi3_WNSSeAq7IRSAKzY HTTP/1.1" 200 121`
... but I still see the 'Searching' message and nothing loads in the widget.

**Comment by garyhesse** [comment]
Update 2: I rolled back even further to jQuery 1.12.0. The data now loads in the widget, but I expected that typing would filter the widget to matching elements and that's not happening. Should it be, or am I misunderstanding the widget's function?

**Comment by codingjoe** [comment]
@garyhesse no, please stay with jQuery 2. Select2v4 doesn't support jQuery 1

**Comment by garyhesse** [comment]
Joe,
Is there a version of jQuery you recommend that should work with the widget?

**Comment by garyhesse** [comment]
Screenshot with jQuery 1.12.0:
![screen shot 2016-02-03 at 11 11 25 am](https://cloud.githubusercontent.com/assets/1245629/12793813/1fe8870c-ca67-11e5-9377-34c70c68f25a.png)

Screenshot with jQuery 2.0.0:
![screen shot 2016-02-03 at 11 12 06 am](https://cloud.githubusercontent.com/assets/1245629/12793848/32c901c6-ca67-11e5-90cf-50b3b8227d78.png)

**Comment by codingjoe** [comment]
@garyhesse you should use the latest jQuery2 version. But the problem seems to be in you JSON response. You have `label` in there, where it should only by `id` and `text`.

**Comment by garyhesse** [comment]
I tested with this JSON response and jQuery 2.2.0 without success:
```{"results": [{"id": 1,"text": "General"}, {"id": 2,"text": "Automotive"}, {"id": 3,"text": "Automotive/Car Appraisers"}]}```

**Comment by codingjoe** [comment]
This is very strange, it works for tons of people. I don't know all your code. I'm afraid that is all I can do for you :(
