### ISSUE TITLE
Docs: What is a "Auto-Field"?

### ISSUE THREAD

**Issue by guettli** [applegrew/django-select2#250]
From the docs: http://django-select2.readthedocs.org/en/latest/get_started.html#installation

{{{
Add django_select to your urlconf if you use any ‘Auto’ fields:
}}}
What do you mean with "Auto fields" here?

**Comment by guettli** [comment]
Do you mean Model-Widget? See: http://django-select2.readthedocs.org/en/latest/django_select2.html#module-django_select2.forms

**Comment by codingjoe** [comment]
Hi @guettli 
good catch. It should be model widgets.

**Comment by codingjoe** [comment]
@guettli is this better #251

**Comment by guettli** [comment]
Yes, very nice. A link to the widgets says it all. Thank you.

**Comment by codingjoe** [comment]
@guettli I did a big docs upgrade. I added spell checking for the future to make the docs even better.
Thanks again for the feedback!
