### ISSUE TITLE
ModelSelect2Widget is only two characters wide, Select2Widget works

### ISSUE THREAD

**Issue by guettli** [applegrew/django-select2#252]
ModelSelect2Widget is only two characters wide, Select2Widget works

See screenshot:

![screenshot-select2-input-very-thin](https://cloud.githubusercontent.com/assets/414336/12795299/9fd354c2-cab9-11e5-9f95-04dc8d92fae5.png)

Do you have a clue what could be wrong here?

**Comment by codingjoe** [comment]
Hi @guettli ,

select2 automatically takes the size of the original input. You might want to check your CSS to change the select size.

Besides, this is a select2 issue. Please refer to their documentation and help desk.

Cheers,
joe

**Comment by guettli** [comment]
I solve my issue with this css:
```
.django-select2 {
    width: 14em;
}
```

**Comment by codingjoe** [comment]
:+1:

**Comment by nuarhu** [comment]
This works for me. Essentially, you can add any options that Select2 offers via `data-*` attributes this way:

            widget=ModelSelect2MultipleWidget(model=MyModel,
                                              queryset=MyModel.objects.all(),
                                              search_fields=['value__icontains'],
                                              attrs={
                                                  'data-placeholder': 'Search for MyModel values',
                                                  'data-width': '50em'
                                              })
