### ISSUE TITLE
Capture JSON id value

### ISSUE THREAD

**Issue by garyhesse** [applegrew/django-select2#255]
When using the HeavySelect2MultipleWidget with a JSON data source, a selected item displays the text field in li.select2-selection__choice. I need to capture the related id value for each selected item as well - perhaps as a data attribute? I haven't found anything in the documentation to provide for this, but that might just be me. Any recommended approach to displaying the id value?

**Comment by codingjoe** [comment]
Hallo again,

well lets see if I got it right, shall we? You want to know related data from each selected choice in JavaScript or rather your DOM, right?
You can change how the choice are being rendered in select2. Thus you can attach any `data`-attribute you like. I for myself, server the choices as including JSON text and render them dynamically for one use case.

Check [this](https://select2.github.io/examples.html#data-ajax). What you want to look into is the `templateResult`, `templateSelection`, `escapeMarkup` and `containerCssClass` setting.

Let me know if you need any help, I'm sure I can write a little example. Tho you might want to consider reaching out to the select2 guys. They usually do the JS and me the Python code.

Cheers,
Joe
