### ISSUE TITLE
Select2 Clear vs. Removing Single Element

### ISSUE THREAD

**Issue by toabi** [applegrew/django-select2#256]
I used `$('#id_myfiled').val()` to get the value of the field. 

I'm using the `Select2MultipleWidget` on a form. If I add and remove items using the `x` on the single item, the empty field has value `null`. If I use the field-wide `clear` button, the resulting value is `[""]`. This leads to a form validation error.

I'm not sure if I have to file this against select2 or here.

**Comment by codingjoe** [comment]
Does it this package break if you use the option-`x` or the field-`x`?

**Comment by sebastien247** [comment]
I have the same problem but this causes a graphical bug :
![capture-6](https://cloud.githubusercontent.com/assets/2801027/13028129/f286734e-d265-11e5-9f5d-503fb297c242.png)
![capture-7](https://cloud.githubusercontent.com/assets/2801027/13028128/f2827334-d265-11e5-8790-6d3e4daf4e2c.png)
![capture-8](https://cloud.githubusercontent.com/assets/2801027/13028127/f27f4498-d265-11e5-8708-6f9074bf57c0.png)

**Comment by codingjoe** [comment]
@sebastien247 how so?

**Comment by sebastien247** [comment]
When handling graphics, this causes me a blank space, and then when I selected a new element empty choice is visible :

![capture-27](https://cloud.githubusercontent.com/assets/2801027/14612395/1e2b1a0e-0597-11e6-844d-ee5f45d07a35.png)

**Comment by codingjoe** [comment]
@sebastien247 the latter one I've seen too. Is there a good fix for that?

**Comment by sebastien247** [comment]
For this graphical bug :
![](https://cloud.githubusercontent.com/assets/2801027/13028127/f27f4498-d265-11e5-8708-6f9074bf57c0.png)

Just remove this :
`<span class="select2-selection__clear">×</span>`

I search for the empty element

**Comment by kevin-brown** [comment]
_(Coming from the Select2 side)_

> this causes me a blank space, and then when I selected a new element empty choice is visible :

Usually this happens when a blank option is included for the placeholder, even though you are using a multiple select. The blank placeholder option is only needed for a single select.

Here's the part of the code where it is added: https://github.com/applegrew/django-select2/blob/0b3abb8f1f56ff94154ab50de4ea352184b5ef8e/django_select2/forms.py#L95

**Comment by codingjoe** [comment]
@kevin-brown does that help you? #275

**Comment by OVarLaz** [comment]
Hi!
I have the same issue when I try to clean the selected contents, clicking in global "x"
![x](https://user-images.githubusercontent.com/12819313/72737627-e8b6f580-3b6d-11ea-8b7a-0c9c442d7fa2.PNG)
I have updated the version of django-select2 (7.2.0 ... lastest)

**Comment by codingjoe** [comment]
Hi @OVarLaz,

glad you asked. @kevin-brown answered that bid here https://github.com/applegrew/django-select2/issues/256#issuecomment-212446692

The please check your rendered template (HTML code without JavaScript running). You will see that there is a bit in the select, like so: `<option value="">------------</option>`.
I don't know how you added the empty label select. Should you need help debugging, I am happy to assist. I must ask you to share a bit of code in that case though.

Best
-Joe
