### ISSUE TITLE
Heavy widgets and ajax example.

### ISSUE THREAD

**Issue by kierun** [applegrew/django-select2#257]
I  have a model (let's call it Animal) that has a `ForeignKey` to a Genus model. I would like to have a `ModelForm` that allows the user to select an Animal instance. Clearly, there are too many animals for a single select list so I would like the user to be able to filter by genus and then search by animal.

Select2 has an example of using Ajax request to do something oh-so-similar to what I want. Instead of searching for a _usr/repo_, I would search for a _genus/animal_. The user might not know the exact genus or the exact animal they want, so both bits need to be searchable. This UI is fine for my needs.

In my ModelForm's __init__(...), have:

```
self.fields['animal'] = forms.ModelChoiceField(
    widget=HeavySelect2Widget(data_view='heavy_data'),
    queryset=Animal.objects.all())
```

And in the views:

```
def heavy_data(request):
    filtered_animals = {}
    if request.is_ajax():
        import ipdb
        ipdb.set_trace()
        # What next?
    return HttpResponse(json.dumps(filtered_animals))
```

I am unsure how to pass the whole genus/animal search string form the form to the view. However, I might not even be on the right tracks... Am I? Is there a better way to do what I w

**Comment by codingjoe** [comment]
Hi @kierun,
why don't you use the `[Select2ModelWidget](http://django-select2.readthedocs.org/en/latest/django_select2.html#django_select2.forms.ModelSelect2Widget)`?

If that doesn't suit you, you should take a look at the `[AutoResponseView](http://django-select2.readthedocs.org/en/latest/_modules/django_select2/views.html#AutoResponseView)` to get an idea how write your own view.

**Comment by kierun** [comment]
I am still in the dark I am afraid. Maybe an example would make things clearer. 

Let say I have animals (genus) like so: `Cat (mammal)`, `Emu (mammal)`, `Salmon (fish)`, and `Tit (bird)`. At load, the select box would have all four listed as: `Cat`, `Emu`, `Salmon`, `Tit`. When I type "mammal", I would get only `Cat` and `Emu`. If I were to search for "mam/ca", I would only get `Cat`.

I can see how to do that iff I can get the search string within some view which can then return a filtered list of Animals.  But I am afraid I cannot immediately see how to do that with `Select2ModelWidget` or `AutoResponseView`...

**Comment by codingjoe** [comment]
@kierun that's easy. You don't need a to change the view in that particular case.

```
class AnimalWidget(Select2ModelWidget):
    model = Animal
    
    def filter_queryset(self, queryset=None):
        return queryset.filter(do='whaterver')
````

**Comment by kierun** [comment]
Oh, that simple! ^_~

Actually, I ended up using `search_fields = ['name__icontains', 'genus__name__icontains']` form `ModelSelect2Widget` as it makes for an easier search: you just type genus and animals in the search box. No need to learn weird formatting.

Many thanks indeed!!!

**Comment by codingjoe** [comment]
> Oh, that simple! ^_~
In deed :smile: 
I'm happy to help, let me know if we could update the documentation to be more specific.
