### ISSUE TITLE
field_id not found

### ISSUE THREAD

**Issue by sebastien247** [applegrew/django-select2#258]
Hi,
After a short moment of inactivity on the website, i obtain this error :

> GET http://127.0.0.1:8080/select2/fields/auto.json?field_id=MTQwMTY1NjcyMjQ1MDcy%3A1aUeII%3AP3TUBsJOeEEXSnjhtcj6JVKbqWk 404 (Not Found)

Is the cache ?

**Comment by codingjoe** [comment]
Hi @sebastien247 I presume you use the locmem backend locally. This means, whenever the server restarts the cache ist lost. Please make sure to use redis, memcached  or another persistent cache backend locally.

Please let me know if you experiencing still issues.

**Comment by sebastien247** [comment]
Perfect, it works ! Thank you.

**Comment by aliev** [comment]
@codingjoe @sebastien247 It works but when the page is opened for a while it stops working.

**Comment by aliev** [comment]
looks like the reason was a cache TIMEOUT option:
https://docs.djangoproject.com/en/1.8/ref/settings/#timeout

Default: 300 (5min)
