### ISSUE TITLE
problem with ModelSelect2Widget

### ISSUE THREAD

**Issue by dianahernandez** [applegrew/django-select2#259]
Django==1.8, Django-Select2==5.8.0 and django-jquery==1.9.1 (?)

**My form:**
```python
class CedulaForm(forms.Form):
    persona = forms.ChoiceField(
        widget=ModelSelect2Widget(
            model=Persona,
            search_fields = ['nombre1__icontains', 'nombre2__icontains', 'apellido1__icontains', 'apellido2__icontains', 'numero_documento__icontains']
        )
    )
```
**My view:**
```python
def modificarp(request):
    personaModificada = request.session.get('persona_modificada')
    if personaModificada == True:
        del request.session['persona_modificada']

    if request.method == 'POST':
        form = CedulaForm(request.POST)
        if form.is_valid():
            print('xD')
            return redirect('rh_modificar_persona', persona.id)
        else:
            print('D:')
    else :
        form = CedulaForm()

    return render(request, 'salud_modificarp.html', {
        'form': form,
    })
```
But the result is ... always prints 'D:' ie, never reaches form.is_valid() why?
Mi resultado es... siempre imprime 'D:' es decir, nunca llega a form.is_valid() por qué?

**Comment by codingjoe** [comment]
Hola @dianahernandez,

it seems too like your form isn't valid.
You might want to consider not printing smilies but `form.errors` or even use `pdb` to debug the whole thing.

Cheers,
Joe

**Comment by hobarrera** [comment]
Pro tip: add `import ipdb; ipdb.set_trace()` at any line, and django will pause there and give you an interactive shell to figure things out.

**Comment by dianahernandez** [comment]
They have not understood me ... I need to know what I have bad, because I have no compilation errors (apparently the form is well written) but execution errors.

Or they can show me another way to extract the value of an attribute of a form with ModelSelect2Widget after is_valid but before save ()

**Comment by dianahernandez** [comment]
@codingjoe I know I should not print emoticons (that will not production) but wanted to know what was the flow of my data and I want to know why it is always invalid form.
#####
sé que no debo imprimir emoticones (eso no va a producción) pero quería saber cuál era el flujo de mis datos y quiero saber porqué siempre es no válido el formulario.

**Comment by hobarrera** [comment]
> @codingjoe I know I should not print emoticons (that will not production) but wanted to know what was the flow of my data and I want to know why it is always invalid form.

Printing the form errors will tell you exactly why the form is invalid: https://docs.djangoproject.com/en/1.9/ref/forms/api/#django.forms.Form.errors

**Comment by dianahernandez** [comment]
but I have django 1.8 not 1.9

**Comment by codingjoe** [comment]
@dianahernandez that doesn't matter. It's been like that forever.
```python

def modificarp(request):
    personaModificada = request.session.get('persona_modificada')
    if personaModificada == True:
        del request.session['persona_modificada']

    if request.method == 'POST':
        form = CedulaForm(request.POST)
        if form.is_valid():
            print('xD')
            return redirect('rh_modificar_persona', persona.id)
        else:
            print(form.errors)
    else :
        form = CedulaForm()

    return render(request, 'salud_modificarp.html', {
        'form': form,
    })
```

You might also want to consider using class based views.
```python
class ModifiCarpView(generic.FormView):
    form_class = CedulaForm

def form_valid(self, form):
    persona = form.cleaned_data['persona']
    return redirect('rh_modificar_persona', persona.id
```
