### ISSUE TITLE
HeavySelect2Widget is not rendering selected options after ValidationError is raised on form

### ISSUE THREAD

**Issue by darbula** [applegrew/django-select2#260]
The problem is traced to [`render_options`](https://github.com/applegrew/django-select2/blob/master/django_select2/forms.py#L230) call where `selected_choices` (second element in `args` list) is list of `unicode`s instead of expected list of integers. `Django==1.8.9`

**Comment by darbula** [comment]
The problem is in django's `BoundField.value˙ method that:

> Returns the value for this BoundField, using the initial value if the form is not bound or the data otherwise.

In `initial` value is integer and in `data` it is unicode.

Django solves this by normalizing to strings i.e. in `Select` widget method `render_options` there is a line `selected_choices = set(force_text(v) for v in selected_choices)` and then in `render_option` `option_value = force_text(option_value)`.

**Comment by codingjoe** [comment]
@darbula thanks for the bug report. But to be honest I have absolutely no clue what you are talking about. Could you be a little more specific on what's failing and how? Maybe even include a stack trace?

Thanks!

**Comment by darbula** [comment]
There is no stack trace since the issue is visible in the frontend only.

It is very easy to reproduce this error. You need form with two fields, one using HeavySelect2Widget and other for example CharField. Then write simple clean method for char field that raises ValidationError when the value length is for example less than 3.

Load form in the browser select few values in select widget and enter string `foo` (length is 3 so no ValidationError is raised) in char field and post. Data is saved. Load again same form to edit saved  data. It should display selected values and char field with string `foo`. Now delete last letter of char field and post it. This should trigger ValidationError since the length is less than 3. Form has errors so model is not saved in the browser you get same form with char field has value `fo`, as it should, but select2 widget has no items selected anymore.

**Comment by codingjoe** [comment]
This seems like a valid use case. Please provide a test in your PR.
