### ISSUE TITLE
Click to select first element

### ISSUE THREAD

**Issue by darbula** [applegrew/django-select2#264]
In `HeavySelect2MultipleWidget` selecting first element from drop down list is not possible neither by clicking on it or using keyboard arrows. Selecting other elements is successful.
## Tests

After merging PR #262 following two test methods should be added to the class `TestHeavySelect2MultipleWidget` in `test_forms.py`. First test for selecting first element is failing while second test for selecting second element does not.

```
    def test_widgets_select_first(self, db, live_server, driver):
        driver.get(live_server + self.url)
        with pytest.raises(NoSuchElementException):
            driver.find_element_by_css_selector('.select2-results')
        genres, fartists = driver.find_elements_by_css_selector('.select2-selection--multiple')
        genres.click()
        genres.send_keys('o')  # results are Zero One Two Four
        # select first element - Zero
        driver.find_element_by_css_selector('.select2-results li:first-child').click()
        result_title = driver.find_element_by_css_selector('.select2-selection--multiple li').get_attribute('title')
        assert result_title == 'Zero'

    def test_widgets_select_second(self, db, live_server, driver):
        driver.get(live_server + self.url)
        with pytest.raises(NoSuchElementException):
            driver.find_element_by_css_selector('.select2-results')
        genres, fartists = driver.find_elements_by_css_selector('.select2-selection--multiple')
        genres.click()
        genres.send_keys('o')  # results are Zero One Two Four
        # select second element - One
        driver.find_element_by_css_selector('.select2-results li:nth-child(2)').click()
        result_title = driver.find_element_by_css_selector('.select2-selection--multiple li').get_attribute('title')
        assert result_title == 'One'
```

**Comment by TheJimFactor** [comment]
Had this issue come up today. Any idea why it's happening?

**Comment by darbula** [comment]
I just stumbled on this issue and wrote those tests, did not investigate any further.

**Comment by codingjoe** [comment]
Hm... could this be a select2 bug? I just upgraded to 4.0.3 in the latest django-select2 release. Maybe is there any difference?

**Comment by tisdall** [comment]
I found this issue was due to having an "id" of "0".  The tests use `enumerate` which give the first element a "0" id. If you add a `+1` in there the issue disappears.

**Comment by codingjoe** [comment]
Closed: **This issue has been inactive for an extended period of time. Please reopen the issue if it is still relevant.**
