### ISSUE TITLE
How to implement a [+] button beneath autocomplete input to create new instances in FK table

### ISSUE THREAD

**Issue by guettli** [applegrew/django-select2#266]
I think it is a very common use case:

I want to implement a [+] button beneath autocomplete input to create new instances in FK table

I asked on the django-user list, but got no reply:

https://groups.google.com/forum/#!topic/django-users/oHyFuDPIjeE

Does django-select2 offer a way to implement this? I guess not.

Why not enhance django-select2 to include this feature?

**Comment by guettli** [comment]
I found that autocomplete-light supports this:

http://django-autocomplete-light.readthedocs.org/en/latest/addanother.html

What is your hint for me?

Use autocomplete-light or investigate how to get this done with django-select2?

**Comment by codingjoe** [comment]
I know that @anneFly did some work on the JS implementation to dynamically add new fields.
I general I'm open to new features, so if you are willing to implement it, please be my guest.

**Comment by jpic** [comment]
[django-addanother](https://github.com/jonashaag/django-addanother) should work.
