### ISSUE TITLE
multi autocomplete for array field

### ISSUE THREAD

**Issue by EvgeniyBurdin** [applegrew/django-select2#267]
`models.py:`

```
from django.contrib.postgres.fields import ArrayField

class AdDO(models.Model):
    ...
    tags_name = ArrayField(models.CharField(max_length=40,
                           blank=True, null=True),
                           blank=True, null=True)

class Tag(models.Model):
    ...
    name = models.CharField(max_length=40, db_index=True)
```
The `AdDO.tags_name` needs to get the character field, for example: "watermelon red, green leaf, black stone" (Tag.name values separated by commas)
_I do not use many-to-many relationship, I do not need. Just need to insert the characters fields in the array (string) field._

How do multi autocomplete for the field `AdDO.tags_name` from `Tag.name`?

**Comment by codingjoe** [comment]
@EvgeniyBurdin does [this](http://django-select2.readthedocs.org/en/latest/django_select2.html#django_select2.forms.Select2TagWidget) help you? I don't know much about ArrayFields, but let me know if we need to update the documentation.

**Comment by EvgeniyBurdin** [comment]
An `ArrayField` is a string that consists of strings separated by commas. That is, my example, can be replaced by:

```
class AdDO(models.Model):
    ...
    tags_name = models.CharField(max_length=245,  #  for max 6 Tag.name, including commas 
                                                       blank=True, null=True)

class Tag(models.Model):
    ...
    name = models.CharField(max_length=40, db_index=True)
```

how to make a completion for this tags_name field?

**Comment by codingjoe** [comment]
@EvgeniyBurdin you just need to overwrite `filter_queryset` or just `queryset`. You should provide they queryset you'd like to use to for autocompletion.

**Comment by EvgeniyBurdin** [comment]
What is a widget to choose?

**Comment by codingjoe** [comment]
```python
class MyWidget(ModelSelect2TagWidget):
    queryset = MyChoiceModel.objects.all()

    def value_from_datadict(self, data, files, name):
        values = super(ModelSelect2TagWidget, self).value_from_datadict(data, files, name):
        return ",".join(values)

```

**Comment by EvgeniyBurdin** [comment]
my example:
```
class TagitWidget(ModelSelect2TagWidget):
    queryset = Tag.objects.all()

    def value_from_datadict(self, data, files, name):
        values = super(TagitWidget, self).value_from_datadict(data, files, name)
        return ",".join(values)


class SomeForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('__all__')
        widgets = {
            'tags_name': TagitWidget
        }


class ArticleAdmin(admin.ModelAdmin):
    form = SomeForm
    list_display = ('title',)  # поля, показываемые в админке


```

screen from admin form:
[http://itmages.ru/image/view/3968224/60ad403c](url)

**Comment by codingjoe** [comment]
This seems to be a JavaScript issue. The field doesn't even have the right size. I remember that `django.contrib.admin` uses Bootstrap 2 since version 1.8. You need to add a template that adds support for Bootstrap 2.
