### ISSUE TITLE
new tag position

### ISSUE THREAD

**Issue by bcail** [applegrew/django-select2#270]
I would like to move the position of the new tag that the user's typing to the bottom of the list, instead of the top. That seems to be newly supported in select2 4.0.2 (https://github.com/select2/select2/pull/4008). What's the best way to do this in django-select2?

**Comment by bcail** [comment]
Update: I got it working by doing the following:
1. copy django_select2.js to local app, and add the following:
$('.django-select2').djangoSelect2({
            insertTag: function (data, tag) {
                    data.push(tag);
                }   
            });

2. in my local widget, I copied the following lines as below (to use the local version of django_select2.js instead of the default):
    def _get_media(self):
        return forms.Media(
            js=(settings.SELECT2_JS, '<local app>/django_select2.js'),
            css={'screen': (settings.SELECT2_CSS,)}
        )   
    media = property(_get_media)

This worked, but is there a better way?

**Comment by codingjoe** [comment]
You don't need to copy the JS file. It's possible to overwrite the default JS options.
Check out how we do it for the heavy widget [here](https://github.com/applegrew/django-select2/blob/master/django_select2/static/django_select2/django_select2.js#L9-L26).

**Comment by bcail** [comment]
Thanks for replying. Are you saying that in my template I should override the initHeavy function, with the settings already listed in the django_select2.js file and adding the insertTag option?

Or is there a way to pass in the insertTag code as an option to the initHeavy function?

Sorry if I'm missing something obvious here...

**Comment by codingjoe** [comment]
No you should overwrite `attrs['class']` and add your own class. After that you can write your own `init` method that calls the init method provided by django-select2. Im I right @anneFly ?

**Comment by bcail** [comment]
Hmm, I tried overriding attrs['class'] when I instantiate my widget, but the normal django-select2 classes are still added to my custom class, and the regular init functions are still called. Would I need to override the widget build_attrs method as well?

**Comment by codingjoe** [comment]
Yes, I just append the class in the `build_attrs` method.
Let me know if you have any good ideas or learnings on how to improve extensibility of this package.

**Comment by bcail** [comment]
Well, it seems like the user needs to be able to pass options into the javascript pretty easily, since there's this insertTag feature from select2 that has to be done in javascript.

I see this line in django_select2.js, that's called automatically:
$('.django-select2').djangoSelect2();

It seems like if this line could have some options that default to empty, but that the user could pass things in as needed (without overriding that file completely), that would be nice. But I'm not exactly sure how to do this.

One option would be to take out the $('.django-select2').djangoSelect2(); line and have the user put it in their template. That would add another step that everyone would need to do to use django-select2, but it would make it a lot easier to add custom javascript code, because you could just pass options through that call (without needing to override that file completely).

Even better would be if you could call djangoSelect2() conditionally in django_select2.js - call it automatically if the user hasn't overridden it, but use the user's version if they have one in their template.

Hopefully there's something helpful in these comments.

**Comment by codingjoe** [comment]
Hm... good point. Regular options you can base as widget `attrs` but callbacks wont work here. I'll try to figure something out.

**Comment by codingjoe** [comment]
Closed: **This issue has been inactive for an extended period of time. Please reopen the issue if it is still relevant.**
