### ISSUE TITLE
Drop the need `icontains` in `search_fields`.

### ISSUE THREAD

**Issue by codingjoe** [applegrew/django-select2#273]
As seen in #272, differing from the default `icontains` search field pattern may cause unexpected problems. Considering this and the fact that search_fields are implemented differently in `django.contrib.admin` including the `django-select2` fork that is currently being merged it is advisable to change the behavior.

**Comment by nuarhu** [comment]
Note that `__icontains` has different requirements for effective DB indexes for search than `__istartswith`. If you decide to default to `__icontains`, it should at least be easy to switch to something else for the user, and the documentation should mention that in case of larger DB tables there could be a performance impact.

Creating an index in Postgres that supports searching in the middle of strings requires a trigram index which cannot be created via the Django ORM. It has to be created via an explicit migration with raw SQL. (There are other ways for fast searches in DBs, this is just an example.)

**Comment by codingjoe** [comment]
@nuarhu that is a very valid point, thanks!
Maybe it's best to allow both, but that also add complexity and a likeliness to make errors.
You know what, I will close it for now. This would be indeed risky. It's not that much effort, and really better to have people think about the performance for a send.

Thanks again 🥇
