### ISSUE TITLE
Select2TagWidget render with MySQL

### ISSUE THREAD

**Issue by oesah** [applegrew/django-select2#278]
Hey, 

I looked for hours now but still can't find a solution. I am using the Select2TagWidget on a text field. I want to save the data as a string list like [u'a', u'b', u'c']. It works nicely when saving, but when I reload the page, the field is empty. In Django Admin it is saved properly as [u'a', u'b', u'c']. How can I render those values in the field? 

regards, Özer

**Comment by oesah** [comment]
So I solved the problem with the following solution: 

```python
import ast
class MyWidget(Select2TagWidget):

	def render(self, name, value, attrs=None):
		value = [str(i) for i in value.split(",")]
		html = super(MyWidget, self).render(name, value, attrs)

		js = "".join([
				'<script type="text/javascript">',
					'var data = %s;' % value,
					'$("#id_keywords").select2({',
					  'data: data,',
					'}).val(data);',
				'</script>'
			])
		return mark_safe(html + js)

 class MyForm(forms.ModelForm):
	class Meta:
        ...
	    widgets = {
	        'keywords':MyWidget,
	    }

	def clean_keywords(self):
	    keywords = ast.literal_eval(
	    	self.cleaned_data.get('keywords')
	    )
	    return str(",").join(keywords)
```

This solution works, but is really not a nice way. Is there any other, better way of solving it? I just want the data, which is saved as `string1,string2,intAsString` to be loaded into the form field correctly.

**Comment by codingjoe** [comment]
Hi @oesah there is some code I don't get. Did you read the [latest documentation](http://django-select2.readthedocs.io/en/latest/django_select2.html#django_select2.forms.ModelSelect2TagWidget)? We actually have a documented example of this case.
Let me know if this helps you. An please drop the inline JS code, nether should this work, nor is it a good idea to inject JS code into your body.

**Comment by oesah** [comment]
The thing is, I'm not trying to have the model. I just wanted a simply CharField that saves values as `value1,value2,value3`. Is that a bad idea?

**Comment by oesah** [comment]
Ok so I've got a better and very simple solution: 

```python
from django.utils.encoding import force_text
import ast
class MyWidget(Select2TagWidget):

	def render_options(self, choices, selected_choices):
		"""Render only selected options."""
		output = []
		selected_choices = [force_text(v) for v in selected_choices.split(",")]

		for option_value in selected_choices:
			output.append(self.render_option(selected_choices, option_value, option_value))

		return '\n'.join(output)
```

So the idea is the following: 
* Have a Char or TextField
* Save multiple values with comma separated
* Have all the functionality of Select2TagWidget

If you have a nicer solution, in which Tags gets automatically created if not existing, that would be great. But for people who need a quick and easy solution, the one above works. Keep in mind to always save the data as comma-seperated in your form clean.

**Comment by codingjoe** [comment]
@oesah yes, bad idea. You should never serialize data into char strings in the database. Later you won't be able to index an search them properly. You should use an `Array` field. Django's ORM has an `ArrayField` that supports database arrays.

Check out the docs and the search the issues here, there where other people who implemented the tag field using the `ArrayField`.

**Comment by oesah** [comment]
ArrayField is PostgrewSQL specific. I am using MySQL. So there is no similar solution with MySQL I assume?

**Comment by codingjoe** [comment]
Haha, oh, I just assumed you use Postgres. Well I don't really know if there is an alternative in MySQL. You if you are still in an early stage with your project, I can only encourage you to switch to Postgres. It's just the better DB, especially when working with Django.

**Comment by oesah** [comment]
Yeah I just did that :) Will try out the solution with ArrayField

**Comment by oesah** [comment]
BTW, the solution above is dirty, but it works for MySQL. So if you like, you can add it to the docs, for people who need a quick fix for MySQL DBs.

**Comment by codingjoe** [comment]
@oesah sounds like a good idea. Please just open a pull request to do so.
