### ISSUE TITLE
css of select2 field ugly

### ISSUE THREAD

**Issue by Megido6** [applegrew/django-select2#279]
![2269d045df330dfefc2659379f1e1cd6](https://cloud.githubusercontent.com/assets/2589828/15967587/f7a4c81c-2f30-11e6-8ab8-21e89572b1d8.gif)

can use other widget or class for make it pretty,at least remove "tags style"?

**Comment by Megido6** [comment]
i use ModelSelect2Widget

**Comment by oesah** [comment]
Yeah I would also appreciate some styling tools. Currently, the TagWidget looks quite bad and I cannot seem to style it with CSS.

**Comment by Megido6** [comment]
it conflict with django-suit stylesheet

**Comment by codingjoe** [comment]
@Megido6 this problem is not django-select2 related but a bootstrap template issue. Sorry

**Comment by rishav00a** [comment]
Finally Solved this issue,
previously i was overriding the styling using JQuery but it was not able to find that element.
As a solution what is did is 

-> Create a js function

function chsize() {
		$(".select2-container--default").css("width","100%"); // this onw works only on Desktop
		$("head").append($("<link rel='stylesheet' href='/static/landing/css/override.css' type='text/css' media='screen' />")); // this will work everyehere whether it is Mobile, Desktop 
	}

-> Call the function on page load inside body tag

   <body onload="chsize();">

-> Here is my CSS file override.css
     .select2-container--default
{
  width: 100%;
}


Enjoy :)
