### ISSUE TITLE
Inline django-select2 and django-suit

### ISSUE THREAD

**Issue by soulraven** [applegrew/django-select2#284]
Hello,
there is a bug when using django-select2 and django-suit

![bug](https://cloud.githubusercontent.com/assets/1303303/16442017/adb272bc-3dd7-11e6-9f80-4d3d793978b4.jpg)

**Comment by codingjoe** [comment]
That is because django-suit uses bootstrap2. You'll need to add a bootstrap 2 template to similar to [this example](https://github.com/applegrew/django-select2/pull/220#issuecomment-152980298).
