### ISSUE TITLE
HeavySelect2MultipleWidget & HeavySelect2Widget do not set default data-minimum-input-length

### ISSUE THREAD

**Issue by mjmaenpaa** [applegrew/django-select2#286]
When using HeavySelect2Mixin together with Select2Mixin (For example HeavySelect2MultipleWidget & HeavySelect2Widget), default data-minimum-input-length will be 0 instead of 2. Due to Python's method resolution order, Select2Mixin.build_attrs is the first one to set data-minimum-input-length. Because it is already set, it won't be updated in HeavySelect2Mixin.build_attrs.

It seems that same is true also for Select2TagWidget, Select2TagMixin and Select2Mixin combination.

**Comment by codingjoe** [comment]
I remember someone was already working on this for other cases. I'd much appreciate a pull-request for your side. Thanks!

**Comment by codingjoe** [comment]
Closed: **This issue has been inactive for an extended period of time. Please reopen the issue if it is still relevant.**
