### ISSUE TITLE
ModelSelect2Widget in list_filter

### ISSUE THREAD

**Issue by Belanchuk** [applegrew/django-select2#289]
How I can set ModelSelect2Widget for field in list_filter?

**Comment by codingjoe** [comment]
Hi @Belanchuk,

I can't follow you. Do you maybe have an example?

Cheers,
Joe

**Comment by Belanchuk** [comment]
[https://box.everhelper.me/attachment/564618/0ab85512-bda0-41fc-a662-f9e8e8f7a626/526007-18LY0DsgLV3YdBLa/screen.png](url)
How can I change the default filter (list_editable) to Select2.
Select2 on the editable_list is working fine.

**Comment by Belanchuk** [comment]
There: https://github.com/darklow/django-suit/issues/303 used Select2Widget.
How can I use ModelSelect2Widget?

**Comment by Belanchuk** [comment]
Is my question clear?

**Comment by codingjoe** [comment]
Hi @Belanchuk to be honest, I don't know enough about `django-suit` to make this work. The widgets are made for form. If suits uses forms to generate the list view, it should be possible.
Sorry.

**Comment by deepakvashist** [comment]
Hi @codingjoe, i'm trying to do: https://github.com/deepakvashist/django-admin-select2

**Comment by codingjoe** [comment]
@deepakvashist thanks for the effort, but django-select2 is making it way into Django itself. It still not merged yet. But it should end up in Django 2.
