### ISSUE TITLE
install in pycharm failed

### ISSUE THREAD

**Issue by petitchamp** [applegrew/django-select2#290]
When I try to install Django-Select2-Py3 in pycharm using Settings panel, following errors occured.

> 
> Collecting Django-Select2-Py3
>   Downloading Django-Select2-Py3-4.2.1.tar.gz (90kB)
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\KE\AppData\Local\Temp\pycharm-packaging\Django-Select2-Py3\setup.py", line 166, in <module>
>         long_description=read("README.md").decode('utf-8'),
>     AttributeError: 'str' object has no attribute 'decode'
>

**Comment by codingjoe** [comment]
That's an old version. Please use Version 5 which is both python 3 and 2 compatible.
