### ISSUE TITLE
Document Django Support (>=1.8)

### ISSUE THREAD

**Issue by DylanYoung** [applegrew/django-select2#291]
Since version 5, django-select2 only supports Django >= version 1.8.  I was unable to find this information in the documentation. If it exists, please point it out; otherwise, this issue should be reopened and fixed.

**Comment by codingjoe** [comment]
We officially support only supported Django versions, so currently: 1.11, 1.10 and 1.8 LTS
You can try older versions, but that would be I'll advice, since those Django versions no longer receive security patches.

**Comment by DylanYoung** [comment]
Yes I know. If you read the issue I submitted, you will see that; however, this is undocumented. This is a documentation issue, not an issue with your code.

**Comment by codingjoe** [comment]
@DylanYoung , sorry for me being so fast to close this ticket. You are right, this should be reflected in the documentation. Please feel free to add it!

**Comment by codingjoe** [comment]
The PyPi classifiers are now set correctly. That should be documentation enough.
