### ISSUE TITLE
How to pass language to select2 widgets?

### ISSUE THREAD

**Issue by koledennix** [applegrew/django-select2#292]

**Comment by codingjoe** [comment]
That is a very good question, but at the wrong place. I didn't see any option to set the language explicitly in the Select2 documentation. Maybe there is a way, you should ask around in their community.

**Comment by kevin-brown** [comment]
Note that you can specify the language using the Django widget attributes as `data-language` or `lang`.

https://select2.github.io/examples.html#language

**Comment by ibnbay99** [comment]
U can use on forms.py, here's my example:

class MyWidget(ModelSelect2Widget):
    model = User
    queryset = User.objects.all()
    search_fields = [
        'email__icontains',
    ]

On other ModelsForm:
'comp_pic': MyWidget(attrs={'data-placeholder': 'Select User Pic', 'data-theme': 'bootstrap', 'data-dir': 'rtl'}),
