### ISSUE TITLE
Option to disable form.media

### ISSUE THREAD

**Issue by lampslave** [applegrew/django-select2#298]
For those who want to add static files into templates manually.

**Comment by tisdall** [comment]
I'm not sure exactly what you're trying to do, but you can always just not include the `{{ form.media}}` in your template and then add things manually.  Alternatively, you can inherit from the widget you want to use and overwrite the `media` property to include the elements you want.  Or change the settings to point to the select2 files you want to use.

**Comment by lampslave** [comment]
I want [this](https://github.com/hovel/django-select2/commit/4ef257012f8db2ada36565de67076c53bc914993), but not so radically :)
`{{ form.media }}` can contain another static files which are not included in template.

**Comment by tisdall** [comment]
Right, so why not just use the inherit option I mentioned:
```
class YourWidget(HeavySelect2MultipleWidget):  # inherit from whichever widget you're using
    def _get_media(self):
        return forms.Media()
    media = property(_get_media)
```

**Comment by codingjoe** [comment]
Hi @lampslave 
As pointed out by @tisdall have to add the `form.media` to your template explicitly in the first place.
You can also decide not to do that. In your particular case, I would advice you to just inherit form the widget and to overwrite `Widget.Media`.
I hope that's good enough. Adding a setting for an edge case is something I'd like to avoid.
