### ISSUE TITLE
Issues when spaces are in tags

### ISSUE THREAD

**Issue by Jakobovski** [applegrew/django-select2#301]
Let's say I have two tags ['apples', 'apples organic']  when I choose `apples organic` as a tag and then start hitting backspace it changes the tag to `apples` and has " organi" as text.

See screenshot: https://drive.google.com/open?id=0ByXDTaNWtzH5eEhTZTdTQ3Z4Y1k

This seems to be an issue with the django implementation and not Select2. Here we see its working fine with vanilla select2:  http://jsfiddle.net/v3h4303L/

Is there some type of configuration i am missing, or is this a bug?

Thanks

**Comment by codingjoe** [comment]
Hi @Jakobovski 

That is a only a matter of configuration. The magic happens in [this line](https://github.com/applegrew/django-select2/blob/master/django_select2/forms.py#L120).

You can change this by passing a different value for `data-token-separators`.

```python
MySelect2Widget(attrs={'data-token-separators': '[',']'})
```

Cheers
-Joe
