### ISSUE TITLE
auto.json endpoint security

### ISSUE THREAD

**Issue by yuvadm** [applegrew/django-select2#302]
The documentation doesn't mention how secure the auto.json endpoint is. Can any clarifications be made on how vulnerable this endpoint is to unauthenticated / unauthorized users?

**Comment by codingjoe** [comment]
By default there is not authentication, we only use the signing to verify that the user has permission to execute the query. However you can have inherit from the default endpoint and add a login and permissions check.

**Comment by yuvadm** [comment]
@codingjoe what would be the best way to inherit the endpoint and override it with authentication checks?

**Comment by yuvadm** [comment]
Here's what I ended up doing as a quick fix, instead of including the default URLs just copy it over and wrap it with `login_required`:

```diff
-        url(r'^select2/', include('django_select2.urls')),
+        url(r"^select2/fields/auto.json$", login_required(AutoResponseView.as_view()), name="django_select2-json"),
```

**Comment by codingjoe** [comment]
sure that works too. Since Django 1.9 there is the `LoginRequiredMixin` that does a similar job.
