### ISSUE TITLE
Error when running testapp

### ISSUE THREAD

**Issue by MichaelViveros** [applegrew/django-select2#306]
I get the following error when I try to run the code for testapp:
`ImportError: No module named 'tests'`

I'm fairly new to Django and tried messing around with the `settings.py` and the imports in `forms.py` but I couldn't get it working.

In the readme it says "This application is used to manually test the functionalities of this package." so maybe you're not supposed to run testapp since it's just used for tests. But it would help me a lot if I could run that code and see what it looks like.

![image](https://cloud.githubusercontent.com/assets/8866443/21591819/a05e1e86-d0d5-11e6-909b-3a422d1f1a9c.png)

**Comment by codingjoe** [comment]
This should do the trick.
```shell
PYTHONPATH=../.. python3 manage.py runserver
```

**Comment by kakulukia** [comment]
Well, thx for clearing this up, but even now that the testapp is running there is no index page showing off the examples .. 
A Readme inside the testapp would be very welcome!

**Comment by codingjoe** [comment]
@kakulukia why do you want to run the test app? It's for unit tests not meant as an example. I'd rather update the documentation, if things are not clear enough.

**Comment by kakulukia** [comment]
because usually those kind of apps are great to learn the code .. and because sadly the documentation is lacking an explanation of create_value, so i wanted to what im doing wrong .. only to find out that there is no code calling that function:
https://github.com/applegrew/django-select2/search?utf8=%E2%9C%93&q=create_value&type=

And besides there are several errors in the value_from_datadict method shown in the readme for ModelSelect2TagWidget - instead it should be:
```
    def value_from_datadict(self, data, files, name):
        values = super().value_from_datadict(self, data, files, name)
        qs = self.queryset.filter(**{'pk__in': [i for i in values if isinstance( i, int )]})
        pks = set(force_text(o.pk) for o in qs)
        cleaned_values = []
        for val in values:
            if force_text(val) not in pks:
                val = queryset.create(title=val).pk
            cleaned_values.append(val)
        return cleaned_values
```

**Comment by codingjoe** [comment]
@kakulukia yes, the custom integrations are poorly documented. It would very much welcome PRs to improve them. A good documentation is always key.
