### ISSUE TITLE
Ideas for improvement 

### ISSUE THREAD

**Issue by agronick** [applegrew/django-select2#308]
I posted some things I had noticed in #303. Here are a few simple things that can be done to make this more secure. I'd be happy to help but only if my effort is wanted.

Here are the ideas I have.

**Store cache entries for less time**
I use my cache for a lot of things. Some things that I want to persist for days. I don't envision anyone staying on a form for days. Expiring the cache entries after 24 hours should be enough. It should probably be configurable. I think most people would be fine with 8 hours. The select boxes could be populated with text that says "Reload the page - session expired." The cache key should be deleted when the form is submitted as well. django-select2 is the only thing in my cache that isn't putting an expiration date on it's entries.

**Validate ModelSelect2Mixin**
This should be easy. On the format_value method on the widget, check the value the user supplied with 
```python
def format_value(value):
    try:
        if self.queryset:
            return self.queryset.get(pk=value)
        else:
            return self.model.get(pk=value)
    except ObjectDoesNotExist:
        return False
```
Now the ModelSelect2 fields return models, while validating that the user input is valid.

**Make a Heavy Select2 View For Non-Model Sources**
There should be a view that developers could extend with a method like get_options() which returns a list of key, value entries. They keys get written to the cache while being used to populate the view. When the form is submitted, this widget validates that the returned value is the same as what was listed in a get_options() call.

**Comment by codingjoe** [comment]
Hello again!

Let me start of by saying that all form of contribution, be it code, comment, documentation and certainly discussion is most welcome. It fuels a great project, so thank you and yes, your help is wanted.

I will try to get into your questions one by one.

#### 1. Cache

[As suggested in the documentation](http://django-select2.readthedocs.io/en/latest/django_select2.html#module-django_select2.cache) you really should setup your own cache for select2. This will also allow you to set a different default cache timeout or any other eviction policy for that matter.

I would be possible to send the `field_id` using a hidden field and clear it form the cache, if a form is actually submitted. I however it will not allow one to setup a proper eviction policy.

I think a good point to start here, is to look at the `ClearableFileInput` from Django. The delete checkbox is also an additional input to the main one. A pull-request would be greatly appreciated, I just haven't had the need yet myself.

#### 2. Validation

The `value` isn't user input, I don't see the need for validation here. Furthermore, validation is handled in Forms and Fields, not Widgets.

I think I'm missing a point here, please elaborate a bit more.

#### 3. None-Model-View

I don't know if there is a use case, that is common enough or a view that can be abstract enough to be the base for all purposes one might have. I think there is great room for improvement here when it comes to documentation. I would love to see you write some example here. Documentation written by another person is always so much better.

**Comment by agronick** [comment]
I rather not have the overhead of running another instance of memcached and
I rather not have one cache full while the other one is half empty. Putting
getattr(settings, 'SELECT2_CACHE_TIMEOUT', 60*60*24) on the cache.set line
wouldn't be a lot of work and it would give people the option of limiting
how long this stuff stays. I want my compiled static files and my sitetree
to stay in the cache for months. I don't want the select2 stuff to but I
can't configure it.

For the validation, maybe that wasn't the right method. There must be some
method to process the input. Maybe value_from_datadict? I know validation
isn't done in the widgets. But you have the queryset from the cache so it
wouldn't be hard to validate it in the value_from_datadict method. That's
super simple validation to make sure the user didn't send in garbage and
lets the developer work with a model as well. It would make it work like a
ModelChoiceField or a ModelMultipleChoiceField. (Again I know widgets not
fields.) But if the user selects a model it would be convenient to get a
model in form.cleaned_data.

The use case for the no model view would be making sure the submitted
options was indeed one of the choices. We have an internal application and
the select2 loads a list of folders. If the values were sent to the cache
the user couldn't send ../../../../etc/whatever.

Just some ideas. If you think any of ideas are worth implementing I would
do it the next time I get a free chance at work. Things are pretty busy
currently though.

**Comment by codingjoe** [comment]
@agronick the formatting is fine, thanks :)

#### 1. Cache

I don't know about memcache right now, but at least when it comes to Redis, you don't need to have a separate machine. A Redis instance supports multiple databases.
Please consider that adding this setting and explicitly setting the timeout would be a breaking change. Feel free to come up with a solution, but I fear it would be a lot effort and might add complexity for a problem that is already solvable.

#### 2. Validation

There already is protection again "gabage" user input. The `field_id` is signed by the server to project you from request forgery. So all features this library adds are save, validation beyond this point should happen on field or model level. If you have any security concerns, please write to django-select2@johanneshoppe.com and do NOT discuss them publicly on GitHub.

#### 3. None-Model-View

Validation if the value is inside the choices sound great! I'd love to see you come up with a solution. Developers would greatly benefit from this, especially to protect them from accidentally developing a security whole.

**Comment by agronick** [comment]
The thing I need most would be a way to set the cache expiration time. I have other things I want to cache for up to 30 days and I have lots of select2 entries waiting 30 days to expire. You could put a getattr(settings, 'SELECT2_CACHE_TIMEOUT') on the cache.set() and it would only change things for people that put it in their settings. For now, I'm going to put it in a file based cache but it will definitely slow down my pages.

**Comment by agronick** [comment]
For anyone else who wants shorted cache times, it seems like this works:
in settings.py
SELECT2_CACHE_BACKEND = 'select2'
CACHES[SELECT2_CACHE_BACKEND] = CACHES['default'].copy()
CACHES[SELECT2_CACHE_BACKEND]['timeout'] = 60*60*5

**Comment by codingjoe** [comment]
Closed: **This issue has been inactive for an extended period of time. Please reopen the issue if it is still relevant.**
