### ISSUE TITLE
This app uninstalls django 1.10 and installs Django 1.9.6

### ISSUE THREAD

**Issue by jangeador** [applegrew/django-select2#310]
I installed this app and it uninstalled my django 1.10.5 while installing django 1.9.6 please update the requirements.

**Comment by kevin-brown** [comment]
Are you sure? I don't see `Django` specified in the requirements, and it's unusual for Pip to downgrade a requirement (usually it says they are conflicting).

Do you still have the logs for when you did the installation?

**Comment by jangeador** [comment]
I am not sure how this happened, but I ran the command `pip install django_select2` as stated in the readme, and this happened. Then as I was reading through the issues, I saw that you suggested to someone to install `pip install Django-Select2` and that install did not have any issues. Do they point to different installers?

**Comment by kevin-brown** [comment]
> Do they point to different installers?

They should point to the same package.

https://pypi.python.org/pypi/Django-Select2
https://pypi.python.org/pypi/django_select2

**Comment by jangeador** [comment]
Cannot reproduce the issue, so it must have been something else. Thank you for your quick response. I will close this issue now. BTW, congratulations on an awesome app.
