### ISSUE TITLE
How to customize options template?

### ISSUE THREAD

**Issue by xelhark** [applegrew/django-select2#331]
I'm trying to customize the options template somehow. The docs are really foggy in this area so I don't really know what to do.

I tried calling my custom init of select2

```
  $('.django-select2').djangoSelect2({
    templateResult: function (data) {
      return "Foo Bar"
    }
  });
```

I got it working, but I had to modify the django-select2 script in order to avoid initializing select2, otherwise my custom init is overridden, so this is not a good option.

I also tried overriding `render_option` in my Widget to no avail.

What's a good strategy?

**Comment by codingjoe** [comment]
Hi you have to overwrite change the class attribute, to avoid initialisation from the default script:

```python
class MyWidget(ModelSelect2Widget):
    def build_attrs(self, extra_attrs=None, **kwargs):
        """Set select2's AJAX attributes."""
        attrs = super().build_attrs(extra_attrs=extra_attrs, **kwargs)
        attrs['class'] = attrs['class'].replace('django-select2', 'my-select2-widget', 1)
        return attrs
```

I agree that this could be easier. Maybe you could create a Pull-request, where the `django-select2` html `class` is a class attribute. This way it could be modified like that:

```python
class MyWidget(ModelSelect2Widget):
    select2_input_class = 'my-select2-widget'
```

**Comment by msi2** [comment]
@codingjoe you are talking about the general class of the select2 right ?

I think the need here (and definitely mine) would be to customize the rendering of the options inside the select2 (adding an image, like a flag or a profile picture and/or other data in addition to the common __str__ of the model)

**Comment by codingjoe** [comment]
@msi2 if that is the case, you should have a look at the select2 project. I can not help you with that.

**Comment by xelhark** [comment]
@msi2 actually that was my initial need. After a lot of work I managed to get it to work though. Basically I created my own views / widgets and even the js plugin 🔧

Honestly, the code I wrote is probably not good enough to be published on a custom package, but maybe I can give you some snippets to work on.

**Comment by codingjoe** [comment]
@xelhark I still don't know what you where trying to do.
If you want to change the Django output, you can change the option template since version 1.11 or overwrite `render_option` in earlier versions.
If it is about changing the rendered select2 input field, you can do that using:
```javascript
$(selector).select2({
    templateResult: function(data) {return "<some html/>"},
    templateSelection: function(data) {return "<some html/>"},
});
```
