### ISSUE TITLE
select2, it is not at all loading the options in  select tag

### ISSUE THREAD

**Issue by mprakasht** [applegrew/django-select2#346]
"GET /select2/fields/auto.json?term=&field_id=MTM5Njg5NDYzNzA3NjAw%3A1d0MKp%3AbNSiU1dZH44XFNI45KvVvdI3-rY HTTP/1.1"  giving 404 error why ?

**Comment by codingjoe** [comment]
I don't know, where is it raising the 404? If you turn the debug mode on, Django will tell you where it raises the 404.

**Comment by belongwqz** [comment]
Maybe it's the cache timeout expired.

**Comment by codingjoe** [comment]
Since there was no response, I will close this thread.

**Comment by thornycrackers** [comment]
I also ran into this issue and I think I can help aid in the correct direction. The issue is in the lines of code that grab from the cache:

```
       else:
           cache_key = '%s%s' % (settings.SELECT2_CACHE_PREFIX, key)
           widget_dict = cache.get(cache_key)
           if widget_dict is None:
               raise Http404('field_id not found')
```

And the issue was when I was using the dummy cache

```
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}
```

After I switched to file based caching instead I didn't get and 404's anymore. My guess is OP had a similar problem.

**Comment by bastienlaunay** [comment]
Hello,

I have exactly the same problem (`404`, `field_id not found`) but **i d'ont want** to use the file based cache.
I use redis for cache, all my settings are OK, it worked before... 
I followed this : [http://django-select2.readthedocs.io/en/latest/django_select2.html#django_select2.forms.Select2TagWidget](http://django-select2.readthedocs.io/en/latest/django_select2.html#django_select2.forms.Select2TagWidget)
