### ISSUE TITLE
AutoModelSelect2MultipleField Widgets are misaligned and not displaying the field's label

### ISSUE THREAD

**Issue by deepthivalisetti** [applegrew/django-select2#348]
Hi applegrew, 
Can you please help me with the below issue? 
It is same as https://github.com/applegrew/django-select2/issues/121
But the issue is with AutoModelSelect2MultipleField.
Widgets are misaligned and not displaying the field's label.

Thanks in advance !!!
Below are the details

Django_select2: 4.2.2
Django: 1.8

**choices.py:**
class CustomersChoices(AutoModelSelect2MultipleField):
    queryset = Customer.objects
    search_fields = ('customer_name__istartswith',
                              'description__istartswith',
                              'user__first_name__istartswith',
                              'user__last_name__istartswith',
                             )
**forms.py:**
class CSDashboardFilterForm(forms.Form):
    customers = CustomersChoices(label='Customer(s)', required=False)
     is_expedite = forms.BooleanField(required=False, label='Is Expedite?')
     status = Select2ChoiceField(choices=CHOICES, required=False)
     facility_plant = ModelSelect2Field(queryset=Plant.objects, initial='----', required=False)
 

![image](https://cloud.githubusercontent.com/assets/17268585/25163895/1637b5cc-24eb-11e7-8369-081e753008d2.png)

**Comment by codingjoe** [comment]
Version 4.2.2 is no longer supported, sorry.
