### ISSUE TITLE
After the cache expire time, the drop-down option list will lost

### ISSUE THREAD

**Issue by belongwqz** [applegrew/django-select2#349]
Use with heavy mode. After the cache expire time, the drop-down option list will lost, and you must refresh the page to fix it. Well, how to auto update the cache when after the cache expire time?
Code example:
```
class MyForm(forms.Form):
    source_entity = forms.ModelMultipleChoiceField(
        widget=ModelSelect2MultipleWidget(model=MyModel, search_fields=['name__icontains']),
        queryset=MyModel.objects.all()
    )
```

**Comment by codingjoe** [comment]
There is no way to auto update at least not to my knowledge. I'd advice you to setup a separate cache server and to properly set the timeout.
