### ISSUE TITLE
Is it possible to create editable select field?!

### ISSUE THREAD

**Issue by NogerbekNurzhan** [applegrew/django-select2#352]
Hello! I want to know, is it possible to create editable select field as in the picture below with the help of your application? I am little bit comfused.

![2017-04-30 00 00 35](https://cloud.githubusercontent.com/assets/8999232/25564636/5f57919a-2dd9-11e7-95a0-7a8ee1ba610b.png)

**Comment by codingjoe** [comment]
@NogerbekNurzhan what do you mean by editable? Anyways, what I see on your screen shot is possible with this library.

**Comment by NogerbekNurzhan** [comment]
I mean that user can select some value from the list and then edit  that value as he want. Not like in ChoiseField where user can select value but cant edit it.

**Comment by codingjoe** [comment]
You can not edit, as in update the value, but you can insert a new one. The [tag widget](http://django-select2.readthedocs.io/en/latest/django_select2.html#django_select2.forms.ModelSelect2TagWidget) does that.
