### ISSUE TITLE
How create correctly Multiple Select Box?

### ISSUE THREAD

**Issue by NogerbekNurzhan** [applegrew/django-select2#356]
Hello! First of all thanks for this project! I am tring to use your library and create **Multiple Select Box** field as in the picture below. I am little bit comfused. Can you show me how create such field? I tried next code but it return me simple select multiple widget. It seems like I forget to add something. Can you show me how create such field correctly?

**django-select-2 version: 5.1.0
JQuery version: 3.1.1**

![mkec6](https://cloud.githubusercontent.com/assets/8999232/25953996/cbf66262-3686-11e7-9f6e-a1974ec150b0.gif)

**forms.py:**
```
class ProductForm(forms.ModelForm):
    company = forms.ModelMultipleChoiceField(widgets=Select2MultipleWidget(), queryset=Company.objects.none())

    class Meta:
        model = Product
        fields = ('company ',)

    def __init__(self, all_companies, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['company'].queryset = all_companies
```

**template:**
```
{% block style %}
    {{ product_form.media.css }}
{% endblock %}

{% load widget_tweaks %}

<form method="post" action="">
    {% csrf_token %}
    <div class="modal-body">
        {% for field in product_form %}
            <div class="form-group{% if field.errors %} has-danger{% endif %}">
                <label class="form-control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>

                {% render_field field class="form-control" %}

                {% for error in field.errors %}
                    <div class="form-control-feedback">{{ error }}</div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Create</button>
    </div>
</form>

{% block script %}
    {{ product_form.media.js }}
    <script>
        $('#id_company').djangoSelect2();
    </script>
{% endblock %}
```

**JS:**
```
$(function () {
    var loadForm = function () {
        var btn = $(this);
        $.ajax({
            url: btn.attr("data-url"),
            type: 'get',
            dataType: 'json',
            beforeSend: function () {
                $("#modal").modal("show");
            },
            success: function (data) {
                $("#modal .modal-content").html(data.html_product_form);
            }
        });
    };

    $("#product-add-button").click(loadForm);
});
```

**Comment by codingjoe** [comment]
What a well written ticket, thanks!

Take a look at the [ModelSelect2MultipleWidget](http://django-select2.readthedocs.io/en/latest/django_select2.html#django_select2.forms.ModelSelect2MultipleWidget). That's the one you are looking for. Let me know if you need more help.
Cheers
-Joe

**Comment by NogerbekNurzhan** [comment]
@codingjoe Hello! Is there any example of ModelSelect2MultipleWidget? I am little bit comfused with this documentation. Can you show me how my form must looks like pls?

**Comment by codingjoe** [comment]
I'm on my phone right now, but just change the meta.widget to the right one. Also don't define the field, since your are already using a model form. The init method should remain as is.

**Comment by codingjoe** [comment]
Let me know if that works.

**Comment by NogerbekNurzhan** [comment]
I forget to say that my form inside modal window and I load form by AJAX. I did an experiment and add form outside of modal window. I notice that outside Select2MultipleWidget works. My form must be inside modal so how to fix this problem now? Do you have any ideas? I add js/ajax code which load form to post. Check it pls.

**Comment by codingjoe** [comment]
Ok, that is important. You will need to invoice select2 again after the AJAX request is finished an the DOM changed. Please see: http://django-select2.readthedocs.io/en/latest/django_select2.html#javascript

**Comment by NogerbekNurzhan** [comment]
@codingjoe I steal dont understand how to fix this problem. PLEASE HELP! Can you show me pls how to fix this poblem? I put `$('#id_company').djangoSelect2({multiple: true});` in my AJAX code? Look _beforeSend_ in ajax code pls. I notice that in html the places where I declare `{{ product_form.media.js }}` and {{ product_form.media.css }} are empty. Also instead of them I tried to put this but anyway there is no Select2MultipleWidget. Can you show me what exactly I need to change?

```
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css">
<script src="{% static 'django_select2/django_select2.js' %}"></script>
```

**Comment by NogerbekNurzhan** [comment]
Finally I found solution. Instead of `{{ product_form.media.js }}` and `{{ product_form.media.css }}` I use this cause I load my form by AJAX:

```
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css">
<script src="{% static 'django_select2/django_select2.js' %}"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
```

I hope in the future you will give an opportunity to add static files to users who use AJAX. Bye and good luck! =)

**Comment by NogerbekNurzhan** [comment]
Can I ask one more question?! How affect to width of Select2MultipleWidget and why this widget not under label?

![2017-05-13 14 13 39](https://cloud.githubusercontent.com/assets/8999232/26023825/ba1e8b76-37e6-11e7-9bb1-a0c37e2eb865.png)

**Comment by codingjoe** [comment]
@NogerbekNurzhan well that's a Django thing. There isn't much I can do about this :/

**Comment by NogerbekNurzhan** [comment]
@codingjoe Thank you for this project anyway! Its awesome! Can I ask you one more question? What kind of widget from django-select-2 is better to use for ModelChoiseField?

**Comment by NogerbekNurzhan** [comment]
@codingjoe Thank you for this project! Its awesome!

**Comment by primate-rick** [comment]
> Let me know if that works.





https://adnanunaccustomed.github.io/hBamseJJNAWG5FrERErM9HYRleEYFK7MTrUfFPFavcO5k2bvo_53aD4FWwRNuAuhI9DvPC_XYKI/
