### ISSUE TITLE
InvalidTemplateLibrary: cannot import name __BOOTSTRAP

### ISSUE THREAD

**Issue by pbaranay** [applegrew/django-select2#357]
Hi there,

I'm a member of a Django project that uses `django-select2`. When running our test suite locally, a number of tests failed with the error:

> InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'django_select2.templatetags.django_select2_tags': cannot import name __BOOTSTRAP

Ultimately I was able to trace this to the first few lines of `django_select2/media.py `:

```
      2 from django.templatetags.static import static
      3 
----> 4 from . import __BOOTSTRAP as BOOTSTRAP
      5 
      6 # Local version of DEBUG
```

I was able to solve the problem by running `touch __BOOTSTRAP.py` so that the import succeeds; however, that doesn't seem like a viable long-term solution. How could this be addressed? Is something with my installation of `django-select2` misconfigured? I am using version 5.10.0.

**Comment by codingjoe** [comment]
That seems to be very outdated, which version are you using?

**Comment by pbaranay** [comment]
Hi @codingjoe, 

I'm using version 5.10.0, which appears to be the most recent version. Is it possible that my package manager never deleted the `media.py` file when I upgraded to a newer version?

**Comment by codingjoe** [comment]
Could be, because the code you are showing is really old. We no longer support bootstrap out of the box since version 5.
