### ISSUE TITLE
ModelMultipleChoiceField with Tree Widget?

### ISSUE THREAD

**Issue by NogerbekNurzhan** [applegrew/django-select2#361]
Hello! Thank you for this project! I have question. Is it possible to create Tree with several nested levels with the help of django-select-2 as in the pictures below?

![example](https://cloud.githubusercontent.com/assets/8999232/26089427/7328fc98-3a1f-11e7-89c1-7579b9a516d9.png)

Lets say I want such nesting: (User can choise functions)
![default](https://cloud.githubusercontent.com/assets/8999232/26089490/1bcbec3e-3a20-11e7-95d7-95e42ba0da7d.jpg)

**models.py:**
```
class Group(models.Model):
    name = models.CharField(_('Name'), max_length=250)

class Task(models.Model):
    name = models.CharField(_('Name'), max_length=250)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)

class Function(models.Model):
     name = models.CharField(_('Name'), max_length=250)
     task = models.ForeignKey(Task, on_delete=models.CASCADE)

class Program(models.Model):
    name = models.CharField(_('Name'), max_length=250)
    function = models.ManyToManyField("Function")
```

**forms.py:**
```
class ProgramForm(forms.ModelForm):
    function = forms.ModelMultipleChoiceField(widget=Select2MultipleWidget(), queryset=Group.objects.none())

    class Meta:
        model = Program
        fields = ('function',)

    def __init__(self, all_groups, *args, **kwargs):
        super(ProgramForm, self).__init__(*args, **kwargs)
        self.fields['function'].queryset = all_groups
```

**Comment by codingjoe** [comment]
Hi @NogerbekNurzhan yes, that should be possible, I never tried it tho.
1. Get it working without select2 ;) Select inputs support grouping and [so does Django](https://docs.djangoproject.com/en/1.11/ref/models/fields/#choices).
2. Pop in the select2 widget. Not the model or heavy once, those will not work.

Let me know if you are experiencing any issues.
Cheers
-Joe

**Comment by dzhuang** [comment]
I noticed 'optgroups' was introduced in 5840622794bc282405370b02dc504bec4304c166 (also for ``ModelSelect2Mixin``) so as to be compatible with Django 1.11, will that work?

**Comment by codingjoe** [comment]
@dzhuang Django 1.11 you mean? Yes, it should be working just fine :)
