### ISSUE TITLE
Select a valid choice error with ModelSelect2MultipleWidget… 

### ISSUE THREAD

**Issue by kierun** [applegrew/django-select2#363]
I am a little confused about how to test a form using `ModelSelect2MultipleWidget`. The form looks like thus:

```
class TestForm(forms.Form):
    users = forms.ModelChoiceField(
        widget=ModelSelect2MultipleWidget(
            model=User,
            queryset=User.objects.all(),
            search_fields=["username__icontains", ],
            attrs={'style': 'min-width:800px'},
        ),
        queryset=User.objects.all(),
        label="Select multiple users",
    )
```

and the test like so:

```
    def test_code_add_form(self):
        jdoe = User.objects.create_user(username='JohnDoe',
                                        first_name="John",
                                        last_name="Doe",
                                        email='john.doe@example.com',
                                        password='s3kr3t')
        data = {'users': (jdoe.pk, )}
        form = TestForm(data=data)
        self.assertTrue(form.is_valid(), form.errors)
```

In conjuncture, they gives me:

`AssertionError: False is not true : <ul class="errorlist"><li>users<ul class="errorlist"><li>Select a valid choice. That choice is not one of the available choices.</li></ul></li></ul>  `

*What am I doing wrong?*

**Comment by kierun** [comment]
… `widget=ModelSelect2MultipleWidget(…)` would make more sense, wouldn't it?

**Comment by codingjoe** [comment]
Hi @kierun!
I think I need a little more information to answer you question correctly.
Is TestForm a `webtest` thing? If so, that can be an issue, because webtest only allows for options in the DOM tree. The whole purpose of the library is to not have them in the DOM tree but to fetch options on demand for better performance.

Cheers
-joe

**Comment by kierun** [comment]
> Is TestForm a webtest thing? If so, that can be an issue, because webtest only allows for options in the DOM tree. The whole purpose of the library is to not have them in the DOM tree but to fetch options on demand for better performance.

No, it is a unit test `django.test.TestCase`. The code pasted was a toy to re-create the problem which went away when I replaced `forms.ModelChoiceField` with `forms.ModelMultipleChoiceField`… And I just noticed that I messed up the answer above. Edited now.

☹ No more coding for me before I get a good night's sleep!

**Comment by codingjoe** [comment]
Oh, you passed a tuple. It should just be the PK, eg:
```python
data = {'users': jdoe.pk}
```

**Comment by kierun** [comment]
@codingjoe I wanted a multiple select. Thus, the test *is correct*. It should be a tuple. However, the widget was correct but the form was set up as a `ModelChoiceField` not a `ModelMultipleChoiceField`. Hope that clears any confusion. ☺

**Comment by codingjoe** [comment]
Ok, does it work with the `ModelMultipleChoiceField`? Because to be honest, I don't see anything incorrect besides that. It should work. #famousLastWords ;)

**Comment by kierun** [comment]
`ModelMultipleChoiceField` does indeed make it work just as expected. ☺
