### ISSUE TITLE
dependent fields do not work when the form is an inline admin form

### ISSUE THREAD

**Issue by stevemartingale** [applegrew/django-select2#380]
I found a problem with dependent_fields when using django-select2 as an inline admin form. The result is that the select options are never updated to filter based on the dependent field.
I created #379 to resolve this

**Comment by stevemartingale** [comment]
I have created a PR to fix this [PR-379](https://github.com/applegrew/django-select2/pull/379)

**Comment by gwsampso** [comment]
is this fixed? i'm having difficulty populating dependant fields in django-admin. To be honest I can get the select to work at all in admin... thanks

**Comment by codingjoe** [comment]
@gwsampso I believe this should be fixed. Besides, I would recommend to use autocomplete fields in the Django admin.
