### ISSUE TITLE
Extend djangoSelect2 in js won't work

### ISSUE THREAD

**Issue by ktshen** [applegrew/django-select2#382]
I am trying to adding own settings to djangoSelect2 function in js.
I create a new js file and include in my own inherited widget's media js, like this
```
# ajax-select2.js
;(function ($) {
  $(function () {
    $('.django-select2').djangoSelect2({
        placeholder: "Type to search",
    });
  });
}(this.jQuery));

# forms.py
class AjaxSelect2Widget(ModelSelect2Widget):
    class Media:
        js = ["js/ajax-select2.js"]
```
However, my widget won't work.(It doesn't show the placeholder.)
Need some help, thank you.

**Comment by codingjoe** [comment]
Hi @ktshen,

this is a very good question.

Did you know, that form `Media` on both forms and widgets inherits from super classes. Therefore the original script will be still there unless you do:

```python
class Media:
    extend = False
    js = ['path/to/my/script']
```

That being said, there are better ways to this. I recommend only adding your own JS script, if you want add functions as options, eg. if you want to change the way select2 renders or parses search results. In all other cases i would just use `data-` attributes.

```python
class MyForm(froms.Form):
    myfield = forms.ChoiceField(
        widget=Select2Widget(attrs={'data-placeholder', 'Type to search'})
    )
```

If you really need to change your JS script, make sure to use a different class name:

```python
MyWidget(Select2Widget):
    def build_attrs(*args, **kwargs):
        attrs = super().build_attrs(*args, **kwargs)
        attrs['class'] = 'my_class' 
        return attrs
```

I hope that helps you. Let me know if you have any questions :)

**Comment by ktshen** [comment]
Thank you so much @codingjoe, 
I turned out to build my own select2 widget.
However, I still have a question that confuses me a lot. Since I like djangoSelect2 original js settings, so I would like to "extend" it. I thought I could simply pass my own option to `$.extend({},options)` 
 (in this case, option is `{"placeholder": "Type to search.."} `), why isn't it effective?

**Comment by codingjoe** [comment]
HI @ktshen i think it was, but the widget was already initialised, therefore you script didn't have any effect. But good, if you found a way :)
Let me know if there are places where I can improve the documentation.
