### ISSUE TITLE
Document breaking changes from render_options to optgroups

### ISSUE THREAD

**Issue by yuvadm** [applegrew/django-select2#384]
Django 1.11 support broke some custom widgets that used `render_options()` to render existing data into widgets. Would it be possible to document how such widgets should use the updated `optgroups()` method?

**Comment by yuvadm** [comment]
More specifically, I'm looking for a snippet that renders an `ArrayField` and also shows the existing data. By just using the [example inlined in the documentation](https://github.com/applegrew/django-select2/blob/5840622794bc282405370b02dc504bec4304c166/django_select2/forms.py#L172) the existing tags never show up.

**Comment by yuvadm** [comment]
Here's what I have so far, it works for my purposes. Would love to hear feedback if it's good for the documentation:

```python
class ArrayTagWidget(Select2TagWidget):

    def build_attrs(self, *args, **kwargs):
        self.attrs.setdefault('data-token-separators', [])
        self.attrs.setdefault('data-width', '500px')
        self.attrs.setdefault('data-tags', 'true')
        return super().build_attrs(*args, **kwargs)

    def value_from_datadict(self, data, files, name):
        values = super().value_from_datadict(data, files, name)
        return ','.join(values)

    def optgroups(self, name, value, attrs=None):
        values = value[0].split(',')
        selected = {*values}
        subgroup = [self.create_option(name, v, v, selected, i) for i, v in enumerate(values)]
        return [(None, subgroup, 0)]
```

**Comment by codingjoe** [comment]
@yuvadm thx, this looks good! There is never too much documentation.
The only feedback I have, is that I would make sure to focus on what to show here. If you want to show how to extend `optgroups` you should focus on that, not throw in the extra attrs.
Cheers! Looking forward to see your PR!
-Joe

**Comment by yuvadm** [comment]
@codingjoe great, thanks for the feedback! Will send a PR shortly.
