### ISSUE TITLE
ModelSelect2MultipleWidget not using ajax?

### ISSUE THREAD

**Issue by pathway** [applegrew/django-select2#389]
- using ModelSelect2MultipleWidget in admin form, on a large child table
- field rendering, saving etc all works great
- But: thousands of M2M rows are rendered into HTML "option" tags (causing very slow loading), ajax doesnt appear to be used.

I thought ModelSelect2MultipleWidget would load options via ajax (because it derives from Heavy), but I dont see it trying to do that.  

I setup urls as per http://django-select2.readthedocs.io/en/latest/get_started.html#installation.  I dont see any evidence of JS errors (in the chrome console) or of ajax attempts.

```python
class MyModelAdminForm(ModelForm):
    class Meta:
        model = MyModel
        exclude = ['rec_creator','rec_editor_last',]
        widgets = {
            'labels': ModelSelect2MultipleWidget(model=Label, max_results = 25,search_fields=['slug__icontains','name__icontains'],),
        }
```
(Btw thanks for an awesome package!)

**Comment by codingjoe** [comment]
@pathway thanks for reaching out. Yes, you are correct. The `ModelSelect2MultipleWidget` does use AJAX to load results on demand. In fact it does not render options at all. That leads me to conclude, that there must be some tiny bug in you setup. Would you mind sharing some more code, so I can try to debug it?
Cheers
-Joe

**Comment by agfunder** [comment]
I now see my issue, it was not a problem with your package.  
All good now, please close.
Thanks again for a fantastic package!

**Comment by pathway** [comment]
I see my issue now, it was my mistake, no problem with your package, sorry for the bother.
Please close.
Thanks again for an excellent package!

**Comment by Mergpijp** [comment]
Hey @pathway what was the solution?

**Comment by pathway** [comment]
Hard to recall but it was something simple, I would expect I did not handle urls.py correctly as per docs
`url(r'^select2/', include('django_select2.urls')),`
