### ISSUE TITLE
dependent_fields does not work

### ISSUE THREAD

**Issue by viraj96** [applegrew/django-select2#403]
Hi, First of all thank you for this wonderful Django plugin. I need to create a Chained Model Multiple Select2 , and I have done everything that the documentation asked me to do regarding that. 
My form looks like this ->

```python
def __init__(self, *args, **kwargs):
		super(NationalFilter, self).__init__(*args, **kwargs)
		# self.fields['state'].choices = getNationalStates()
		# self.fields['district'].choices = getNationalDistricts()
 state = ModelChoiceField(
			queryset = State.objects.all(),
			label = u'State',
			widget = ModelSelect2MultipleWidget(
					model = State,
					search_fields = ['state__icontains']
				)
		)
	district = ModelChoiceField(
			queryset = District.objects.all(),
			label = u'District',
			widget = ModelSelect2MultipleWidget(
					model = District,
					search_fields = ['district__icontains'],
					dependent_fields = {'state' : 'state'},
					max_results = 100,
				)
		)
```
My models look like this ->
```python
    class State(models.Model):
	state = models.CharField(max_length = 1000)

	def __unicode__(self):
		return '%s' % (str(self.state))

class District(models.Model):
	state = models.ForeignKey(State)	
	district = models.CharField(max_length = 1000)

	def __unicode__(self):
		return '%s' % (str(self.district))
```
I call the form fields inside templates using `{{ nationalFilter.state }}` and `{{ nationalFilter.district }}`
If I were to retain the commented code then they would work like any unchained fields do but when I remove them it says that the 'Results could not be loaded'. I am trying to render form in the modal. The error it gives on the django command line server is the following
```
    Not Found: /select2/fields/auto.json
[09/Aug/2017 20:25:59] "GET /select2/fields/auto.json?term=&field_id=MTM5OTk5OTQ0NTg2NjQw%3A1dfSNx%3AvpS6GwaTyvV6gXAY-06cQSJyEFg HTTP/1.1" 404 1828

```
The error to me seems to be related to the url configuration. So I am adding that too here.
My main urls.py(the one created by default) looks like this  ->
```python
   urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('data_analyser.urls')),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
]

```
The other one that I created for my app looks like this ->
 ```python
   urlpatterns = [
	url(r'^main$', views.main, name = 'main'),
	url(r'^select2/', include('django_select2.urls')),
]
```

Could you guys tell If I am doing anything wrong.

**Comment by codingjoe** [comment]
Hi @viraj96 since you are getting a 404 I presume you do not have your cache setup properly.
Check out our documentation on configuring django-select2:
http://django-select2.readthedocs.io/en/latest/django_select2.html#module-django_select2.conf
Let me know if you need more help :)
-Joe

**Comment by viraj96** [comment]
@codingjoe Thank you for your quick response. I was also suspecting the same thing due to which I added  cache settings to my app. Now the problem of loading is solved but still the problem of chaining persists.
My cache settings are as follows ->
```
   CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION':'127.0.0.1:11211',
    },
    'select2': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION':'127.0.0.1:11211',
        'TIMEOUT': 60 * 60 * 24,
    },
}
SELECT2_CACHE_BACKEND = 'select2'
```
The idea is taken from one of the previous answers to an older issue. Now the new warning django command line server gives is regarding UnorderedObjectListWarning, specifically,
```
    /usr/local/lib/python2.7/dist-packages/django/core/paginator.py:112: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <QuerySet [<State: West Bengal>, <State: Uttarakhand>, <State: Uttar Pradesh>, <State: Tripura>, <State: Telangana>, <State: Tamil Nadu>, <State: Sikkim>, <State: Rajasthan>, <State: Punjab>, <State: Puducherry>, <State: Odisha>, <State: Nagaland>, <State: Mizoram>, <State: Meghalaya>, <State: Manipur>, <State: Maharashtra>, <State: Madhya Pradesh>, <State: Lakshadweep>, <State: Kerala>, <State: Karnataka>, '...(remaining elements truncated)...']>
  UnorderedObjectListWarning

```
I don't think this is in anyway related to the chaining of the field, or is it?

**Comment by codingjoe** [comment]
Hi @viraj96 you are right, the `UnorderedObjectListWarning` is not related. It just is a reminder to add some kind of sorting to your QuerySet, or a default sorting to your model.

I have a guess, your `State` widget, is a multi select. Maybe that is an issue. I don't know. Can you try changing it to single select, just to test if that works?

**Comment by viraj96** [comment]
@codingjoe Yes changing `State` from `ModelSelect2MultipleField` to `ModelSelect2Field` makes it work. But the functionality that I am looking for is that the user can select multiple states and corresponding districts must show up. Is this possible?

**Comment by codingjoe** [comment]
Hi @viraj96 

I'm afraid we don't support that out of the box, but you can totally make that work. You just need to implement your own `filter_queryset` method.
See https://github.com/applegrew/django-select2/blob/master/django_select2/forms.py#L396-L423

**Comment by cvipul** [comment]
I am afraid, its not as simple as that @codingjoe 
To allow MultiSelect field in dependent fields, we will have to override the View (and hence the urls too)
The query from the JS goes to AutoResponseView where the "get_queryset" method only sends the first value forward 

```
kwargs = {
        model_field_name: self.request.GET.get(form_field_name)
        for form_field_name, model_field_name in self.widget.dependent_fields.items()
        if form_field_name in self.request.GET and self.request.GET.get(form_field_name, '') != ''
}
return self.widget.filter_queryset(self.term, self.queryset, **kwargs)
```
self.request.GET.get(form_field_name) would need to be self.request.GET.get**list**(form_field_name)

**Comment by codingjoe** [comment]
@cvipul I noticed that too, after writing the comment, which is why I have been working on a fix. I just released version [7.0.0](https://github.com/applegrew/django-select2/releases/tag/7.0.0) which does pass the request to `filter_queryset`.

**Comment by cvipul** [comment]
Thanks @codingjoe 

I implemented the Multi-Select Dependency widget as below, if someone needs it

```
class DependentMultipleSelectWidget(ModelSelect2MultipleWidget):
    def filter_queryset(self, request, term, queryset=None, **dependent_fields):
        # The super code ignores the dependent fields with multiple values
        dependent_fields_multi_value = {}
        for form_field_name, model_field_name in self.dependent_fields.items():
            if form_field_name+"[]" in request.GET and request.GET.get(form_field_name+"[]", "") != "":
                value_list = request.GET.getlist(form_field_name+"[]")
                dependent_fields_multi_value[model_field_name] = value_list

        if queryset is None:
            queryset = self.get_queryset()
        search_fields = self.get_search_fields()
        select = Q()
        term = term.replace('\t', ' ')
        term = term.replace('\n', ' ')
        for t in [t for t in term.split(' ') if not t == '']:
            select &= reduce(lambda x, y: x | Q(**{y: t}), search_fields,
                             Q(**{search_fields[0]: t}))
        # TODO - Q doesnt support list of values, will have to add something of our own
        if dependent_fields:
            select &= Q(**dependent_fields)
        if dependent_fields_multi_value:
            queryset = queryset.filter(**dependent_fields_multi_value)

        return queryset.filter(select).distinct()
```

I am essentially using "[]" suffix at the end of request params to identify variables sending a list.
Also, had to use direct "filter" method instead of a "Q" method in the queryset.

**Comment by cvipul** [comment]
@codingjoe - why don't we just add this functionality out of the box? It seems like a very legitimate usecase, something that the documentation also fails to warn against.
Do you want me to create a pull request with the above changes to the filter_queryset method?

**Comment by codingjoe** [comment]
Hi @cvipul,

Hm… if there is a simple solution, I would prefer it work out of the box. If not, I agree that we need to improve the documentation.

Best,
Joe

**Comment by cvipul** [comment]
Depends on what we call simple.
It would be more elegant to make a change in the View itself, so that it doesn't filter out the fields with multiple values.
But the easiest would be to just change the filter_queryset method of the widget, now that we are passing the request object to it (code in my previous comment)

Till I can make the changes at the appropriate places and raise a PR, can we update the documentation?

**Comment by miguelcleon** [comment]
For the #TODO I did: 
        if dependent_fields_multi_value:
            for key,val in dependent_fields_multi_value.items():
                select &= Q(**{"%s__in" % key: val})
