### ISSUE TITLE
Sorted Multiple2Widget

### ISSUE THREAD

**Issue by NizhiSaeba** [applegrew/django-select2#410]
This is not really an issue, but i don't know where can i ask about this.

i'm working in two differents computers, all with python 3.6.1 and django 1.11.4, but i guess not same django-select2 version. i see in changelog that 5.9.0 add support to django 1.11, i did start my project with django 1.9 but now i want to update to django 1.11 but i cant achieve a thing that i was made with older versions...

the problem is:

i need a field in a model to be a `ManyToMany` but with order, i found a Django module called SordetM2M which do that. but comes with his own (and ugly) widget where list all the items (that is not nice if you have to list 300 items). 

well, i try to see where the selected options are collected, then i found that was in forms.Select as:
```python
    def render_options(self, selected_choices):
        # Normalize to strings.
        selected_choices = set(force_text(v) for v in selected_choices)
        output = []
        for option_value, option_label in self.choices:
            if isinstance(option_label, (list, tuple)):
                output.append(format_html('<optgroup label="{}">', force_text(option_value)))
                for option in option_label:
                    output.append(self.render_option(selected_choices, *option))
                output.append('</optgroup>')
            else:
                output.append(self.render_option(selected_choices, option_value, option_label))
        return '\n'.join(output)
```

i change it to:
```python
    def render_options(self, selected_choices):
        # Normalize to strings.
        selected_choices = [force_text(v) for v in selected_choices]
        output = []

        for i in selected_choices:
            for option_value, option_label in self.choices:
                if str(option_value) == i:
                    if isinstance(option_label, (list, tuple)):
                        output.append(format_html('<optgroup label="{}">', force_text(option_value)))
                        for option in option_label:
                            output.append(self.render_option(selected_choices, *option))
                        output.append('</optgroup>')
                    else:
                        output.append(self.render_option(selected_choices, option_value, option_label))

        for option_value, option_label in self.choices:
            if str(option_value) not in selected_choices:
                if isinstance(option_label, (list, tuple)):
                    output.append(format_html('<optgroup label="{}">', force_text(option_value)))
                    for option in option_label:
                        output.append(self.render_option(selected_choices, *option))
                    output.append('</optgroup>')
                else:
                    output.append(self.render_option(selected_choices, option_value, option_label))
        return '\n'.join(output)
```
to get ordered as stored (by SortedManyToMany) and then concatenated the complement... 

It worked very well

but when i upgrade to django 1.11 i found that i cant do the thing anymore, (and other issues not related to this)

Now i have all project updated to work with django 1.11, except for the fiel wich i can use as Select2MultipleWidget; i saw that inherits from Select2Mixin, forms.SelectMultiple; SelectMultiple inherits from Select as before but now don't have render_options() method. and Select2Mixin Have it but only with this code:
```python
    def render_options(self, *args, **kwargs):
        """Render options including an empty one, if the field is not required."""
        output = '<option value=""></option>' if not self.is_required and not self.allow_multiple_selected else ''
        output += super(Select2Mixin, self).render_options(*args, **kwargs)
        return output
```
i tried to override and tried to make to do strange things to catch if is really overriding, but appears is not...

![image](https://user-images.githubusercontent.com/6070970/29641300-8e0af15e-8828-11e7-8755-5bdcaf837b5d.png)

in fact PyCharm tells me that render_options() is overriding the same method on Select2Mixin. 

I guess i have to override something else but i cant find it :(

can someone help me? or there is a way to get the selected values ordered as stored and ot alphabetically?

thanks

**Comment by codingjoe** [comment]
Hi @NizhiSaeba interesting question.

There are a couple of thing you need to consider:
I can not recommend using the Model widgets in your case. They have a search field, which would ultimately break the whole idea behind the sort order, would it not?
Anyhow as long as your `QuerySet` is ordered, so would be your results/options. The only place where we use a `set` (unordered data structure) is for the selected choices. So you the initially selected options are not sorted. We could change that behavior, but would it really help you cause?

Let me know if you need further help or if I can explain things better.

Cheers
-joe

**Comment by codingjoe** [comment]
Closed: **This issue has been inactive for an extended period of time. Please reopen the issue if it is still relevant.**
