### ISSUE TITLE
django-select2 in Admin List Filter

### ISSUE THREAD

**Issue by kokhoor** [applegrew/django-select2#411]
Is it possible to have django-select2 integration in admin list filter (in the change list, not form)?

**Comment by codingjoe** [comment]
@kokhoor yes, I guess it is. I didn't look into that before. I guess the Django's admin uses a model form factory. You can pass custom widgets into that factory.

I am afraid tho, you will have to dig into Django's code a bit yourself. Let me know if you find anything or need any help integrating django-select2.

Cheers
-joe
