### ISSUE TITLE
Set widget width

### ISSUE THREAD

**Issue by frague59** [applegrew/django-select2#414]
Hi, 

Thanks for select2 integration in django, It's great !

I'ld like to set the widget width (to use it in formset). For now, the width of the widget is based on the longest word in it, and forced by an element style:
```html
<select ...>
    <option value="0">Foo</option>
    <option value="1">Bar/option>
    ...
</select>
<span class="select2 select2-container select2-container--default select2-container--focus" dir="ltr" style="width: 554px">
... [select2 machinery]
</span>
```
I've tryed to use the widget attrs parameter, but the width is set to the select (I can see it briefly), not the s2 widget. 

How can I set this width ?

Thanks for your help !

**Comment by codingjoe** [comment]
Hi @frague59 I would recommend using a custom select2 theme. Anyhow this is something that is not specific to this implementation. I suggest you check out the select2 documeantion.
https://select2.org/getting-started/basic-usage

Enjoy!
-Joe

**Comment by frague59** [comment]
Hi, 

My question is more about sending attrs to select2, because it's not about 1 field in a formset, but many fields in many formsets... and other forms.

Thanks !

**Comment by codingjoe** [comment]
All the more reason to go for a template if its about the style of the input. If it's about the form in general, sure you can pass `attrs` as you can with any widget in Django.
