### ISSUE TITLE
One search field still creates a boolean OR clause in the ORM query

### ISSUE THREAD

**Issue by nuarhu** [applegrew/django-select2#418]
While debugging my own code, I noticed that in django_select2/forms.py `ModelSelect2Mixin.filter_queryset()` creates a boolean clause with `OR` even if there is only one search_field. I have no idea whether this can impact performance or not. Just wanted to report it.

```python
>>> from django.db.models import Q
>>> from functools import reduce
>>> select = Q()
>>> term = 'test'
>>> search_fields = ['name']
>>> for t in [t for t in term.split(' ') if not t == '']:
...     select &= reduce(lambda x, y: x | Q(**{y: t}), search_fields, Q(**{search_fields[0]: t}))
... 
>>> for t in [t for t in term.split(' ') if not t == '']:
...     select &= reduce(lambda x, y: x | Q(**{y: t}), search_fields, Q(**{search_fields[0]: t}))
... 
>>> select
<Q: (AND: (OR: ('name', 'test'), ('name', 'test')))>
```

**Comment by codingjoe** [comment]
Hi @nuarhu good point. I believe most databases will optimize there queries to perform identical.
But I still think it's worth fixing. I would appreciate if you could provide a Pull-Request with a fix :)

Thanks for reporting 👍 
-Joe

**Comment by codingjoe** [comment]
Closed: **This issue has been inactive for an extended period of time. Please reopen the issue if it is still relevant.**

**Comment by cvipul** [comment]
@codingjoe - added a pull request like you asked. Have a look.
