### ISSUE TITLE
The widget doesn't work with dummycache for local development

### ISSUE THREAD

**Issue by thornycrackers** [applegrew/django-select2#429]
You can reference the issue here:

https://github.com/applegrew/django-select2/issues/346

The widget should probably have a fallback so that if someone is testing this plugin locally with dummycache that it at least works for them.

**Comment by codingjoe** [comment]
Thanks @thornycrackers you are making a good point. I would very much welcome a pull-request ;)

**Comment by codingjoe** [comment]
Closed: **This issue has been inactive for an extended period of time. Please reopen the issue if it is still relevant.**
