### ISSUE TITLE
Select 2 options not working

### ISSUE THREAD

**Issue by pidzej** [applegrew/django-select2#430]
Django 1.11 django-select2 latest
Hi i using ModelSelect2Widget:
```python
class MyWidget(ModelSelect2Widget):
	model = Customers
	#queryset = Customers.objects.all()
	max_results = 10
	search_fields = [
        'name__icontains',
    ]

class CarsForm(forms.ModelForm):
	class Meta:
		model = Cars
		fields = '__all__'
		widgets = {
			'customer': MyWidget(attrs={'data-placeholder': 'Search for MyModel values', 'data-width': '100%', 'class':'form-control m-select2'}),
        }
```
That way working but when i add script:
```javascript
<script>$('.django-select2').djangoSelect2({placeholder: 'Select an option'});
</script>
```
placeholder not hanging even if i remove attrs from widget.

**Comment by codingjoe** [comment]
Hi @pidzej I am using Django 1.11 in my projects, I can not recreate you issue. We also have tests that cover this behavior.
That being said, maybe I am missing something. If you can provide me with a test or with a more detailed description of the error, I would be happy to take another look at it.

Thanks
-Joe

**Comment by marco9999** [comment]
There may be something here.. I have a similar issue (trying to modify width), however looking at the chrome debugger, the 

```
var init = function ($element, options) {
    $element.select2(options)
  }
```

is actually getting called twice, first time with the options and second with no options.

The first time is triggered by loading our own scripts, but the second time appears to be from within django_select2.js? Specifically coming from here (looks like a document ready callback):

```
  $(function () {
    $('.django-select2').djangoSelect2()
  })
```

If I take this out, then my `options = { width: '1000px' }` works... 
(Although strangely placeholder text still doesn't work)

I'm not a web frontend dev, so I could also just be doing something wrong (accounting for the fact that no one has complained before).

**Comment by codingjoe** [comment]
@marco9999 ok, this seems to be Select2 related. I think you should take that to their community. This is merely the Django implementation. Select2 is maintained separately.

**Comment by gha2012** [comment]
@marco9999 thank you! I have the same problem. The django_select2.js hack works for me, too.
