### ISSUE TITLE
Error when loading JS

### ISSUE THREAD

**Issue by rafaelcapucho** [applegrew/django-select2#435]
I'm having this weird error. JQuery is present in the document though.

```
Django==1.11.6
Django-Select2==5.11.1
```

![a](https://user-images.githubusercontent.com/163367/32477365-a56401f2-c364-11e7-8e61-8fd6811a0f66.png)

All the following file opens correctly when clicked.

![b](https://user-images.githubusercontent.com/163367/32477364-a542b25e-c364-11e7-9459-77a98940ef70.png)

Thx.

**Comment by codingjoe** [comment]
That's in the Admin right? The Django's admin has this script called `jquery.init.js`. It does call `noConflict(true)` and assigns jQuery to `window.django`. I would recommend to add your own jQuery version.
