### ISSUE TITLE
Chained field ignores "selected" attribute.

### ISSUE THREAD

**Issue by eriktelepovsky** [applegrew/django-select2#436]
Hi. I am using the **dependent fields** functionality and I am trying to preselect the options instead of returning the filtered queryset. I have a custom ajax view which returns the correct data according to my needs in the following format defined by [select2 API](https://select2.org/data-sources/formats#selected-and-disabled-options):

```
{
    "more": false, 
    "results": [
        {
            "text": "Option 1", 
            "selected": false, 
            "id": 5
        }, 
        {
            "text": "Option 2", 
            "selected": true,
            "id": 6
        }
    ]
}
```

My code:

```
class AutoSelectedResponseView(AutoResponseView):
    def get_queryset(self):
        """Override queryset to return all results, not only dependent"""
        whole_qs = self.widget.filter_queryset(self.term, self.queryset)
        return whole_qs

    def get(self, request, *args, **kwargs):
        """
        Return a :class:`.django.http.JsonResponse`.

        Example::

            {
                'results': [
                    {
                        'text': "foo",
                        'id': 123,
                        'selected': false
                    }
                ],
                'more': true
            }

        """

        self.widget = self.get_widget_or_404()
        self.term = kwargs.get('term', request.GET.get('term', ''))
        self.object_list = self.get_queryset()
        context = self.get_context_data()

        # dependent/filtered results
        dependent_qs = super(AutoSelectedResponseView, self).get_queryset()

        return JsonResponse({
            'results': [
                {
                    'text': self.widget.label_from_instance(obj),
                    'id': obj.pk,
                    'selected': obj in dependent_qs  # selected if object is dependent
                }
                for obj in context['object_list']
                ],
            'more': context['page_obj'].has_next()
        })
```

Unfortunately, the value is never pre-selected. Any ideas why? Thank you.

**Comment by codingjoe** [comment]
Hi @eriktelepovsky I don't know about any `selected` attribute in the default API parser. You should really take this to the select2 repo, I believe they might be able to help you. Sorry that I can't :/

**Comment by eriktelepovsky** [comment]
Hi @codingjoe and thank you for your answer. Please look into select2 API:

https://select2.org/data-sources/formats#selected-and-disabled-options

There already is the "selected" attribute and it works fine. I am just not able to get it work with your django-select2 library. Can you collaborate, please? Thank you in advance.

**Comment by codingjoe** [comment]
Ok, my best guess is, that it doesn't work, because the API call is only made if you actually search for something. When the page is rendered no AJAX call is made. Why don't you want all the selected choices to be rendered using Django's template engine anyways? Can you elaborate more on the use case?

**Comment by eriktelepovsky** [comment]
Thank you for your reply. Let me clarify it a little bit more. Let's use a code in your "testapp". There are the Country and City models. Imagine, there are thousands of cities saved in the database and mapped to the countries they belong to, so I can't use the native select widget. I need ajax solution to speed it up. I want to show two selects in my form: one for a country and one for a city. The city dropdown should be dependent on the country of course. I am trying to show cities which belong to chosen country (already possible) and pre-select the capital city. What do you think?

**Comment by codingjoe** [comment]
@eriktelepovsky oh, ok, that is a tricky one. I believe that exceeds the possibilities of this package. I would recommend to build a more specific javascript interface for that use case and probably separate REST endpoints.

**Comment by eriktelepovsky** [comment]
I don't think it is a very tricky. I already have a custom AutoResponseView with custom API endpoint:

urls.py:
```
url(r"^fields/auto-selected.json$", AutoSelectedResponseView.as_view(), name="django_select2-json-selected"),
```

views.py
```
class AutoSelectedResponseView(AutoResponseView):
    def get_queryset(self):
        """Get full QuerySet from cached widget."""
        whole_qs = self.widget.filter_queryset(self.term, self.queryset)
        return whole_qs

    def get(self, request, *args, **kwargs):
        """
        Return a :class:`.django.http.JsonResponse`.

        Example::

            {
                'results': [
                    {
                        'text': "foo",
                        'id': 123,
                        'selected': false
                    }
                ],
                'more': true
            }

        """

        self.widget = self.get_widget_or_404()
        self.term = kwargs.get('term', request.GET.get('term', ''))
        self.object_list = self.get_queryset()
        context = self.get_context_data()

        # dependent/filtered results
        dependent_qs = super(AutoSelectedResponseView, self).get_queryset()

        return JsonResponse({
            'results': [
                {
                    'text': self.widget.label_from_instance(obj),
                    'id': obj.pk,
                    'selected': obj in dependent_qs  # selected if object is dependent
                }
                for obj in context['object_list']
                ],
            'more': context['page_obj'].has_next()
        })
```

and it already returns the data in a correct format defined by select2 API:

```
{
    "more": false, 
    "results": [
        {
            "text": "Option 1", 
            "selected": false, 
            "id": 5
        }, 
        {
            "text": "Option 2", 
            "selected": true,
            "id": 6
        }
    ]
}
```

forms.py:
```
my_field = forms.ModelChoiceField(
        queryset=MyModel.objects.all(),
        widget=ModelSelect2Widget(
            model=MyModel,
            dependent_fields={'parent': 'parents'},
            data_view='django_select2-json-selected',
            max_results=MyModel.objects.all().count()
        )
    )
```

I just don't understand, why the "selected" attribute is ignored by the dropdown and the options are not pre-selected? JavaScript select2 library already [supports this](https://select2.org/data-sources/formats#selected-and-disabled-options). I can see the items in response array with **"selected": true** in Google Chrome Console as well. 

Can you help a little bit more, please? You would know the best as the author of this library. Thank you.

**Comment by codingjoe** [comment]
@eriktelepovsky as I mentioned before, they are not selected because the the JSON is not loaded. You will need to tell the second select 2 widget to load the selected choices. Otherwise selected choices will only be loaded if you use the search.

**Comment by eriktelepovsky** [comment]
Hi @codingjoe I'd like to ask you: do you know if there is a way to retrieve the select2 data/options when "open" event is triggered, please?

My idea is to listen on "change" event of the parent field and then open the child select. I am trying to avoid calling ajax call programatically as I know it is called when select is opened, right?

I was looking in the [https://select2.org/programmatic-control/events](url), but couldn't find anything useful, so I was asking myself you can maybe help.

Thank you.

**Comment by codingjoe** [comment]
Hi @eriktelepovsky I don't know any solution from the top of my head. I believe the guys at select2 might be able to help you. Best Joe
