### ISSUE TITLE
Dependent fields to not support form prefixes

### ISSUE THREAD

**Issue by frague59** [applegrew/django-select2#439]
Hi, 

I'm doing a form with 2 dependent fields, linked together through a m2m relation:

```python 
class PaperType(Administrable, models.Model):
    """
    Paper weights and types
    """
    #: Paper weights, in g/m²
    weight = models.PositiveIntegerField(verbose_name=_('weight'), help_text=_('In g/m²'))

    #: Extra
    extra = models.CharField(max_length=255, verbose_name=_('extra'), null=True, blank=True)

class PaperColor(Administrable, models.Model):
    """
    Paper colors
    """
    #: color label
    label = models.CharField(verbose_name=_('label'), max_length=255)

    #: Available paper weights for this color
    available_paper_types = models.ManyToManyField('printflow.PaperType',
                                                   related_name='available_paper_colors',
                                                   blank=True)
```
 
Then I've set a relation between 2 ModelSelect2Widget (it is in a ModelForm, I've not set the form fields, but only the widgets: 

```python
class PrintJobForm(forms.ModelForm):
    class Meta:
        widgets = {'paper_type': s2_widgets.ModelSelect2Widget(model=models.PaperType,
                                                               search_fields=['extra__icontains',
                                                                              'weight__icontains', ],
                                                               dependent_fields={
                                                                   'paper_color': 'available_paper_colors'},
                                                               max_results=50
                                                               ),
                         'paper_color': s2_widgets.ModelSelect2Widget(model=models.PaperColor,
                                                                search_fields=['label__icontains'],
                                                                dependent_fields={
                                                                    'paper_type': 'available_paper_types'},
                                                                max_results=50
                                                                ),}
```

I can see in the html the `data-select2-dependent-fields="paper_type"` attribute in the paper_color field definition, but when I step-by-step debug the `ModelSelect2Mixin.filter_queryset()` method, no data in passed to the queryset: no GET "paper_type" parameter is send to the view.

Do you think it is possible to enable the `dependent_fields` in this case ? Did I miss something ?

Thanks for your great django application and for your help  :)

**Comment by frague59** [comment]
I've got it: I'm creating a form wizard, so the name of the fields are prefixed with the step names...

** Quick fix:  **
I've updated the dependent_fields from `paper_type` to `JOBS-paper_type`, and it works.

** Long (better) fix:  **
Detect the name of the wizard step on the `data-select2-dependent-fields="paper_type"` generation...

Thanks !

**Comment by codingjoe** [comment]
@frague59 thanks for reaching out. Good that you made it work, but I believe you just uncovered a bug. Seems the dependent field features doesn't play nice with form prefixes.

**Comment by codingjoe** [comment]
@a-ruzin can you check that?

**Comment by a-ruzin** [comment]
@frague59 Could you post full fix.
Is the problem "you have two forms on a single page with same input names"?

**Comment by a-ruzin** [comment]
@codingjoe btw, is this relates to https://github.com/applegrew/django-select2/pull/399 ?

**Comment by codingjoe** [comment]
@a-ruzin it does seem related to #399, could you review that PR?

**Comment by a-ruzin** [comment]
I will review. But He suggests a javascript hack (as I do in my first proposal for dependent fields). But it's better to change field names in python (as You insisted). I need some days to investigate the problem and solution.

**Comment by frague59** [comment]
@a-ruzin

I agree with this last proposal, because using python will work also for the wizards (I hope so...).

The point is to use dthe form_prefix as prefix for the fields, as done in formtools:
https://github.com/django/django-formtools/blob/master/formtools/wizard/views.py, line 405
```
...
'prefix': self.get_form_prefix(step, form_class),
...
```

**Comment by codingjoe** [comment]
The main problem here seems to be that prefixes are not supported for dependent fields. Which is bad, since everything else does. Prefixes are a common concept in `django.forms`. I think we should really fix it. I did write the dependent fields feature (nor do I use it). I would really welcome some help here 👍

**Comment by bc500** [comment]
Would a regex in javascript be enough? I think there have been already similar proposals, something like this might work if the convention to use a dash to separate the prefix is kept:

```javascript
          var dependentFields = $element.data('select2-dependent-fields')

          var prefix_regex = new RegExp("(.+-).+");
          var prefix_match = prefix_regex.exec($element.attr('name'));
          var prefix = '';
          if (prefix_match.length >= 2) {
            prefix = prefix_match[1]
          }

          if (dependentFields) {
            dependentFields = dependentFields.trim().split(/\s+/)
            $.each(dependentFields, function (i, dependentField) {
              result[dependentField] = $('[name=' + prefix + dependentField + ']', $element.closest('form')).val()
            })
          }
```
Solving this in python seems more difficult, the form class would have to be modified to pass the prefix to the widget.

**Comment by codingjoe** [comment]
@bc500 I would prefer to have the prefix prepended on python using `data-select2-dependent-fields`. At this point they should already have the correct prefix. This should solve the issue and avoids any issues with dependent fields pointing to anything but the current form. Sadly the prefix is not available in widgets per se. It should be extractable though.

**Comment by bc500** [comment]
What do you mean by extractable? As far as I understand, there is no visibility on the form object from the widget, as you pointed out.

**Comment by codingjoe** [comment]
I added a new in the current pull-request, but essentially. By default Django uses `-` as a prefix separator. This character is not allowed for class attributes. So it's save to assume that this is the separator even if you don't have access to the form.

**Comment by codingjoe** [comment]
It won't work in the cases where people override the two methods that build the prefixes, but hey. There are many ways to break this package ;)

**Comment by codingjoe** [comment]
Closed: **This issue has been inactive for an extended period of time. Please reopen the issue if it is still relevant.**
