### ISSUE TITLE
404's being raised when requesting the queryset from DB sporadically

### ISSUE THREAD

**Issue by ntbrown** [applegrew/django-select2#445]
Whenever using a MultipleModelSelect widget as in:

  ```
field = forms.ModelMultipleChoiceField(
        widget=ModelSelect2MultipleWidget(
             attrs={'data-placeholder': _("Start typing...")},
            model=MyModel,
            search_fields=[....],
         ),
        queryset=MyModel.objects.all(),
    )
```

404's are beign raised sporadically when teh ajax is kicked off resulting in "No results found", but re-clicking / sending the ajax request again will properly load the results. This happens sporadically.

**Comment by ntbrown** [comment]
Forgot to setup cache. Noob mistake.

**Comment by codingjoe** [comment]
No problem, happens to a lot of people. Its not very intuitive, but I currently don't know a way around it.
