### ISSUE TITLE
HTML validation fails

### ISSUE THREAD

**Issue by jvpap** [applegrew/django-select2#447]
I render a Select2Widget.
The HTML validation for this fails.
The generated HTML source contains a table without table tag.
I'm not sure if the problem comes from django-select2 or from select2 itself.

**Comment by codingjoe** [comment]
@jvpap thanks for the info, but you are correct, it is a problem in select2. We don't have any HTML code in this repository. All HTML that is generated uses Django templates. All JS related DOM modifications are provided by select2.

Cheers
-Joe
