### ISSUE TITLE
Model Select2 Widget extra choices

### ISSUE THREAD

**Issue by aqueeel** [applegrew/django-select2#450]
```
class MyForm(forms.Form):
    form = forms.ModelChoiceField(
        queryset= MyModel.objects.filter(status=1),
        label='',
        to_field_name = 'title',
        widget=widgets.MyWidget(),
    )

class MyWidget(ModelSelect2Widget):
    model = MyModel
    search_fields = [
        'title__icontains',
    ]
    max_results = 30
    
    
    def label_from_instance(self, obj):
        return str(obj.title)

```

How to add extra choices which is not in this model?

example: 

`<option value="somevalue"> All </option>`

How to select an value by default or programatically ?

**Comment by codingjoe** [comment]
Hi @aqueeel 

That is possible. You will need to overwrite the method `optgroups `. It's a method from Django, it responsible for creating the options.
https://github.com/applegrew/django-select2/blob/90fbf7422f1acaba1bffe9f1fba031a59a7d8ab0/django_select2/forms.py#L88-L92

Best
-Joe
