### ISSUE TITLE
Fancy single-quote in README.rst breaks docker

### ISSUE THREAD

**Issue by hmpf** [applegrew/django-select2#451]
The following line:

```"3. Add ``django_select`` to your urlconf if you use any ‘Auto’ fields."```  

https://github.com/applegrew/django-select2/blame/master/README.rst#L22

contains two non-ascii single quotes.

This breaks when running pip from a Dockerfile:

``UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 861: ordinal not in range(128)``

The UTF8-version of ``‘`` is ``\xe2\x80\x98``.

**Comment by hmpf** [comment]
To test:
```LC_ALL=C pip install django-select2==6.0.0```

**Comment by codingjoe** [comment]
Released in 6.0.1

**Comment by codingjoe** [comment]
Thanks @hmpf good call!
