### ISSUE TITLE
Select2 showing message 'Results cannot be loaded.' 

### ISSUE THREAD

**Issue by alessioferri20** [applegrew/django-select2#453]
Like in the title using the select2 (maybe caused by slow connection) i always get 'Results cannot be loaded'.
I suppose is not a problem specific on django-select2 but a problem with jQuery, however I am not able to find a solution, did you ever face this problem?

**Comment by codingjoe** [comment]
Hi @alessioferri20 

I believe you should check your logs too.
The message is thrown here: https://github.com/select2/select2/blob/ebf10c93db7d6d7a0d1330119d4c6f32cbd231d7/dist/js/select2.full.js#L3495

I guess in your logs you will find information if the JSON was malformed or if you have any other response error.

Best
-Joe

**Comment by alessioferri20** [comment]
Hi @codingjoe,
Thank you for your answer, however i forgot to mention that sometimes the result shown! so i don't get why sometimes is malformed and sometimes not!
Also in my local environment this behaviour occurs much less often!

**Comment by codingjoe** [comment]
Hello again. I believe this might be because of you cache setup. Please see http://django-select2.readthedocs.io/en/latest/django_select2.html#module-django_select2.conf

**Comment by alessioferri20** [comment]
HI @codingjoe,
I had completely forgotten about that implementation, so actually I never implemented the cache at all!
Do you think that this is the problem or the fact that I have not implemented the cache at all could hide another problem?

**Comment by alessioferri20** [comment]
Hi @codingjoe it seems that implementing the caching system throws the error already mention in issue 103: https://github.com/applegrew/django-select2/issues/103
Maybe there is an error in my configuration?
![schermata 2018-01-25 alle 15 00 13](https://user-images.githubusercontent.com/23658291/35391971-8aa1cb1e-01e0-11e8-99f4-9312680edd85.png)

**Comment by codingjoe** [comment]
@alessioferri20 are you using a multi node setup (have multiple application servers)? Should that be the case you need a shared (dedicated) cache server. I would recommend redis.

**Comment by alessioferri20** [comment]
Hi @codingjoe,
Thanks for you answer, however by implementing the cache it does not work anymore both in production and in my local environment, I don't have a multiple application servers and I've already tried using Redis too like in the link to [Read the Docs](http://django-select2.readthedocs.io/en/latest/django_select2.html#module-django_select2.conf) you provided before, unfortunately the result is always the same.
Before using the cache:
-  Local environment working perfectly and always returning the desired result.
-  in production working ~30% of the times (it have a weird behaviour that while writing the name sometimes it show the result sometimes not).

 After the implementation of the cache (like in the image I've provided before and using Redis like in this example [Read the Docs](http://django-select2.readthedocs.io/en/latest/django_select2.html#module-django_select2.conf) result is that the select always show 'Results cannot be loaded.' both in local and in production! (it seems it was better before the cache!)

To provide more information, hoping that is helpful, I can say that I'm using: 
```
<!-- jQuery Core -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<!-- jQuery UI -->
<script src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
```

**Comment by codingjoe** [comment]
@alessioferri20 ok, you should really check the 404 message. All 404 responses have a different message.
https://github.com/applegrew/django-select2/blob/90fbf7422f1acaba1bffe9f1fba031a59a7d8ab0/django_select2/views.py#L80-L87

**Comment by alessioferri20** [comment]
@codingjoe  As mentioned before it returns field_id not found

**Comment by codingjoe** [comment]
Ok I can say for sure there is nothing wrong with the package itself. It just be something with your cache setup. That being said, I am happy to help you out, can you please send you me your cache configuration. Not just the Django settings but also your eviction policy and so on.

**Comment by alessioferri20** [comment]
@codingjoe  Thank you for your help, this problem is driving me crazy XD!
Lets'see:
This is the cache configuration in the settings:
```
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    },
    'select2': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
        'TIMEOUT': 60 * 60 * 24,
    },
}

SELECT2_CACHE_BACKEND = 'select2'
```

Unfortunately I don't know what do you mean by eviction policy, however this is the nginx configuration that I'm actually using: 
```
server {
    listen 80;
    server_name 46.101.134.225;
    client_max_body_size 2M;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static {
        root /ebrand;
    }

    location /media {
        root /ebrand/staticfiles;
    }

    location /assets {
        root /;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/ebrand/ebrand.sock;
    }
}
```

And this is my gunicorn conf:
```
[Unit]
Description=gunicorn daemon
After=network.target

[Service]
User=root
Group=www-data
WorkingDirectory=/ebrand
ExecStart=/ebrand/bin/gunicorn --access-logfile - --workers 3 --bind unix:/ebrand/ebrand.sock ebrand.wsgi:application

[Install]
WantedBy=multi-user.target
```

The django project directory is placed under: /projectname

**Comment by alessioferri20** [comment]
@codingjoe I forgot to give to you how I implemented the plugin in my form:
```
from django_select2.forms import ModelSelect2Widget, ModelSelect2MultipleWidget
...
class CompanyForm(BaseModeratedObjectForm):
    ...
    city = forms.ModelChoiceField(widget=ModelSelect2Widget(
        model=City, search_fields=['name__istartswith']
    ), queryset=City.objects.all(), required=False)
    ...
    treatments = forms.ModelMultipleChoiceField(widget=ModelSelect2MultipleWidget(
        model=Treatment, search_fields=['name__icontains']
    ), queryset=Treatment.objects.all(), required=False)
    ...
```

**Comment by codingjoe** [comment]
hm... strange. I don't see a mistake, but I am also not a memcached export. I believe something is wrong with you memcache daemon. The error message you see is only being raised if the key can not be found. It can only not be found, because it's gone. Why It's gone I can tell. Maybe it's never been persisted. Maybe your memcached server crashes in between. That's why I recommended redis, since its persisted.
But I am guessing here. I am afraid I am reaching the limits of what I can do with "remote debugging" :/
I am sorry. I would suggest to check your memcached config again, maybe try another cache server. Use the filesystem one, just to be sure.

**Comment by alessioferri20** [comment]
Hi @codingjoe thank you for your answer,
However the problem present itself even with redis!
I will look further into this, and give you an update if i solve the problem ;).
The last thing i want to ask is what do you think about the problem showing sporadically without using the cache at all.
Thank you for your support!

**Comment by codingjoe** [comment]
The package always uses the cache. If none other specified it will use the `default` cache.
It uses the cache because it needs some kind of persistent storage to store the data. I would prefer to use the session storage. But Django doesn't pass the session down to the widget level, therefore there is not elegant way to access it.

**Comment by alessioferri20** [comment]
@codingjoe  How it can use the default cache if no default cache is implemented in the settings?

**Comment by codingjoe** [comment]
Because Django uses locmem as a default, see https://docs.djangoproject.com/en/2.0/topics/cache/#local-memory-caching

**Comment by alessioferri20** [comment]
@codingjoe I finally manage to get it work!!!!!!!!!
The problem was that i forgot to install redis-server, so implementing the redis cache after installing the redis-server (with sudo apt-get install redis-server) solved the problem *.*

**Comment by codingjoe** [comment]
I would recommend:

```python
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    'select2': {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Set the cache backend to select2
SELECT2_CACHE_BACKEND = 'select2'
```

**Comment by alessioferri20** [comment]
@codingjoe  I want to thank you for all your support and patience, you are the best!
I suggest to update the documentation (where select2 cache is implemented with memache) in order to address this possible problem ;)

**Comment by codingjoe** [comment]
@alessioferri20 do you want to open the PR? I feel you invested a lot of work her and deserve the credit :)

**Comment by alessioferri20** [comment]
@codingjoe It will be a pleasure ;)

**Comment by alessioferri20** [comment]
@codingjoe As this will be my first pull request, any advise will be greatly accepted XD!

**Comment by codingjoe** [comment]
@alessioferri20 it's hard to make too many mistakes. There are plenty linters in place to prevent you from making any style or spelling errors.

**Comment by codingjoe** [comment]
Closed: **This issue has been inactive for an extended period of time. Please reopen the issue if it is still relevant.**

**Comment by ashkov** [comment]
Hello! Does it work with memcached? I do not want to use redis server. Version 5.11.1

**Comment by codingjoe** [comment]
@ashkov any cache backend will do except the dummy backend or `LocMemCache` in a multi server setup.

**Comment by v1kku** [comment]
Would be nice to mention this in the setup guide in the docs; that you need to setup the cache and mention what will work and what won't.

**Comment by codingjoe** [comment]
@v1kku it is here: https://django-select2.readthedocs.io/en/latest/django_select2.html#django_select2.conf.Select2Conf.CACHE_BACKEND
That being said, Ia m sure the documentation could be improved. I would welcome a pull-request, if you would be interested in contributing.

**Comment by sandeepimpressads** [comment]
I have followed the exact steps above, added SELECT2_CACHE_BACKEND, CACHES. Still getting 

> field_id not found
when i added `redis-cli monitor` i can see the requests are coming to redis 
`1571897223.608474 [2 127.0.0.1:36772] "GET" ":1:select2_139996831722968"`
