### ISSUE TITLE
Configure django-select2 elements width in settings ?

### ISSUE THREAD

**Issue by zelds** [applegrew/django-select2#457]
Hi. How i can set in settings file default width value for every Widget in project ?
Example:
```
SELECT2_WIDTH = '100%'
```

**Comment by codingjoe** [comment]
Hi @zelds thanks for the feedback. I am curious, wouldn't your problem be solved by adding your own CSS file? This seems more intuitive to me than having a Django setting. What do you think?
best -joe

**Comment by zelds** [comment]
But 
```
Select2 will do its best to resolve the percent width specified via a css class, but it is not always possible. The best way to ensure that Select2 is using a percent based width is to inline the style declaration into the tag. `http://select2.github.io/select2/`
```
To solve it devs must find how to add inline styles by default to lib.

**Comment by codingjoe** [comment]
Well, this is not entirely true. You can set the with if you create your own template. Which I would recommend in this case. If this is just a one time thing passing an attribute does the job. If you don't know how to build your own select2 template, just create a python mixin that sets the attribute for all you widgets.

Those are three ways I can think of to solve this problem, that do not including adding a setting. Anyhow, even if, the use case does not seem to be big enough to add it here. I try to keep this package very very simple and small but provide a kick ass documentation as well as good support (like this ticket).

I would really welcome a PR that adds more documentation regarding this issue. A new setting is very unlikely tho.

best -j

**Comment by zelds** [comment]
But how this mixin must look like ?

**Comment by codingjoe** [comment]
Somthing like this, but I haven't tested that code. Don't have a shell open right now.
```python
class FixedWidthSelectWidgetMixin:
    def build_attr(self, attrs):
         attrs =  super().build_attrs(attrs)
         attrs['width']  = '100'
         return attrs
```

**Comment by zelds** [comment]
Thanks.
