### ISSUE TITLE
Limit number of tags

### ISSUE THREAD

**Issue by Macodom** [applegrew/django-select2#459]
This is not an issue but more like a request of feature.

Is possible to give a max number of tag selected? I know it can be done: 
https://stackoverflow.com/questions/21379988/select2-limit-number-of-tags

But I'm not sure where I can tweak this option on django-select2. If is possible would be great to be an add feature, but I will be happy only knowing where I can tweak this limit number.

**Comment by Macodom** [comment]
Well I think it was something noobish of me but it was as simple as put the attributes on the widget. Select2MultipleWidget(attrs={'class': 'span6', 'data-maximum-selection-length': 2}),

Maybe would be a good idea to put it in documentation to just point out how to add custom options from select2. I'm not sure if is something that simple that everyone knows how to deal.

**Comment by codingjoe** [comment]
Feel free to open a pull-request to add documentation, it's always a welcome contribution.
