### ISSUE TITLE
Metadata about supported Django versions is outdated

### ISSUE THREAD

**Issue by wimglenn** [applegrew/django-select2#461]
Hi there, thanks for the library.   Could you mention the supported Django versions on the github landing page and/or the docs?

It is still listing [Django 1.8 classifier](https://github.com/applegrew/django-select2/blob/426cace3a3d4093ba339b462c3205e4b3da4b359/setup.cfg#L18) in the `setup.cfg` metadata, and [on the PyPI landing page for release 6.0.1](https://pypi.python.org/pypi/Django-Select2/6.0.1), even though I'm sure 1.8 is no longer supported.

**Comment by codingjoe** [comment]
Thanks @wimglenn I removed the classifiers. We generally only support the latest version + latest LTS.
Fix is released in [6.0.2](https://github.com/applegrew/django-select2/releases/tag/6.0.2)
