### ISSUE TITLE
ModelSelect2Widget not compatible with change/delete related in admin interface

### ISSUE THREAD

**Issue by edevil** [applegrew/django-select2#463]
I'm using a ModelSelect2Widget for a field which is a foreign key to a different model:
```
            'project': ModelSelect2Widget(
                model=Project,
                search_fields=['title__icontains', 'id__icontains'],
                max_results=500,
            ),
```

In the admin interface, whenever I change the value of the select field, the two adjacent admin fields are not updated (change and delete related):

<img width="453" alt="screen shot 2018-02-21 at 17 52 18" src="https://user-images.githubusercontent.com/12426/36496382-fe4fdea2-172f-11e8-91f9-76f92abb66ef.png">

The buttons should be disabled when there is no value in the select box and enabled when something is selected. Is this a known limitation or it there a way to make the admin hooks work with django-select2?

**Comment by codingjoe** [comment]
Hi @edevil I recommend check out the changelog of the Django integration I wrote.
https://github.com/django/django/commit/94cd8efc50c717cd00244f4b2233f971a53b205e

You will find the necessary changes there if you still run on Django<2.0.
You can also check out pull-request #392
