### ISSUE TITLE
Read the Docs API documentation broken (automodule)

### ISSUE THREAD

**Issue by goetzb** [applegrew/django-select2#464]
Hi there,

Thank you for this useful app! Over the weekend, I've noticed that the **documentation on Red the Docs looks broken**. The API documentation from https://github.com/applegrew/django-select2/blob/master/docs/django_select2.rst seems no longer to evaluate the **`automodule` directive** correctly: http://django-select2.readthedocs.io/en/stable/django_select2.html
![2018-02-26_django-select2_rtd_automodule_broken](https://user-images.githubusercontent.com/1097522/36670015-b95eb6c0-1aee-11e8-9a65-97a75abd8cb8.png)

A version from July last year on https://web.archive.org/web/20170731032619/http://django-select2.readthedocs.io/en/latest/django_select2.html displays all the auto-generated content as expected:
![2018-02-26_django-select2_rtd_automodule_2017-07_archiveorg_working](https://user-images.githubusercontent.com/1097522/36670175-4f0ed83a-1aef-11e8-8f32-5652b3ce3ae7.png)

I don't exactly know since when the documentation is broken - maybe Read the Docs changed some configuration options or a Sphinx update introduced some changes...

Unfortunately, I could also not yet work out what's wrong from just looking at the code, so I can't suggest a fix, but at least I wanted to report it.

Please let me know if you have any questions!

Thank you,
Goetz

**Comment by codingjoe** [comment]
This is very likely related to https://github.com/sphinx-doc/sphinx/issues/4520
I downgraded the sphinx version.

**Comment by codingjoe** [comment]
That actually didn't have seem to fix it.

**Comment by codingjoe** [comment]
@goetzb I currently don't have much time on my hand, if you would want to debug this, it would be more than welcome 😉

**Comment by goetzb** [comment]
@codingjoe Thanks, I'll try to take a closer look over the coming days (or weeks... ;)

**Comment by codingjoe** [comment]
@goetzb yes, that would be cool! thx!

**Comment by codingjoe** [comment]
@goetzb I can not reproduce this locally. I asked @applegrew for access to the readthedocs project. I will look into the config there once I have access.

**Comment by codingjoe** [comment]
Fixed it 👍

**Comment by goetzb** [comment]
Great, thanks! - I wanted to have a look at the problem tonight...
