### ISSUE TITLE
dependent_fields in a formset

### ISSUE THREAD

**Issue by bc500** [applegrew/django-select2#465]
I am trying to use chained foreign keys in a model formset view (using ModelFormSetView from django-extra-views). The name of the fields is prefixed using 'form-0-', form-1-', etc.
The javascript code that selects the value of the chained field looks for the field name:

https://github.com/applegrew/django-select2/blob/7782e9bc3d5f51841b4184eaad494c098c348edf/django_select2/static/django_select2/django_select2.js#L20

This cannot find the field, as its name is prefixed with 'form-#-'.

Is there any way to append the prefix for formsets, so that the selector is something like this?
              result[dependentField] = $('[name=' + prefix + dependentField + ']', $element.closest('form')).val()

Thanks for any info.

**Comment by codingjoe** [comment]
Hi @bc500 yes, it seems the feature does currently not support prefixes :/
check out the main ticket about this #439
