### ISSUE TITLE
Documentation Inaccessible for Newbie Django Users

### ISSUE THREAD

**Issue by eddy-oj** [applegrew/django-select2#469]
Hi,

I am looking to use the tool you have made but don't understand the instructions.

e.g. in the installation instructions:

"Add django_select2 to your INSTALLED_APPS in your project settings."

Could you be more specific with a line of code?

Again:

"Add django_select to your urlconf".

Could you add a line of code? Even if it varies, it would be handy to have an example for the latest version of Django.

**Comment by codingjoe** [comment]
Hi @eddy-oj ,

I assumed those to be the Django basics, but you seem to prove me wrong. Honestly, I can try to explain you what I mean and you should tell me how to improve the documentation. I am using Django for half a decade now, it's sometimes hard for me to put me into someones shoes how is new to Django.

`INSTALLED_APPS` is a setting in your `settings.py` file of your project. Check out the testapp in your test suite:
https://github.com/applegrew/django-select2/blob/c2331b272a48139e3dd982119aa59133971c43c3/tests/testapp/settings.py#L13-L21

Your URL config is also defined in your settings file:
https://github.com/applegrew/django-select2/blob/c2331b272a48139e3dd982119aa59133971c43c3/tests/testapp/settings.py#L34

It is the root entry point for your request routing. Here is an example of the line you need to add:
https://github.com/applegrew/django-select2/blob/c2331b272a48139e3dd982119aa59133971c43c3/tests/testapp/urls.py#L34

Let me know if you need more help.

Best
-Joe
