### ISSUE TITLE
ImportError: No module named testapp

### ISSUE THREAD

**Issue by babygame0ver** [applegrew/django-select2#471]
I have tried to run the testapp by navigating in the directory it is saying that the testapp not found.

**Comment by codingjoe** [comment]
Hi @babygame0ver thanks for reaching out. I must admit the testapp is only made for the test suite. So don't expect a great. But anyhow, you can run the app from the git root, like:

```shell
python tests/testapp/manage.py runserver
```

If that doesn't work, try:
```shell
PYTHONPATH=. python tests/testapp/manage.py runserver
```
