### ISSUE TITLE
i18n is not activated by default

### ISSUE THREAD

**Issue by dzhuang** [applegrew/django-select2#483]
According to select2 [doc](https://select2.org/i18n), simply included the i18n js file won't activate i18n automatically, unless the lang is ``defined in the [lang]``.

I found I need to manually activated i18n by 
```javascript
$('.django-select2').djangoSelect2({language: "zh-CN"})
```
as I've defined [lang="en"] in template. Did I miss anything?

**Comment by codingjoe** [comment]
Hi @dzhuang are you sure? I believe I tested this for the Django admin patch.

**Comment by dzhuang** [comment]
Sorry for late response (again :-) ). I didn't test that in admin, but it actually happened in a normal view.

**Comment by codingjoe** [comment]
Closed: **This issue has been inactive for an extended period of time. Please reopen the issue if it is still relevant.**
