### ISSUE TITLE
Mention in README that basic select2 support is included in Django 2.0 admin

### ISSUE THREAD

**Issue by Tyilo** [applegrew/django-select2#485]
See [`ModelAdmin.autocomplete_fields`](https://docs.djangoproject.com/en/2.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.autocomplete_fields)

**Comment by codingjoe** [comment]
@Tyilo that's a very good idea, especially since I wrote the Django feature ;)

Would you mind writing the note and creating a PR?
