### ISSUE TITLE
How to change options format/html?

### ISSUE THREAD

**Issue by milano-slesarik** [applegrew/django-select2#487]
Hello, 
can't figure out how to set custom template for options.

EDIT: Django==2.0.6

USE CASE: 
When you have to choose from users and you want options to contain profile photo and the username.

I think that `label_from_instance` could do that but I can't use `ModelSelect2MultipleWidget`

```
class TestForm(forms.Form):
    user = forms.ModelMultipleChoiceField(queryset=User.objects.all(),widget=ModelSelect2MultipleWidget(model=User))
```
Doesn't show any users in options:

![image](https://user-images.githubusercontent.com/7869582/42053620-4834bace-7b12-11e8-9b7c-9f556e5ee73e.png)
The only thing which works for me is `ModelMultipleChoiceField` with `Select2MultipleWidget`

`forms.ModelMultipleChoiceField(queryset=User.objects.all(),widget=Select2MultipleWidget())
`
But you can't specify `label_from_instance` for this widget.

Do you have any ideas? 

Thanks

**Comment by codingjoe** [comment]
Hi @milano-slesarik that's a good questions, but you are asking it at the wrong place. You can specify your own renderer for the options, but that's done in javascript and is part of the Select2 library not of this Django package.

I would recommend you search their documentation for `templateResult` and  `templateSelection`.

Let me know if you need more help. I do use custom templates in one project, but with React.... so it's not very generic.
