### ISSUE TITLE
django-select2 works only with jquery 2 ?

### ISSUE THREAD

**Issue by cfournies** [applegrew/django-select2#489]
Quick question, I haven't been able to make Django-select2 work. I'm thinking that is the version. Django-select2 works only with Jquery 2? currently we are using jquery 3.3 and Select2 4.0
#

**Comment by codingjoe** [comment]
Hi @cfournies that's a great question, that I can't answer, since this is only the Django implementation. Please head over to the folks who maintain the main jQuery library here: https://github.com/select2/select2

I am sure they can help you.

Best
-Johannes
