### ISSUE TITLE
Select2TagWidget bug for arrayfield

### ISSUE THREAD

**Issue by teror4uks** [applegrew/django-select2#491]
Hello. I have some problem with custom Select2TagWidget for my ArrayField. When I create values in input and want delete only latest value, I can do that only if I push `Enter` or `Space` two times. My code:

It's my widget
```
class Select2TagWidgetArray(Select2TagWidget):

    def format_value(self, value):
        if not value:
            return []

        return value.split(',')

    def optgroups(self, name, value, attrs=None):
        if not self.choices and value:
            self.choices = [(c, c) for c in value]
        return super().optgroups(name, value, attrs=None)

    def value_from_datadict(self, data, files, name):
        values = super().value_from_datadict(data, files, name)
        return ','.join(values)
```

my form:
```
class CustomForm(forms.ModelForm):
    field = SimpleArrayField(
        forms.CharField(max_length=256), required=False, delimiter=',',
        widget=Select2TagWidgetArray(attrs={'data-width': '70%', 'data-token-separators': ','})
    )
```

Demonstration problem:
Tap one time on `ENTER` and will remove all values after clicked on `BACKSPACE`
![with_error](https://user-images.githubusercontent.com/10071749/42826036-20ae081e-89ec-11e8-93f7-9b479b625d1c.gif)

If tap two times to `ENTER` and trying push on `BACKSPACE` will remove only latest value
![non_error](https://user-images.githubusercontent.com/10071749/42826084-419e4da4-89ec-11e8-8dd8-fe6fc6cb8ae5.gif)

It too difficult push to button two times.

requirements:
django-select2 = 5.11.1
Django = 1.11

**Comment by codingjoe** [comment]
Hi @teror4uks wow good catch. This looks to me like a select2 issue and not related to this Django package. Please make sure to make the maintainers at select2 aware for this issue. Thanks -Joe
