### ISSUE TITLE
Version 6.1.1 does not work with python 3.5

### ISSUE THREAD

**Issue by predatell** [applegrew/django-select2#493]
File "/home/werty/.virtualenvs/myshibboleth3/lib/python3.5/site-packages/django_select2/conf.py", line 59
    JS = f'//cdnjs.cloudflare.com/ajax/libs/select2/{LIB_VERSION}/js/select2.min.js'
                                                                                   ^
SyntaxError: invalid syntax

**Comment by codingjoe** [comment]
We know, we don't support old Python versions. EoL for 3.5 is next year. Please see: https://github.com/applegrew/django-select2/commit/1954bf57fafee0f27a7b444b1a468331ac2af9b3

Again if you would provide a patch I am willing to merge it. But I won't invest my own time to support old python versions.

**Comment by predatell** [comment]
Possible you can add some notes to docs or requirements about what version of django-select2 supports what version of python

**Comment by codingjoe** [comment]
Sorry, yes, 2020, see https://devguide.python.org/#status-of-python-branches

Anyhow. I don't mind anyone patching it, I just won't do it myself, since I mostly use 3.7 or 3.6.
