### ISSUE TITLE
Documentation confusingly sparse

### ISSUE THREAD

**Issue by natecox** [applegrew/django-select2#496]
I came back to the docs today to look up the available widgets, because I haven't had to touch them in a while on my project; was surprised to find that the docs are basically empty right now.

![image](https://user-images.githubusercontent.com/2782695/43340304-bf46d95a-9190-11e8-8188-1d263cec4840.png)

Is this intentional?

**Comment by codingjoe** [comment]
good catch @natecox . did you figure out the problem yet by any chance?

**Comment by natecox** [comment]
I built the docs by cloning this repo successfully. The only issue I had is that the generation does not work with python 3.7 because the version of Sphinx included in the requirements file has a known bug that has since been fixed. Upgrading manually (`pip install -U sphinx`) fixed that issue for me.

I'm not sure what the process is to upload to RTD, but I'd say just rebuild and redeploy.

**Comment by natecox** [comment]
Let me know if there's anything else I can offer regarding this.

**Comment by codingjoe** [comment]
I checked rtd uses 3.5. I added another commit to add 3.5 compatibility again. Lets see if this improves things

**Comment by natecox** [comment]
Looks fine from my perspective.
