### ISSUE TITLE
django_select2 RequestURL problem

### ISSUE THREAD

**Issue by sunqy1212** [applegrew/django-select2#497]
Hi, I am using django_select2 in a form and doing everything just according to the document, but when I click the form field it renders nothing and show "No results found".
I checked the browser's RequestURL and find that the RequestURL is :"http://127.0.0.1:8000/app/?field_id=xxxxxxxxxxx", but not "http://127.0.0.1:8000/select2/fields/auto.json?filed_id=xxxxxxxxxxx" and I think that's the problem.
Can any one help me. Thanks in advance.
settings.py:
`INSTALLED_APPS = [
 app,
django_select2
]`
urls.py:
`urlpatterns = [
    url(r'^select2/', include('django_select2.urls')),
    url(r'^app/',include('app.urls')),
]`
forms.py:
`# -*- coding: UTF-8 -*-
from django import forms
from django_select2.forms import Select2Widget,ModelSelect2Widget,ModelSelect2MultipleWidget
class AppForm(forms.ModelForm):    name=forms.ModelChoiceField(queryset=UserProfile.objects.none(),widget=ModelSelect2Widget(model=UserProfile,search_fields=['full_name__icontains']),label='name')
    class Meta:
        model = App
        fields = "__all__" 
`

**Comment by codingjoe** [comment]
Hi @sunqy1212 thanks for reaching out. I presume this is a caching issue. Please please double check the cache configuration. If you have a dummy cache setup, it will not work.

Best
-Joe

**Comment by sunqy1212** [comment]
Thanks for you replay. I found my solution by changing the "select2.js" verson from 4.0.6 to 4.0.3，and its just working fine. May be this is because I am using django-selecct2 version 5.8.9.
