### ISSUE TITLE
Compatability with Django 2.1

### ISSUE THREAD

**Issue by shaief** [applegrew/django-select2#507]
I recently upgraded my Django to 2.1 and django-select2 to 6.3.1, and since upgrading i get the following error:

> Error during template rendering
> 
> In template /home/shaief/moon/pitch/venv/lib/python3.7/site-packages/django/contrib/admin/templates/admin/includes/fieldset.html, error at line 19
> render() got an unexpected keyword argument 'renderer'

 
row # | code
------- | ----------------------------------
9 | `{% for field in line %}`
10 | `<div{% if not line.fields\|length_is:'1' %} class="fieldBox{% if field.field.name %} field-{{ field.field.name }}{% endif %}{% if not field.is_readonly and field.errors %} errors{% endif %}{% if field.field.is_hidden %} hidden{% endif %}"{% elif field.is_checkbox %} class="checkbox-row"{% endif %}>`
11 | `{% if not line.fields\|length_is:'1' and not field.is_readonly %}{{ field.errors }}{% endif %}`
12 | `{% if field.is_checkbox %}`
13 | `{{ field.field }}{{ field.label_tag }}`
14 | `{% else %}`
15 | `{{ field.label_tag }}`
16 | `{% if field.is_readonly %}`
17 | `<div class="readonly">{{ field.contents }}</div>`
18 | `{% else %}`
19 | `{{ field.field }}`
20 | `{% endif %}`
21 | `{% endif %}`
22 | `{% if field.field.help_text %}`
23 | `<div class="help">{{ field.field.help_text\|safe }}</div>`
24 | `{% endif %}`
25 | `</div>`
26 | `{% endfor %}`
27 | `</div>`
28 | `{% endfor %}`
29 | `</fieldset>`

From what i could understand, this is probably related to django-select2.

For reference see here:
https://github.com/yourlabs/django-autocomplete-light/issues/1026

Thanks!

**Comment by codingjoe** [comment]
Hi @shaief do you happen to have a full stack trace for me?

**Comment by codingjoe** [comment]
I just looked into it a bit. This could not be raised by `django-select2` since we pass all arguments to super, see also
https://github.com/applegrew/django-select2/blob/e4efaab6f181592429e7fd1722729b6526cf74c0/django_select2/forms.py#L256-L258

**Comment by shaief** [comment]
@codingjoe thanks, i'll keep investigate it then.
