### ISSUE TITLE
ModelSelect2Widget: sorting

### ISSUE THREAD

**Issue by jieter** [applegrew/django-select2#510]
I need an annotation to change the ordering of the search results for the `ModelSelect2Widget`, to prioritize matches starting with the search term over substring matches. Just sorting by name can result in ordering like this with `term = 'cat'`:
```
a small cat
both big cats
cat
```

while I would like to have
```
cat
a small cat
both big cats
```

I implemented it using this customization of `ModelSelect2Widget`:
```python
class PrioritizeStartsWithWidget(ModelSelect2Widget):
    def filter_queryset(self, term, queryset, **dependent_fields):
        qs = super().filter_queryset(term, queryset, **dependent_fields)
        return  qs.annotate(
            starts_with_order=Case(
                When(name__istartswith=term, then=Value(1)),
                default=Value(0),
                output_field=IntegerField()
            ),
        ).order_by("-starts_with_order", "name")
```

While this works it might be nice to be able to add such a transformation without having to create a custom class. I'm not sure what would be a good/flexible API, but something like this would suit my needs:
```
class MyForm(forms.ModelForm):
   field = forms.ModelSelectField(...
       widget=ModelSelect(
           queryset=Model.objects.all(), 
           queryset_transform=lambda queryset, term: queryset.annotate(....).order_by(...)
       )
    )
```

The provided callable should be executed as part of `filter_queryset`

**Comment by codingjoe** [comment]
@jieter good idea. Do you have an idea how this could be solved?

**Comment by jieter** [comment]
Let me see if I can provide a quick implementation.
