### ISSUE TITLE
Django-select2 support for Django 2.0 on Python 3.4

### ISSUE THREAD

**Issue by shaief** [applegrew/django-select2#511]
Hi,
After upgrading django to version 2.0 and django-select2 to post 6 i have had some issues with Select2TagWidget (i get an empty and unusable form widget)
If i understand correctly, version 6.0 is the first to support Django 2.0, but there is no support for Python 3.4:

> 
    v6.0.0
    Add Support for Django 2.0
    Drop Python 2 support
    Drop Python 3.5 support
    Drop Django 1.8 support
    Drop Django 1.10 support

Is it true? if so - are there any workarounds?

Thanks!

**Comment by codingjoe** [comment]
The latest release should work on Python 3.4, but it is not supposed officially, meaning it could break even in minor release.
