### ISSUE TITLE
How disabled second select, before the first select is not selected?

### ISSUE THREAD

**Issue by kmvit** [applegrew/django-select2#514]
Hi, i am using this variant [https://django-select2.readthedocs.io/en/latest/extra.html#customizing-a-form](url)
I need disabled second select(city), before first select(country) is not selected.

**Comment by codingjoe** [comment]
Hi @kmvit , good question. There isn't anything built into the library to support that. You will need to write your own JavaScript code. You can listen to the `on_change` event from the form input. You don't need to catch any of the select2 related events. Select2 does currently trigger the `on_change` signal on the hidden input, as you would expect it.

Something like this:

```javascript
$('input[name="country"]').on('change', (e) -> {
  $('input[name="city"]').disabled = false
})
```

__code not tested__
