### ISSUE TITLE
In django_select2, the field_id parameter is getting not passed in ajax url

### ISSUE THREAD

**Issue by ramana-kk** [applegrew/django-select2#515]
While I am using django_select2, the field_id parameter is not getting passed to get URL select2/fields/auto.json. Due to this, it throws 404 error. Is there any configuration I am missing?

django_select2 - LIB_VERSION = '4.0.5' python3.6 django2.1

https://stackoverflow.com/q/52383968/10379621

**Comment by codingjoe** [comment]
Hi @ramana-kk thanks for reaching out. Sadly we no longer support version 4. There where may bugs back then, that could be just one of them. I honestly don't know.

**Comment by ramana-kk** [comment]
Hi @codingjoe , Thanks for the response.
Sorry to say it is the latest version. I mentioned the LIB_VERSION.
django_select2-6.3.1.dist-info

**Comment by codingjoe** [comment]
How do you know the field_id is not passed? What does your network log say? My best guess is, that you didn't setup your cache correctly and sue the `DummyCacheBackend`.
