### ISSUE TITLE
Looking for example of image dropdown.

### ISSUE THREAD

**Issue by glennpierce** [applegrew/django-select2#517]
Hi
Are there any examples of displaying images in a dropdown (For a model field in the Django Admin). 
Basically I want to display a list of images from the filesystem and present them for selection.

Thanks

**Comment by codingjoe** [comment]
In general I recommend to have the view respond a JSON not just plain text. When this is done you can parse the data in Javascript and change the template. You should look up the Select2 documentation for: `templateResult` and `templateSelection`.

Here is a little example of something that we use (python part only, we use a react frontend):
```python
class ArticleWidget(ModelSelect2Widget):

    def __init__(self, *args, **kwargs):
        kwargs['data_view'] = 'product_catalog:article-widget'
        super().__init__(*args, **kwargs)

    def build_attrs(self, *args, **kwargs):
        """Set select2's AJAX attributes."""
        attrs = super().build_attrs(*args, **kwargs)
        attrs['class'] = attrs['class'].replace('django-select2', 'article-widget', 1)
        return attrs

    def label_from_instance(self, obj):
        return json.dumps({
            'id': obj.pk,
            'text': obj.title,
            'image': obj.image.xs_cropped.url if obj.image else '',
        })
```
