### ISSUE TITLE
Exclude django_select2.js in a manner similar to #484, because #479

### ISSUE THREAD

**Issue by MiddleFork** [applegrew/django-select2#519]
In #479, you published the django-select2 JS to NPM
In #484, you provided the option to exclude the Select2 JS from the Select2Mixin class in forms.py

It would seem to follow that we would like the option to exclude the django-select2 JS in a similar manner, e.g. because we want to provide it via npm and our bundler.  ( I haven't yet attempted that.)

**Comment by codingjoe** [comment]
Hey there, I will continue to make comments about this matter on your PR, to make it a bit simpler.

**Comment by codingjoe** [comment]
HI @MiddleFork thanks for reaching out. I absolutely understand your points. There are scenarios where you want a custom script. I have plenty projects where I use costumized versions of select2.
However, I do think there might be a better solution, that covers more scenarios. I for example, have multiple different flavors of a select2 widget in a single project. Only one settings would not work.
Futhermore the basic script is already extenable. So you might want to keep the basic script and add a second one. So your Setting would need to provide a tuple?

Keeping all that in mind, I believe inheritance in the better way to solve this issue. You build your own mixin or a subclass that makes the changes to media, and importantly also changes the class name of the widget. That way you can also avoid namespace collision.

I have a set of those mixins at had, that give me a boostrap template or inject a completely different template renderer. I am happy to share them with you. Just let me know what you need.

Maybe we can also improve the documentation, another setting is for me currently not a satisfying alternative.

**Comment by MiddleFork** [comment]
My use case is to implement an NPM/webpack solution. For that reason I wish to exclude the script from being provided at all.

I'm one step away from this. I can definitely load both and bundle them and expose them. Everything works except the AJAX url at this point - I guess I'm not initializing something correctly and thus the /select2/fields/auto.json url doesn't get utilized - the AJAX request is working itself but the URL it acts against is the URL of the page itself.

When I switch back to the 'traditional' approach everything works so I know my configuration is OK at that level.

So my scenario, again, is that I don't want the script included locally at all.

If I'm able to totally implement the npm/webpack solution I'll provide a working example and perhaps you'll better understand my use case here.

**Comment by codingjoe** [comment]
Hi @MiddleFork 
I agree, it would be great to have an example for the NPM solution. I don't use it myself, so I can't really provide an example myself. But I know someone who can... @graingert would you mind providing a sample on how to use django-select2 integrated via NPM? Thx!

**Comment by graingert** [comment]
Yeah so I just subclassed the widgets and blanked it the media. You want to do this for all 3rd party widgets you use

**Comment by MiddleFork** [comment]
That was a cryptic one-liner, however as I am using django_crispy_forms, that may be an instance of which you are referring.


-------- Original Message --------
Subject: Re: [applegrew/django-select2] Exclude django_select2.js in a
manner similar to #484, because #479 (#519)
