### ISSUE TITLE
NPM+Webpack solution attempt:  Status and AJAX URL Question -with working solution

### ISSUE THREAD

**Issue by MiddleFork** [applegrew/django-select2#521]
I am working on an NPM+Webpack implementation for django-select2.  The goal is to use webpack to bundle all the required code and eliminate embedded script tags (#519). This is working up to a point that I think I can at least ask an educated question.

**Update: tl;dr:   I can in fact make this work if I add one line of code to django_select2.js**
9e781c8

```
var initHeavy = function ($element, options) {
    var settings = $.extend({
      ajax: {
+       url: $element.data('ajax-Url'),
        data: function (params) {
          var result = {
            term: params.term,
```

I do believe I now have a npm+webpack solution, no explicit <script> tags for jquery, select2, or django-select2 required anywhere.

The link that solved this for me is https://stackoverflow.com/questions/30373451/select2-use-a-dynamic-ajax-url-on-call

In retrospect, simple. Still have no idea why it was necessary for this solution but not in general.
-sw

**Everything that follows is my debugging process, and no longer relevant, except for the webpack index.js snippets.**

**My index.js looks like this (updated):**
```
// JQUERY
import $ from 'jquery';  // actually optional unless you want to work with $ in this file (ie in document.ready)
// SELECT2
import select2 from 'select2/dist/js/select2.min.js';
import 'select2/dist/css/select2.css';
// DJANGO-SELECT2
var djangoSelect2 = require("django-select2");
// DOCUMENT.READY - optional if you want to customize.
$(document).ready(function(){
  $('.django-select2').djangoSelect2({placeholder: 'My Placeholder Text'});
});
```
**A minimal index.js might look like this**
```
import select2 from 'select2/dist/js/select2.min.js';
import 'select2/dist/css/select2.css';
var djangoSelect2 = require("django-select2");
```

**And the result of the console logs seem promising:**

> jquery is:  ƒ ( selector, context ) {
> 
> 		// The jQuery object is actually just the init constructor 'enhanced'
> 		// Need init if jQuery is called (just allow error to be thrown if not included)
> 		return new jQuery…
> 
> select2 is  ƒ ($element, options) {
>     if (Utils.GetData($element[0], 'select2') != null) {
>       Utils.GetData($element[0], 'select2').destroy();
>     }
>     this.$element = $element;
>     this.id = this._generat…
> 
> djangoSelect2 is ƒ (options) {
>     var settings = $.extend({}, options)
>     $.each(this, function (i, element) {
>       var $element = $(element)
>       if ($element.hasClass('django-select2-heavy')) {
>         initHeavy(…
> 

**My issue is that the HeavySelect2 AJAX url is not represented in my AJAX query. So, monitoring what's going on I see this:**

> "GET /Test?term=9&field_id=MTQwMjM1OTU4MTUwNzA0%3A1gVMyc%3AAuc5NTlTYvs4I6oxr_mhemhs9BA HTTP/1.1" 200 1197
> "GET /Test?term=98&field_id=MTQwMjM1OTU4MTUwNzA0%3A1gVMyc%3AAuc5NTlTYvs4I6oxr_mhemhs9BA HTTP/1.1" 200 1197

etc.
**When what I need to see is** 

> "GET /select2/fields/auto.json?term=98&field_id=MTQwMjM1OTU4MTUwNzA0%3A1gVMyc%3AAuc5NTlTYvs4I6oxr_mhemhs9BA HTTP/1.1" 200 1197

**And indeed, if I copy and paste the above into the browser manually, behavior is as desired:**

> {"results": [{"text": "98001: Auburn,WA", "id": "98001"}, {"text": "98002: Auburn,WA", "id": "98002"}, {"text": "98003: Federal Way,WA", "id": "98003"}, {"text": "98004: Bellevue,WA", "id": "98004"}, {"text": "98005: Bellevue,WA", "id": "98005"}, {"text": "98006: Bellevue,WA", "id": "98006"}, {"text": "98007: Bellevue,WA", "id": "98007"}, {"text": "98008: Bellevue,WA", "id": "98008"}

So again, seems right.

Thus I ask myself why isn't the URL being substituted?  I look into the python code and see references to data_url (forms.HeavySelect2Mixin.__init__, 224) and data-ajax--url (forms.HeavySelect2Mixin.build_attrs (249).

> If I do a set_trace() within build_attrs, I can verify that

```
(Pdb) attrs['data-ajax--url']
'/select2/fields/auto.json'

```
And this is where my trail goes cold.  

**How do we get from here to the desired result? Where does the URL get implemented or utilized? How can I further diagnose?**

Thanks, 
Steve Walker

**Comment by codingjoe** [comment]
If it's only that one line, this looks like something you should report to the Select2 project itself.

**Comment by MiddleFork** [comment]
I appreciate your response.   I finally figured out what you mean, but I still don't fully understand.

In my ModelChoiceField() in my ModelSelect2Widget() I need to explicitly set 

> data_url='/select2/fields/auto.json'

In which case I do not need to modify your django_select2.js at all.  So you are correct to **WONTFIX**

And I can see in your API documentation for class django_select2.forms.HeavySelect2Widget you say

> data_url='/url/to/json/response'

and I can see in your tests/test_forms.py

> data_url='/foo/bar'


But I still don't see anywhere in your code where 

> data_url='/select2/fields/auto.json'

is set by default, or by example, in order to properly match the same string in your urlpatterns.

Am I still missing something, or does the same string (whether '/foo/bar', '/url/to/json/response' or '/select2/fields/auto.json') in fact need to be set both in the urlpatterns AND in the data_url?

And if it does, then my commit may actually be relevant after all.

Thank you again.

**Comment by codingjoe** [comment]
Hi @MiddleFork , I don't if I did fully understand your questions, but let me try to answer it anyways :)
So the URL is usually set via the HTML attribute `data-ajax--url` [here](https://github.com/applegrew/django-select2/blob/master/django_select2/forms.py#L246). You can override the URL for each widget by overriding [`get_url`](https://github.com/applegrew/django-select2/blob/master/django_select2/forms.py#L232-L236) or setting the `data_url` or `data_view` class attribute. The later needs to be a view name, not a fully resolved URL.
Of course if you want to use a custom view under a different URL you will need to register it in your `urlpatterns`.

I hope that helped a bit. Let me know if you have any further questions.
Best
-Joe

**Comment by manuelkappler** [comment]
I can confirm that the above commit solved a similar problem for me.
I initialized select2-fields in bootstrap modals that were dynamically generated. The url used for the ajax call in these cases was always the same as the underlying object (e.g. hostname/model/pk?field_id=foobar) whereas it should have been hostname/select2/fields/auto.json?field_id=foobar

Adding the above line to django_select2.js fixed that issue.

Interestingly enough, the select2 field on the modal actually did have the correct 'data--ajax-url' attribute and that didn't change with this fix. I'm not well-versed in JS (especially with the extend syntax) to understand whether the extend call in initHeavy overwrites the original select2 url implementation. If it does, that would explain the behavior here (as initHeavy is now called way past loading the select2 code).
