### ISSUE TITLE
django select2 chained dropdown

### ISSUE THREAD

**Issue by sbas1** [applegrew/django-select2#522]
I am new to Django and trying to get familiar with it. 

I have two dropdown menu's which are chained. I want to select a country, and from there I want to choose the city from that country. 

I  have the following models in models.py

    from django.db import models

    # Create your models here.
    class Country(models.Model):
        name = models.CharField(max_length=255)

        def __str__(self):
            return self.name

    class City(models.Model):
        name = models.CharField(max_length=255)
        country = models.ForeignKey('Country', related_name="cities", on_delete=models.CASCADE)

        def __str__(self):
            return self.name

My views.py has the following code:
    from django.shortcuts import render
    from django import forms
    
    from django_select2.forms import ModelSelect2Widget
    
    from .models import Country, City
    # Create your views here.
    
    class AddressForm(forms.Form):
        country = forms.ModelChoiceField(
            queryset=Country.objects.all(),
            label=u"Country",
            widget=ModelSelect2Widget(
                model=Country,
                search_fields=['name__icontains'],
            )
        )
    
        city = forms.ModelChoiceField(
            queryset=City.objects.all(),
            label=u"City",
            widget=ModelSelect2Widget(
                model=City,
                search_fields=['name__icontains'],
                dependent_fields={'country': 'country'},
                max_results=500,
            )
        )
    
    def start(request):
        form = AddressForm()
        return render(request, 'startpagina.html', {'form': form})

My HTML has the following code:

    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="UTF-8">
    <title>Chained</title>
    {{ form.media.css }}
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"
            integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
            crossorigin="anonymous"></script>
    
    
    </head>
    <body>
    <table>
        {{ form }}
    </table>
    <br>
    {{ form.media.js }}
    </body>
    </html>

I populated my country and city models with the following values:<br>
    Country: name: Nederland
    Country: name: belgie
    City: name: Amsterdam, country: Nederland
    City: name: Rotterdam, country: Nederland 
    City: name: Antwerpen, country: belgie
    City: name: Brussel, country: Belgie

When i run my django project I do get 2 dropdown menu, but unfortunately they are not linked. This means that when I select Nederland I don't get Amsterdam and Rotterdam, but I get all the cities.<br>

Can somebody tell me what i am missing in my code to get the 2 dropdown menu's linked?

**Comment by codingjoe** [comment]
Hi @sbas1 

Thanks for reaching out. I am not super familiar with dependent fields, since I didn't write that myself, but I'll give it a go. Could you please send me the network logs from your browser? When you select the country and focus the city field and maybe type something, what GET request is send to your server? What does the URL looks like?

Best
-Joe

**Comment by sbas1** [comment]
Hi Joe,

Due to sickness I was not able to react. Sorry for that.
I tried to do what you asked me to do and I got the following result
![screenshot from 2018-12-21 20-41-52](https://user-images.githubusercontent.com/45940134/50365006-d89ba380-0572-11e9-9c4e-00bd5695e077.png)

**Comment by codingjoe** [comment]
Hi @sbas1 something seems off. The second request, the one that fetches the cities should include `country` in the GET parameters. They should also include `term` which i don't see either. Maybe you could make another screenshot of the `param` file, not the response?

**Comment by sbas1** [comment]
Dear codingjoe,

Thank you very much for the idea to look in the param file. I found my mistake. The country_id was not given to the city. It turned out that i forgot the <form> in the HTML page. After adding it, it did work perfectly.
Once again thanks

**Comment by nielsvanhooy** [comment]
hi sbs1 i was wondering what your last change was to make it work. im also running into this issue.

**Comment by nielsvanhooy** [comment]
For anyone else reading this closed topic. after couple hours of trial and error.
just forgot to add a form method on the html.

{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  {{ form.media.css }}
  <style type="text/css">
    select {
      width: 200px;
    }
  </style>
</head>
<body>
<form method="post" action="">
  {{ form }}
  <input type="submit" value="Submit Form"/>
</form>
<script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
<script type="text/javascript">
  window.onerror = function (msg) {
    $("body").attr("JSError", msg);
  }
</script>
{{ form.media.js }}
</body>

**Comment by sbas1** [comment]
I see that my sentence is not complete. It is true that I forgot the to add the form method on the html

**Comment by gwsampso** [comment]
@sbas1  @nielsvanhooy do you happen to have a complet Forms, Template and Model you would be willing to share please? i'm really struggling overhere

**Comment by sbas1** [comment]
gwsampso. I hope this will help. This is a samll program that should work.

 [Chained_3.zip](https://github.com/applegrew/django-select2/files/2871368/Chained_3.zip)

**Comment by gwsampso** [comment]
Wow amazing thanks will review.

**Comment by address-url-routing46** [comment]
> I see that my sentence is not complete. It is true that I forgot the to add the form method on the html





https://mimicrepetitive.github.io/vfiAMPJfSwBB5Sq8HA4x9sBTHBbBAHSI3Pei1U2JflDPMtQI73bttkxDN/
