### ISSUE TITLE
Ignore __prefix__ in formsets

### ISSUE THREAD

**Issue by CleitonDeLima** [applegrew/django-select2#526]
Is possible ignore the `__prefix__` formsets when applying `djangoSelect2`?

I have verified that the initialization is done only with the class **.django-select2**  
https://github.com/applegrew/django-select2/blob/82859121a6285d212d6d42ec8a9b65cf02ee5991/django_select2/static/django_select2/django_select2.js#L65

When initializing `.djangoSelect2` in dynamic field this happens:

![image](https://user-images.githubusercontent.com/4956372/52371402-9227d880-2a3c-11e9-816b-c4d95dcbe33a.png)

**Comment by CleitonDeLima** [comment]
This fixed my problem:

https://github.com/CleitonDeLima/django-select2/commit/797d8277344ce6d9b7616f84a1794ca610175baf#diff-4f5cd3437db85c4e907ea4fae06cfd0dR65

**Comment by codingjoe** [comment]
@CleitonDeLima are you in the Django Admin? I would recommend to use autocomplete fields introduced in Django 2.

**Comment by CleitonDeLima** [comment]
@codingjoe No, it's outside admin.

**Comment by codingjoe** [comment]
I see, but you seem to dynamically add new formsets don't you? In this case you will need to initialize those too. Just using `$('.django-select2').djangoSelect2()` will initialize it again on the form elements that have been already initialized previously. You will need to call that on the elements that you actually add.

**Comment by CleitonDeLima** [comment]
@codingjoe returning to this issue,

In django 2.x fields with `[name*=__prefix__]` to apply autocomplete widgets are ignored.

![image](https://user-images.githubusercontent.com/4956372/63144272-84917380-bfc8-11e9-91cf-8ed439ba2e01.png)
[Link to django autocomplete.js](https://github.com/django/django/blob/8289fc55fff879df273cb95fdd1b039447f85783/django/contrib/admin/static/admin/js/autocomplete.js#L29)

Considering empty formset in outside admin templates, is possible apply this in project? I can contribute to it

**Comment by codingjoe** [comment]
Hi @CleitonDeLima,

I implemented autocomplete fields in Django, therefore I know that this is one of my changes required to make select2 work properly in Django's admin interface. Since Django now has support autocomplete fields, I don't see a reason to back port the functionality.

Can you explain your scenario a bit more and help me understand, why you can't use autocomplete feilds?

Best
-Joe

**Comment by CleitonDeLima** [comment]
Hi @codingjoe,

I am using formsets **outside admin** and dynamically adding items using a button. I have an empty form with `__prefix__` in the fields and they are initialized with DjangoSelect2. This startup does not work correctly. The DjangoSelect2 call should exclude fields with `__prefix__` to work properly just like in Django admin. The formsets are the same, in both admin and in my application outside admin.

1 - Example (DjangoSelect2 has been called on start page):  
![image](https://user-images.githubusercontent.com/4956372/63268052-b1b08100-c269-11e9-888f-e7cb67218b5c.png)

2 - Add form called (DjangoSelect2 initialized again, create new field with select2)
![image](https://user-images.githubusercontent.com/4956372/63268323-4e731e80-c26a-11e9-9607-ea3ed1ec4131.png)

If there is no solution, what would be my options regarding `formset.empty_form` with DjangoSelect2 **outside admin**?

**Comment by codingjoe** [comment]
@CleitonDeLima check out my comment over here: https://github.com/applegrew/django-select2/issues/564#issuecomment-522255122 and over here: https://github.com/applegrew/django-select2/issues/561#issuecomment-514491099

We are currently working on a solution to make extending the JS part simpler and better documented. You contribution would be very much appreciated.

**Comment by CleitonDeLima** [comment]
@codingjoe 

Now I understand the problem, thanks for clarifying my questions.

**Comment by codingjoe** [comment]
@CleitonDeLima my pleasure. Feel free to "bother" me with more questions in the future :)
