### ISSUE TITLE
Database formatting & search filter

### ISSUE THREAD

**Issue by BedirT** [applegrew/django-select2#527]
Hi,

I am using ```ModelSelect2TagWidget``` to get the data to database. The problem is I am getting the data in a format that I don't really want.

## Forms.py
```python
class QuestionLevelSelect2TagWidget(levelSearchFieldMixin, Select2TagWidget):

	def value_from_datadict(self, data, files, name):
	    values = super(QuestionLevelSelect2TagWidget, self).value_from_datadict(data, files, name)
	    return ",".join(values)
```

What I expect is the data entered to be separate data rows, like my model is:

### Models.py
```python
class QLevel(models.Model):
    qID = models.ForeignKey(Question, on_delete=models.CASCADE)
    level = models.CharField(max_length=16)

    def __str__(self):
        return self.level
```
and I expect when i entered 3, 4, 5 - for example to be ;
- 3 
- 4
- 5 

in db. But it comes out as;
- 3,4,5

How can I fix this? 

The second question of mine is about the name filtering.  When I search for some specific names I am trying to use fieldmixin but obviously, it's not working. I don't know what should I use. Basically, I just need a string filtering from all the data in the table.

```python 
class levelSearchFieldMixin(object):
	model = QLevel
	search_fields = [
		'level__icontains'
	]
```
If possible I could go with some array meaning like a custom array thats gonna be in search results i.e. ```Choices=[3, 4, 5, 6, 7]```

**Comment by codingjoe** [comment]
Hi @BedirT,

I would need to see more of your code to understand what it is you are trying to do here, but my best guess is: You are seeing `3,4,5` saved to your database, because you explicitly tell it to here: `return ",".join(values)`

**Comment by codingjoe** [comment]
In any case, you see to be wanting to build some highly custom stuff. I am not sure you want to use this library for that. You might be better of, just using select2 bare bones and write whatever python code you need for it.
