### ISSUE TITLE
Option text is clipped at 20 chars

### ISSUE THREAD

**Issue by hodossy** [applegrew/django-select2#531]
I have the above problem, I was not able to find why this happens. Thanks for any suggestions!

**Comment by codingjoe** [comment]
Hi @hodossy this sounds strange. Are you sure your options are actually stored longer than 20 chars in the database. I wouldn't know of any place where we clip the options. That beings said, maybe select2 itself does clip the results when rendering the template. That I don't know and you would need to take up with them. Sorry, that I can't be of any more help.

**Comment by hodossy** [comment]
Hello @codingjoe, DB field is varchar(250), but the json response only contains 20 chars, so it must be this package setting up the auto response view.

**Comment by codingjoe** [comment]
hi @hodossy,

the view, that creates the JSON response calls the `label_from_instance` method on your widget, see https://github.com/applegrew/django-select2/blob/ffe91627d8befbf6fdf8798cbda572b4c6c3cced/django_select2/forms.py#L460-L479

Unless you changes the method, it will call `Model.__str__`. I would recommend to check the string representation of your object. Maybe you do the string clipping there. I checked again, there is no code in this package, that trims the string to 20 chars.

Best
-Joe
