### ISSUE TITLE
Disable options

### ISSUE THREAD

**Issue by nutrihub** [applegrew/django-select2#532]
Is it possible to pass an additional argument "disabled_choice" to allow defining a new queryset which creates options with the "disabled" tag?
~~~~
   <option value = "1" disabled="disabled">Foo</option>
~~~~

**Comment by codingjoe** [comment]
No not really. You would need to change the view and add another option to the JSON response. You would also need to add your own template rendering function to render the options. This is possible and I have done it, but it's a lot of work. I would recommend to maybe find a conceptional solution to your problem.
If you really need one. I can give you some pointer on how to implement that.
