### ISSUE TITLE
Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by dahuangfeng123** [applegrew/django-select2#533]
django 1.11.17
windows 10
chrome 72.0.3626.121
jQuery v2.2.3

![image](https://user-images.githubusercontent.com/3371478/55571973-2fe80d00-5739-11e9-921d-1376bc6e3ece.png)

![image](https://user-images.githubusercontent.com/3371478/55571939-1e9f0080-5739-11e9-9a5f-a3f598c64aab.png)

**Comment by codingjoe** [comment]
Hi @dahuangfeng123,

thanks for reaching out. Django removes `$` as a name for jQuery from the global javascript namespace using `$.noConflict(window.django, true)`.

That is why you can't simply use django-select2 in the admin. I would suggest to use the `autocomplete_field` feature that was introduced in Django 2. It is based on select2 but better integrated for its use in Django admin.

I hope that does help you a bit. If you have further questions, please feel free to reach out.

Best
-Joe
