### ISSUE TITLE
pypi release 7.0.2 is lacking the static files

### ISSUE THREAD

**Issue by tuky** [applegrew/django-select2#535]
**Describe the bug**
Downloading the package from https://pypi.org/project/django-select2/ gives me an archive without the static files.

Thx for this app, btw.

**Comment by codingjoe** [comment]
@tuky good catch. Sorry for that. I am working on a patch right now.

**Comment by jieter** [comment]
oops, just caught this after cleaning out my development environment :|. Luckily, `./manage.py collectstatic` doest not delete files in its destination directory, so production still has the version .
