### ISSUE TITLE
How to update a widget with JS

### ISSUE THREAD

**Issue by fmatray** [applegrew/django-select2#539]
**Goal**
I want to update a ModelSelect2MultipleWidget field with JS.

**Problem**
I can't update following the documentation of Select2. 
I guess, values are not in a correct format but I can't find how to to this.

**Code Snippet**
I tried several things :
$('id_selections').select2.val([1, 2, 3]).trigger('change')

$('id_selections').djangoSelect2.val([1, 2, 3]).trigger('change')

Thanks a lot.

**Comment by codingjoe** [comment]
Hi @fmatray thanks for reaching out. I am afraid I don't quite understand your problem yet. Can you share a little more informatin about your use case. What is it you are trying to achive. Best-Joe

**Comment by fmatray** [comment]
Hello,
sorry, I was not very clear.

I have a field _services_ in _UnAvailabilityForm_ :
`'services': ModelSelect2MultipleWidget(model=Service, search_fields=['name__icontains', 'tech_infos__icontains'])`

In the HTML form, I have a select menu called template. 
When I select a template, several fields in the form are updated with Javascript. 
And I want to to something like :  **$("#id_services").update(data.services)**


My JS code : 
```
$("#template").change(function() {
    url = $( "select option:selected" ).val();
    if (url != "") {
        $.getJSON(url, function(data) {
            $("#id_title").val(data.title)
            $("#id_description").val(data.description)
            $("#id_impact").val(data.impact)
        });
    } else {
        $("#id_title").val('')
        $("#id_description").val('')
        $("#id_impact").val('')
    }
});
```

Thanks a lot.

**Comment by codingjoe** [comment]
Hi @fmatray, I see what you are trying to do. That being said, this is the wrong place to ask this question. This is a JS questions related only to select2 not this Django integration. Check out their documentation https://select2.org/
They also have an IRC chat, where you can find help.
Best
-joe
