### ISSUE TITLE
queryset from choices

### ISSUE THREAD

**Issue by predatell** [applegrew/django-select2#540]
I want to use `ModelSelect2Widget` with `ModelChoiceField`. I set `queryset` to `ModelChoiceField`, so I don't want to add the same `queryset` to `ModelSelect2Widget`. `ModelSelect2Widget` can take it from `self.choices.queryset`(related pull request #509). Example how do I use it:

`item = forms.ModelChoiceField(queryset=MyModel.objects.filter(is_active=True), required=False, widget=ModelSelect2Widget)`

**Comment by codingjoe** [comment]
Closed in favor of #509
