### ISSUE TITLE
what is the minimal required python version?

### ISSUE THREAD

**Issue by mfrasca** [applegrew/django-select2#545]
I just opened the sources, and saw some `f-`strings.  they are only there in test sources, not in generic sources, so I assume that the requirement for testing is 3.6, while the requirement in general, that would be? ??  
how do you make sure that the code is 3.5 compliant while the test suite is not?

**Comment by codingjoe** [comment]
@mfrasca simple answer, we don't. The package only supports CPython 3.6+.
3.5 was only used to build the docs. Since readthedocs.io upgraded their build stack to Python 3.7, we will drop that too in the future.

**Comment by mfrasca** [comment]
please note: the last released Debian is still 9-stretch, and stretch only provides Python3.5.
I would wait for Debian-10 to be released, before dropping support for Python3.5.
that will possibly happen "some time mid 2019", according to the Debian team.

**Comment by codingjoe** [comment]
@mfrasca that might be true, but Debian has hundreds of contributors and commercial sponsors. This package has a hand full of people like you and me. I can not provide the same legacy support as Debian does. We have plenty old version that do support older Python versions, people can use those. But if they want to use the latest features of this package, they will also need to set up the latest Python and Django version. I guess there is just so much you and I can do 🤷‍♂

**Comment by mfrasca** [comment]
what can we do… well, the point from my part is that I am using Debian 9 and per default I use and suggest usage of Python3.5, in combination with Django 2.2.  I have been using `django-select2` in this setup and it works fine (apart from issue #544).  so from my point of view I have the choice between instructing Debian 9 users to install Python 3.7, or if you have nothing fundamentally against 3.5, make the test suite for `django-select2` succeeds with Python3.5.  and my preference goes for the second option.  I have installed 3.7 on my system just in order to run this test suite, but I'm ready to backport the test suite to 3.5 if you give green light.

**Comment by codingjoe** [comment]
@mfrasca I'd really like to avoid that. If you have root access to your system, why not install a newer Python version. If you are not familiar with installing Python from source, I'd recommend using [pyenv](https://github.com/pyenv/pyenv).

**Comment by mfrasca** [comment]
I have nothing against recommending anything, and I have been managing my first Linux computers doing (tar xzf source.tar.gz; ./configure; make; sudo make install) but … we need to state things in the front page I would say.  this pyenv thing looks like too much automagic, I prefer virtual environments.
