### ISSUE TITLE
jQuery Version 3

### ISSUE THREAD

**Issue by DylanYoung** [applegrew/django-select2#574]
**Describe the bug**
Does django-select2 support jQuery v3?  jQuery v2 no longer receives support, but the docs still mention it and nothing else.

**To Reproduce**
https://django-select2.readthedocs.io/en/latest/get_started.html#external-dependencies

**Comment by codingjoe** [comment]
@DylanYoung good catch, thanks! I opened a PR #575 to fix the documentation. Would you mind reviewing the changes? Thx!

**Comment by DylanYoung** [comment]
Looks good to me @codingjoe. Thanks!
