### ISSUE TITLE
Error while saving a field without value

### ISSUE THREAD

**Issue by developingo** [applegrew/django-select2#58]
I'm using an AutoModelSelect2Field in django's admin site, and works fine except when I try to submit a form without any value for this field. The complete traceback is here: (http://dpaste.com/1392138/)

It seems to be a problem while rendering the widget, maybe it assumes it has a value.

**Comment by codingjoe** [comment]
I this error occurring in django 1.5+?
If we don't support django 1.4 LTS yet, should be in the future as it is going to be deprecated rather soon?
