### ISSUE TITLE
Clean option no works properly

### ISSUE THREAD

**Issue by OVarLaz** [applegrew/django-select2#588]
**Describe the bug**
Visual bug in django-select2 option, when I try to clean the content in the box, removing all items, but if I select a new, I get a blank space. I use django-select2==7.2.0 (lastest version)

**Exception & Traceback**
If I click 2 times in the "x", the content is cleaned completely

**Code Snippet**
forms.py
![image](https://user-images.githubusercontent.com/12819313/72739509-c2935480-3b71-11ea-9fb5-8f4b9e9a1ddf.png)

views.py
```python
especialidadesFormset = CentroInvestigacionEspecialidadForm(prefix='especialidades')
```

reg.html
```html
<div class="col-12">
       {{ especialidadesFormset.management_form }}
        {% for form in especialidadesFormset %}
              {{ especialidadesFormset }}
        {% endfor %}
  </div>
```

**To Reproduce**
1. Go to the view with the select2 field
2. Add/select one or more options 
3. Remove all items, clicking in "x"
4. Select another item of the list
5. Will see a blank selection before the last selected

**Expected behavior**
It must not show that blank space, with my selection

**Screenshots**
![x](https://user-images.githubusercontent.com/12819313/72738229-20726d00-3b6f-11ea-8125-b1f39181acd7.PNG)

**Comment by codingjoe** [comment]
Hi @OVarLaz the `CentralInvestigationEspecialidad` model with me as well? Best Joe

**Comment by codingjoe** [comment]
This repo has moved, please address your issue at https://github.com/codingjoe/django-select2 Thanks!
