### ISSUE TITLE
Release 7.2.1 on PIP

### ISSUE THREAD

**Issue by vaibhavmule** [applegrew/django-select2#594]
I can see that you have released https://github.com/applegrew/django-select2/releases/tag/7.2.1, what are things blocking to release on Pypi?

@codingjoe

**Comment by codingjoe** [comment]
Thanks @vaibhavmule for bringing this to my attention. It seems travis-ci has changed its behavior and therefore the automated release did not run. Best -Joe

**Comment by vaibhavmule** [comment]
Just curious if it wasn't deployed, it should have given an error or failed build, right?

**Comment by codingjoe** [comment]
@vaibhavmule it was successfully deployed. 7.2.2 that is.

**Comment by vaibhavmule** [comment]
@codingjoe I was talking about 7.2.1

**Comment by codingjoe** [comment]
@codingjoe same code, just that 7.2.1 had a release error. I will not release it manually. Please use 7.2.2

**Comment by vaibhavmule** [comment]
yes using 7.2.2 only. Thanks for the release.
