### ISSUE TITLE
ModelSelect2TagWidget tagging new values

### ISSUE THREAD

**Issue by Mergpijp** [applegrew/django-select2#603]
**Describe the bug**
Clearly given 4 arguments but it says 5 were given..

**Exception & Traceback**
value_from_datadict() takes 4 positional arguments but 5 were given

 values = super().value_from_datadict(self, data, files, name)  at line 205

**Code Snippet**
From the documentation in forms.py:

```
class KeywordSelect2TagWidget(ModelSelect2TagWidget):
    queryset = Keyword.objects.all()

    def value_from_datadict(self, data, files, name):
        values = super().value_from_datadict(self, data, files, name)
        queryset = self.get_queryset()
        pks = queryset.filter(**{'pk__in': list(values)}).values_list('pk', flat=True)
        cleaned_values = []
        for val in values:
            if force_text(val) not in pks:
                val = queryset.create(title=val).pk
            cleaned_values.append(val)
        return cleaned_values
```

In forms.py:

```
    keywords = forms.ModelMultipleChoiceField(widget=KeywordSelect2TagWidget(
        model=Keyword,
        search_fields=['name__icontains',],
        attrs={'data-minimum-input-length': 0,},
    ),queryset=Keyword.objects.all(), required=False)
```

> __class__ | <class 'publications.forms.KeywordSelect2TagWidget'>
> -- | --
> data | {'ISBN_number': '',  'collection_country': '',  'collection_date': '',  'collection_venue_and_city': '',  'contact_email': '',  'contact_telephone_number': '',  'contact_website': '',  'content_description': '',  'copyrights': 'unknown',  'csrfmiddlewaretoken': 'AzfnVs88SWyp5j1BO71TpD5dHBfHEbKK1dvJaSDuRGGmws0jaU3PydWitibwU5z4',  'description_of_illustration': '',  'donor': '',  'editor': '',  'extra_info': '',  'general_comments': '',  'is_a_translation': '',  'keywords': 'm',  'nr_of_pages': '',  'printed_by': '',  'publication_city': '',  'publication_date': '',  'published_by': '',  'publishing_organisation': '',  'save': 'Save',  'team_comments': '',  'title_original': '',  'title_subtitle_European': '',  'title_subtitle_transcription': '',  'title_translation': '',  'translated_from': ''}
> files | <MultiValueDict: {}>
> name | 'keywords'
> self | <publications.forms.KeywordSelect2TagWidget object at 0x00000287D6A72780>

**To Reproduce**
Add new tags or existing tags to the keywords field.

**Expected behavior**
Expected it to work with existing keywords but the error persists.

**Comment by codingjoe** [comment]
Hi @Mergpijp thanks for the detailed error report. This isn't a bug though. It's a simple Python mistake. You don't pass `self` to a `super` call, that is done automatically by the interpreter, same as you don't have to add `self` on a regular method call on an object instance.

Following your example:
```python
values = super().value_from_datadict(data, files, name)
```

**Comment by Mergpijp** [comment]
Dear Joe,

I tried running it without the self argument but it is still not working.
I will show you my model:

```
class Keyword(models.Model):
    name = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.name

```
I even tried to change title to name from the given code in the documentation.

`val = queryset.create(name=val).pk`

It will give : invalid literal for int() with base 10: 'hey' If i put 'hey' as tag.
Referring to:

`pks = queryset.filter(**{'pk__in': list(values)}).values_list('pk', flat=True)`

Any idea how to get this to work?

**Comment by codingjoe** [comment]
Hi @Mergpijp do could you provide the entire traceback please? It would help me to narrow down the issue. Best Joe

**Comment by Mergpijp** [comment]
Hi @codingjoe, this time i tried entering 'something' here is the traceback:
http://dpaste.com/3FJ99GA

**Comment by codingjoe** [comment]
Hi @Mergpijp,

Ok, so what you need to do here, is to remove all strings from list of possible keys:

```python
class KeywordSelect2TagWidget(ModelSelect2TagWidget):
    queryset = Keyword.objects.all()

    def value_from_datadict(self, data, files, name):
        values = super().value_from_datadict(self, data, files, name)
        queryset = self.get_queryset()
        pks = queryset.filter(**{'pk__in': [v for v in values if v.isdigit())}).values_list('pk', flat=True)
        cleaned_values = []
        for val in values:
            if force_text(val) not in pks:
                val = queryset.create(title=val).pk
            cleaned_values.append(val)
        return cleaned_values
```

**Comment by Mergpijp** [comment]
Hi @codingjoe ,

There was a typo in your code the list comprehension did not close. I have the following code:
```
class KeywordSelect2TagWidget(ModelSelect2TagWidget):
    queryset = Keyword.objects.all()

    def value_from_datadict(self, data, files, name):
        values = super().value_from_datadict(data, files, name)
        queryset = self.get_queryset()
        pks = queryset.filter(**{'pk__in': [v for v in values if v.isdigit()]}).values_list('pk', flat=True)
        cleaned_values = []
        for val in values:
            if force_text(val) not in pks:
                val = queryset.create(name=val).pk
            cleaned_values.append(val)
        return cleaned_values
```
Now it works when I enter black and press save the form will have black as keyword. However if then enter white and save. It will have an integer as keyword and white. If enter Orange and save. It will have 2 integers and Orange as keyword. Something is still wrong.

**Comment by codingjoe** [comment]
Honestly, at this point, you a probably best served with a debugger. Maybe use pdb and set a breakpoint in the for loop. I am sorry, I can't be of better help.

**Comment by Mergpijp** [comment]
Ok installed django-pdb with breakpoint() in the code. How do I inspect variables? I am using pycharm at the moment.

**Comment by Mergpijp** [comment]
Hi @codingjoe,

I solved this the only downside is that you cannot use integers as tag. Here is the code:

```
def represent_int(s):
    try:
        int(s)
        return True
    except ValueError:
        return False


class KeywordSelect2TagWidget(ModelSelect2TagWidget):
    queryset = Keyword.objects.all()

    def value_from_datadict(self, data, files, name):
        values = super().value_from_datadict(data, files, name)
        print(values)
        queryset = self.get_queryset()
        pks = queryset.filter(**{'pk__in': [v for v in values if v.isdigit()]}).values_list('pk', flat=True)
        cleaned_values = []
        for val in values:
            if represent_int(val) and int(val) not in pks or not represent_int(val) and force_text(val) not in pks:
                val = queryset.create(name=val).pk
            cleaned_values.append(val)
        return cleaned_values
```
Thanks for all the help appreciate it!
