### ISSUE TITLE
problem with inline select2

### ISSUE THREAD

**Issue by mirzadelic** [applegrew/django-select2#65]
Hi,
when i click on "add new" to inline, there is select2 field, but i can't choose anything, no options in it:

``` python
class UnosOperacijeForm(forms.ModelForm):

    class Meta:
        model = ModelOperacija
        widgets = {
            'operacija': Select2Widget(attrs={'style': 'width:120px'}),
        }

class ModelOperacijaInline(admin.TabularInline):
    model = ModelOperacija
    extra = 0
    form = UnosOperacijeForm

class ModelOperacijaAdmin(TranslationAdvModelAdmin):
    inlines = [ModelOperacijaInline]
```

Any solution?

**Comment by RamezIssac** [comment]
Hello, 
I've come to inform you of the new added jQuery events when an inline form is added or removed on the change form page, in Django 1.9.
https://docs.djangoproject.com/en/1.9/ref/contrib/admin/javascript/
I think this would help solve this issue.

Regards;

**Comment by codingjoe** [comment]
@RamezIssac thanks!

**Comment by jrief** [comment]
I'm still encountering this problem with Django-Select version 5.8.6 and Django-1.9
Has this been fixed somehow, or am I just doing a silly mistake? I don't see any event handlers for ``formset:added`` as mentioned in the Django docs referenced by @RamezIssac .

**Comment by codingjoe** [comment]
@jrief that's a good point, but this is something, that might be more interesting for the implementation of select2 in Django. That I have developed for Django version 1.11
