### ISSUE TITLE
4.2.2 bug... AttributeError using AutoModelSelect2Field / AutoHeavySelect2Widget

### ISSUE THREAD

**Issue by jrvidotti** [applegrew/django-select2#73]
Hi Applegrew!

This code below worked until 4.2.1... using 4.2.2, a error is trowed:

- 'CityChoices' object has no attribute 'empty_values'

class CityChoices(AutoModelSelect2Field):
    queryset = City.objects
    search_fields = ['name__icontains']

class SomeForm(ModelForm):
	city = CityChoices(widget=AutoHeavySelect2Widget())

**Comment by george-silva** [comment]
I downgrade the latest version (4.2.1?) to 4.0.0 and everything works fine.
