### ISSUE TITLE
Add extra parameters to heavy fields ajax

### ISSUE THREAD

**Issue by arminbalalaie** [applegrew/django-select2#92]
I want to add extra parameters to my ajax request to Select2View. how can I do this ?

**Comment by vishes-shell** [comment]
## For future seakers

For version 6.0.2 of django-select2. The working solution is to subclass your desired widget and extend `build_attrs` method.

```
your_delay = 1000

class SomeWidget(ModelSelect2Widget):
    search_fields = [
        'search_field__icontains',
    ]
    model = YourModel

    def build_attrs(self, *args, **kwargs):
        attrs = super().build_attrs(*args, **kwargs)
        attrs.setdefault('data-ajax--delay', your_delay)
        return attrs
```

Basically all that's being returned from `.build_attrs()` with prefix `data-ajax--` will be passed to `ajax` js method.
